### ISSUE TITLE
Digital Team

### ISSUE THREAD

**Issue by Mattdgt** [manga-download/hakuneko#1331]
Hi! I'm Matt the founder of the Digital Team. I saw that you implemented hakuneko by also adding our site. By doing so, you gave people the ability to take without us wanting our scans. Not everyone uses the scans as they should and seeing ours on sites that do not belong to us and that earn with the "work" of others is not good for us. So I kindly ask you to remove the way to take from us.
I thank you for your attention.

**Comment by 27136773** [comment]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions then the removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

1. How much traffic is caused by HakuNeko?
2. How much is it compared to overall traffic (percentage)?
3. How did you measure those analytics (framework)?
4. How exactly did you distinguish traffic caused by HakuNeko from those caused by other scraper-bots?
5. Are you already using a proper configured CDN to reduce bandwith and prevent scraper-bots (e.g. CloudFlare's free plan with IAUM)?
6. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by 27136773** [comment]
See also #532

**Comment by Mattdgt** [comment]
QUESTIONAIRE
1. I have never used traffic control programs. in fact my problem is not what hakuneko consumes us as data traffic, but what hakuneko does by taking our manga without permission.
2. look up!
3. look up!!
4. look up!!!
5. Yep!
6. Absolutely yep, to any aggregator robot I will ask for the removal of our site.

**Comment by 27136773** [comment]
As soon as all removal conditions from above are fulfilled, the website will be removed from HakuNeko:

- [ ] Ads must be non-intrusive (blocking content during scroll, expand on click)

<img width="300" alt="Screen Shot 2020-03-17 at 3 52 08 PM" src="https://user-images.githubusercontent.com/27136773/76871486-66943600-686b-11ea-8d58-786b91a80c15.png">
<img width="300" alt="Screen Shot 2020-03-17 at 3 53 16 PM_" src="https://user-images.githubusercontent.com/27136773/76871502-6bf18080-686b-11ea-86b5-5b058c653ca6.png">

- [ ] Only a single Ad per page

<img width="300" alt="Screen Shot 2020-03-17 at 3 55 47 PM" src="https://user-images.githubusercontent.com/27136773/76871576-84619b00-686b-11ea-8f11-2777a4e2c24e.png">

- [x] Ad must not disrupt the reading flow

- [ ] Provide direct download links for chapters

<img width="300" alt="Screen Shot 2020-03-17 at 4 15 48 PM" src="https://user-images.githubusercontent.com/27136773/76871611-8fb4c680-686b-11ea-82e6-6472699722f2.png">
<img width="300" alt="Screen Shot 2020-03-17 at 4 16 40 PM" src="https://user-images.githubusercontent.com/27136773/76871622-93e0e400-686b-11ea-8762-cf6645b33667.png">

**Comment by Mattdgt** [comment]
As far as advertising is concerned, I could also give you reason, even if I don't see the reason why you should come to syndicate on my work. But as for the last point, if I don't want people to download the scans just to not see them on other sites, why would I now stay here and write to remove the site from hakuneko?

**Comment by Mattdgt** [comment]
As far as advertising is concerned, I could also give you reason, even if I don't see the reason why you should come to syndicate on my work. But as for the last point, if I don't want people to download the scans just to not see them on other sites, why would I now stay here and write to remove the site from hakuneko?

**Comment by Sheepux** [comment]
> 1. I have never used traffic control programs. in fact my problem is not what hakuneko consumes us as data traffic, but what hakuneko does by taking our manga without permission.

Simple question regarding this part : Do you own this manga or do you simply fan-scanlate it as a hobby that is not supposed to be a source of money ?

Ronny's questions are (as i understand it) : is hakuneko putting a strain on your server/hobby, or on your income ?

**Comment by Mattdgt** [comment]
Simple, if I work on a manga I wouldn't want to see it end up on another site other than mine, even though I know I'm doing something illegal. There is not only hot or cold, black or white. There are also other reasons besides the source of income or the servers.
Whether it's a hobby or something else, it bothers to see your material uploaded to other aggregator sites.

**Comment by Sheepux** [comment]
Coldly from a technical point of view: Hakuneko is not uploading the content anywhere and doesn't have a website, it's somekind of browser that strips everything on the page (however additionally it provides a download option to browse offline when people are traveling). Therefore it does indeed strips ads (just as i would with firefox using ublock). Hakuneko is not hiding the credits of the source as you have to get it through the connector stating where it's from, however it could be improved by giving additional information when clicking on a manga.

Anyway, regarding the actual request, i'll leave it to Ronny and the community review.

**Comment by maxtron95** [comment]
So you don't see a problem with [FMD](https://github.com/fmd-project-team/FMD) and other manga downloaders doing the same thing as FMD also has Digital Team as well?

**Comment by 0xh3LL0** [comment]
agree with Sheepux, hakuneko is just a browser with download function, 
even without hakuneko, i can just simply go to your site with ublock enabled, 
and download your release with add-on like ImageAssistant,
so, there is no differences, **with your consent or not**, people can download it anyway, 
it just that hakuneko simplify the process, 


side note,
i know how's your feelings though, since i'm translator as well, but i'm cool as long as they didnt remove my credit page.

**Comment by 27136773** [comment]
Based on the discord community voting the removal request has been **rejected**.
10 votes for approval
26 votes for rejection
