### ISSUE TITLE
Docker Releases?

### ISSUE THREAD

**Issue by GlassedSilver** [manga-download/hakuneko#1384]
Having this application run centralized on my home server and adding items to my download list from any device would be lovely. Downloading directly into my comic server's directory and then pulling straight from that either streamed with my browser or through Tachiyomi.

PC stays off, or heck I even remote add jobs since my home server is always running, my PCs not so much.

I don't know how to create docker applications from scratch (that is GNU/Linux binary to DockerHub-ready package), however I do know how to take a DockerHub release and then make a Community Application from it for my fellow unRAID users, so I could help with that.

**Comment by 27136773** [comment]
Maybe related: #1012

**Comment by Sheepux** [comment]
I don't think that it's the same request (flatpack is just a packaging format). 
This is a request to transform haku into a remote solution (web server) deployed as a docker container.
That would require a rework as the current implementation is linked with electron. #TooMuchTime

**Comment by GlassedSilver** [comment]
> 
> 
> I don't think that it's the same request (flatpack is just a packaging format).
> This is a request to transform haku into a remote solution (web server) deployed as a docker container.
> That would require a rework as the current implementation is linked with electron. #TooMuchTime

Didn't know electron cannot run in Docker... Kinda curious why that would be? You can, afaik, have any dependency run in Docker containers and the GUI can be served by guacamole.

Applications like Calibre, filemanagers and many more are served that way.

Flatpack is indeed unrelated. To my understanding a Docker container can be as compatible as any VM really. I have never set up a Docker container myself, that's why I'm not rushing in with a PR instead, however I think the utility is definitely there for an application like this.

Maybe this [Google search ](https://www.google.com/search?client=firefox-b-d&q=electron+in+docker+container) can inspire a few thoughts in the people who are a little closer to the code than I am? :) (I hope this doesn't come off as condescending, if there's anything I can do myself I'll be happy to help!)

**Comment by Sheepux** [comment]
If i'm not wrong, your question is about remote invocation of the download function.
That would be covered by:
* Expose the web interface (that's my previous response: no we cant as the download process relies on the chrome functions, would require rework to do it purely in nodeJS).

Your last point is about runing the app as it within a docker container.

* Run it as an application within docker (yes, you can). You require access to a x-server for the GUI to remote click on the electronUI). It doesn't cover the "remote download" feature that i think you're looking for.
That's only usefull if you don't want to install it on your system and want to use docker instead of usual install process.

**Comment by Sheepux** [comment]
If you want to cover the second scenario: https://github.com/chris102994/docker-hakuneko.

User maintained. Not by the hakuneko project itself. #VNC version

**Comment by GlassedSilver** [comment]
Well yes, I want to run this not on my desktop, laptop and (impossibly so) my phones and tablets.

It'd be great if the action took place on my server, which is a home server, so not really remote, but CAN be remote. Either way it's centralized to my workflows. Start a job on machine A, manage the job later somewhere else. No deduplicating of my staging download folder for digestion into my comic server.

As for user maintained, that's kinda why I asked... An official image would let me rest more easily. VNC is also a little downer, but I'd take what I can get, especially if it's official. Thanks for your quick replies by the way, very appreciated. <3 :)

**Comment by Sheepux** [comment]
I guess Ronny will probably close this request as "nobody" will be working on it because of 3 reasons:
* not a priority
* rework = time that is currently precious, so this request would be onhold for quite a long long time.
* and mainly because : auto downloading / Scheduled downloading is not within hakuneko's spirit. (note: it's also intentional that hakuneko exec doesn't have arguments for such case). We understand the use case though.

Ronny could provide additional details regarding the last statement.
You can also refer to this somewhat related question : https://github.com/manga-download/hakuneko/issues/1306

**Comment by GlassedSilver** [comment]
I never mentioned auto downloading. Fair enough though on the other two.

Little bit off-topic maybe, but since this is getting yanked anyhow I guess it doesn't disrupt the flow and I don't wanna create an issue for this short question: can Hakuneko stripe volume #'s from the filename? Currently I'm using FMD which I'm actually very happy with now that it got forked and is actively maintained again, however outside of scripting a post-process myself it keeps volumes in the filename. This can be a problem for sorting, when different groups scanlated a series resulting in some chapters being listed as `Vol. 3 Ch. 35` and others as just `Ch. 20` for example. If Hakuneko deals with this in a better fashion that'd be interesting to know.

**Comment by Sheepux** [comment]
Options "Chapter title format". Such questions are welcomed on the help channel on the discord. 
Don't know if it's used by the download process as well :)

**Comment by GlassedSilver** [comment]
> 
> 
> Options "Chapter title format". Such questions are welcomed on the help channel on the discord.
> Don't know if it's used by the download process as well :)

Not really an active user, just in the considering camp and I loathe using Discord most of the days. Anyhow thanks for the feedback. :)

**Comment by chris102994** [comment]
@GlassedSilver I have actually created a dockerized version of this for my specific use with unRaid.

[Link](https://github.com/chris102994/docker-hakuneko)
[unRAID Template](https://github.com/chris102994/docker-templates/blob/master/chris102994/hakuneko.xml)

I would like to note that the current build is still broken due to [This Bug](https://github.com/manga-download/hakuneko/issues/13) I will be reviewing it in the next few days.

**Comment by Sheepux** [comment]
Stalling issue, i guess that it can be closed now :)
Feel free to create a Feature Request about a "centralised local downloader" (and describe the uses cases as it seems quite complex), but as discussed before this won't be done before long.
