### ISSUE TITLE
newtoki 

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#1489]
> **From:** HakuNeko User

**Version:** [6.1.7@1069c5](https://github.com/manga-download/hakuneko/commits/1069c5)

newtoki chapters aren't showing on the app but when i visited the website, all the chapters are there. 

<details><summary>What has been done?</summary>

☑ Read the Quick Start Guide: https://git.io/hakuneko-quickstart
☑ Tried Troubleshooting: https://git.io/hakuneko-troubleshooting
☑ Done Website Interaction: https://git.io/hakuneko-websiteinteraction
☑ Searched for Similar Issues: https://git.io/hakuneko-issuesearch

</details>

**Comment by 27136773** [comment]
- They changed their domain to https://newtoki58.com
- They added a new Captcha protection which [needs to be solved manually](https://github.com/manga-download/hakuneko/wiki/Manual-Website-Interaction#2-captcha-protection) before entering the site
- They aded a temporary IP ban (~1 hour), not yet sure if this ban results from to many consequtive requests or when the Captcha was not solved correctly

**Comment by XenonR** [comment]
Was it a fluke? Works for me:
![Untitled-1](https://user-images.githubusercontent.com/18627623/80910174-fd3e8880-8d2d-11ea-857c-1d72d4321f79.gif)

**Comment by 27136773** [comment]
Still [working on this](https://github.com/ronny1982/hakuneko/commits/newtoki), but haven't yet figured out how they distinguish between connections from Browser and connections from HakuNeko... still investigating

Since throttling has no effect yet it may be an asynchronous request via timeout which is send from the browser, but obviously not from HakuNeko

**Comment by 27136773** [comment]
The IP banning seems to be based on HTTP request.
Spamming dozens of page requests in browser works fine, spamming dozens of requests from command line will result in IP ban.

They probably evaluating the requested resources, since the browser seems to load scripts, images, perform AJAX requests, ... and from command line only the HTML page is requested, without loading any of its resources.
