### ISSUE TITLE
[Scantrad-union] Missing manga from partner 

### ISSUE THREAD

**Issue by Zarh** [manga-download/hakuneko#1591]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
We can't see the manga from the partner page : https://scantrad-union.com/partenaires/

**To Reproduce**
For example : https://scantrad-union.com/manga/partenaire-second-life-ranker/ is missing

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by XenonR** [comment]
@Zarh I can include the mangas from https://scantrad-union.com/partenaires/ but there is no reference to (1) https://scantrad-union.com/manga/partenaire-second-life-ranker/ Instead there's a reference to (2) https://scantrad-union.com/manga-partenaire/ranker-who-lives-a-second-time/ which seems to be the same manga, but with different chapters.
Also since (2) is just a link collection to mangadex I miss the point in adding it.

Overall some of the partenaire mangas seem to be original but a lot are just links to other sites. So i feel the connector is good as it is right now.

**Comment by Zarh** [comment]
**Sorry !!** I didn't see your message previously...

So, you are right the link i gave previously wasn't good. So, the link hakuneko use to get the list of manga is this one : https://scantrad-union.com/projets/  

I think it's better to use this one because it's seems complete : https://scantrad-union.com/manga/

But in this list there is a TAG "[Partenaire] " in the title of the name of mangas translated by their partner, can you also remove it when you load the titles in hakuneko, please ?


Please re-open the issue...

Again, I'm sorry for the delay.

**Comment by Zarh** [comment]
@XenonR  @ronny1982  

Hi, I didn't know if read my previous message. So, i'm mentioning you just to be sure...

**Comment by XenonR** [comment]
> Hi, I didn't know if read my previous message. So, i'm mentioning you just to be sure...

I'll have another look when time allows it.

**Comment by XenonR** [comment]
@Zarh Your last suggested list made more sense. Enjoy.
