### ISSUE TITLE
[Feature] Automatically retry failed downloads option

### ISSUE THREAD

**Issue by Draw99Gray** [manga-download/hakuneko#1593]
It's quite frustrating to download from Mangadex since their servers are quite shoddy, and no other aggregator site has that many manga updated nor the groups themselves working and uploading to the site

I'd like to suggest a feature to retry automatically failed downloads, like a box you can tick

the true question would be play and stop buttons for downloads but i guess that gets too close to "download manager" and you guys don't have that kind of vision for the software

**Comment by MarissaBlackwing** [comment]
If this gets added, I'd like to request that this be an optional feature that is manually enabled in the settings. It would be easy to end up in a sort of 'failure loop' otherwise, especially since there currently doesn't appear to be a cancel/remove download option outside of closing the window altogether.

**Comment by 27136773** [comment]
This is no longer appropriate since MangaDex now tries downloading from a list of servers
