### ISSUE TITLE
unable to keep HakuNeko upto date on Windows 10 

### ISSUE THREAD

**Issue by Iloveboobs84** [manga-download/hakuneko#1628]
I don't if it's a security issue with Win 10 but it appears I can't keep the Nightly version up to date because when I click the refresh button/update listing button it just reloads the same number count for manga from the sites. Trying to find a manga on MangaDex and there Title ID for it is 43511 which is the 43,511 manga uploaded to there site. But when I try searching by Name for the manga it wouldn't appear because the Count in the HakuNeko App only goes to 35,634 and the manga was first added over 9 months ago to MangaDex. Roughly there is a difference of 7,877 manga missing from the HakuNeko App that isn't updated.

**Comment by Iloveboobs84** [comment]
why did you close it i didn't even get to reply and FAQ#5 only said to use  Link Copy & Paste feature to access the latest mangas within HakuNeko but never address HOW TO do that because I don't know!

**Comment by ronny1982** [comment]
I closed it because this is not a bug with the software.
Additional information can be retrieved from the Wiki or from Discord.

Copy & Paste is described in the [Quick Start - Manga List Panel](https://github.com/manga-download/hakuneko/wiki/Quick-Reference#manga-list) the explaination for the first button.

**Comment by Iloveboobs84** [comment]
I've read that QuickStart BS 3x now and there is NOTHING referring to Using the Copy and Paste in the APP. Do you guys just blindly answer a question or what? PLEASE Show me where it reads Copy and Pastes for downloading manga that Isn't updated to Haku because you don't want to update the CDN.

**Comment by Iloveboobs84** [comment]
Where is the Discord channel because you're not helping at all. I have the Nightly Version and there is NO WAY to copy and Paste mangas that aren't updated because someone is not supervising the app to ensure it's up to date. I've read the Quick Start listing and AGAIN there is NOTHING REFERRING to HOW TO copy, Paste manga in from websites to download.

**Comment by ronny1982** [comment]
The Quick start mentioned the clipboard and gave a sample.

![image](https://user-images.githubusercontent.com/27136773/80739298-7a8fb080-8b16-11ea-9f10-56f7b5086cc5.png)

----

The discord channel is linked at the top of the GitHub project page.

![image](https://user-images.githubusercontent.com/27136773/80738999-153bbf80-8b16-11ea-9bc1-8daf6f744e0d.png)

----

You are welcome to make suggestions to improve the Wiki.

Since this is going to escalate i have to refrain from any direct responses from now.
Further communication requires one of the other contributors to become a mediator.

**Comment by Iloveboobs84** [comment]
This wasn't or wouldn't escalate if you JUST answer the question the first time about how to use the copy/paste function you claim the APP has your now calling the Clipboard. What is it Copy and Paste or clipboard and there aren't any clear directions on how clipboarding the links work either. I've searched for 30mins on the MangaDex site while the App was open and there isn't any about copying the link to the clipboard to save links to open in the app. You're just saying it can be done without explaining How because you believe it's self-explanatory. It would be easier if you had a section that was just for using the Clipboard/Copy/paste function and labeled it HOW to for DUMB DUMBS like me.

**Comment by Sheepux** [comment]
There is a section (he even copied you the interesting part) stating  that you have to click on this button when the manga link is in your clipboard. If you don't understand what those means, you should not use internet.

**Comment by Sheepux** [comment]
User requested help on the discord. Got the exact same reply by a community member.
I'm considering that the user was not willing to read the guides that describe exactly how to do it with screen captures ...
Closing this ticket.
