### ISSUE TITLE
[Feature]Manga website link beside manga in chapter list

### ISSUE THREAD

**Issue by Sole-Chain** [manga-download/hakuneko#1720]
Similarly to #653, I want a to be able to find updated chapters of the manga I read daily, 
but I think another solution in comparison to having the latest chapters found automatically 
could be to be able to see the original link of the manga by right clicking it it the chapter list.

This would mean that the user could then use the copy from clipboard feature to manually find the latest chapter in a shorter amount of time than it would take them to go to the website in HakuNeko and search the manga manually, and be helpful if the user wants to do this consecutively.

HakuNeko Version 6.17

**Comment by Sole-Chain** [comment]
I just realized that the format between the websites URL and the way they are saved in the chapter list for the website are different and so they are unable to be used interchangeably (example provided, battle frenzy, manually selected vs clipboard link, wuxiaworld.site).

I believe this will make the feature unable to be simply implemented and subpar in comparison to #653 and so I am closing this thread.

![Battle Frenzy - Manual](https://user-images.githubusercontent.com/65174440/81583816-3ee9c600-93f5-11ea-80e4-95788b4f2dff.png)
![Battle Frenzy - Clipboard](https://user-images.githubusercontent.com/65174440/81583864-4d37e200-93f5-11ea-82a4-01bd5ab47e25.png)

**Comment by Sheepux** [comment]
Nah, it can be easily done as we can find the complete chapter URL.
However it's somewhat useless as you just check the difference with the bookmark (this is what is done with #653 ). Note: it requires that the list is well ordered (this why #653 is currently stuck)

I think the use case could be to find out why there are pages missing in the download/preview by going directly on the website page (instead of having to find it manually).

You could reopen it if needed.
