### ISSUE TITLE
[Bug] Downloaded file is empty in Mangasail

### ISSUE THREAD

**Issue by Dr-Shiro** [manga-download/hakuneko#1810]
Hello
I have trouble with Mangasail where when I download a chapter, the file appears empty
Please fix this problem quickly
thank you

**Comment by 27136773** [comment]
Which manga/chapter?

**Comment by Dr-Shiro** [comment]
The problem with all chapter

**Comment by 27136773** [comment]
Reproducible with Black Clover - Chapter 252

Next time please just provide a manga and chapter for reproduction (even if you assume the problem affects all mangas and all chapters).
The developers cannot afford to search through thousands of mangas and chapters to confirm the issue...

**Comment by Dr-Shiro** [comment]
But I tried downloading several chapters from several manga and all chapter files are empty!

**Comment by 27136773** [comment]
It is always important to provide a single manga and chapter for reproduction, the following example is just one of many use cases why it is so important:

1. User says all mangas/chapters are broken (the user tested with `Manga X, Chapter 5`)
_Also i have my doubt that the user manually confirmed that all thousands of mangas/chapters are not working_
2. Developer uses random `Manga Y, Chapter 17` to fix and resolve the issue.
3. User is annoyed, because `Manga X, Chapter 5` is still not working.

Yes the problem with `Manga Y, Chapter 17` was a completely different issue, so it did not fix the issue with `Manga X, Chapter 5`

You see why it is important that the user and the developer are referring to the same information for reproduction as close as possible?

Furthermore i don't see any advantage of writing `All Mangas, All Chapters` instead of `Black Clover, Chapter 252` ...

----

Unfortunately it is common behavior that the users always keep saying `all mangas / all chapters` are broken when they are asked to provide a sample manga / chapter to reproduce the issue... and sometimes i really just want to close these issues as non-reproducible

**Comment by Dr-Shiro** [comment]
Thanks for the great support
Sorry, I did not know that determining the chapters is so important

However, these are some of the chapters I have tried to download now, and the files are empty
One piece, Chapter: 978 + 979 + 980
black clover, Chapter: 249 + 250 + 251 + 252
Boku no Hero Academia: 272 + 273
