### ISSUE TITLE
Cant download anything 

### ISSUE THREAD

**Issue by bryamamigo** [manga-download/hakuneko#194]
I was so hype about this app but so far i cant make it work.
i cant download anything when i try it i get the same error over and over again 
![Untitled](https://user-images.githubusercontent.com/37577648/59401516-edf6cb00-8d68-11e9-8e5a-96c3ec8b0616.png)

**Comment by 27136773** [comment]
After an sophisticated analysis the following conclusion of the problem was found:

- When the website is opened for scraping, the images starts loading
- Since some chapters have many images this may take a while until this operation is complete
- HakuNeko has a timeout of 60 seconds to wait for the website
- The images and therefore the website is not loaded within the timeout
- Loading the images of the website is not required, HakuNeko just needs the image resource identifiers
- Disable image loading leads to a problem with KissManga
- KissManga has a bug that leads to a deadlock when an image cannot be loaded
- The onerror method for the images will set a new image resource (actually same resource with just a random parameter)
- The image resource fails loading and calls the error method again => deadlock

Needs to find a way to fix the bug on KissMangas website through HakuNeko (i doubt KissManga will fix their bugs in favorite of HakuNeko)
