### ISSUE TITLE
[idk what to call it] why are useless connectors still in the connectors list

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#1989]
a Connector that you cant get a list of manga from is useless like "line webtoon" if you cant get a list of manga from it, and arent willing to support old list when they get a bit broke #1635,  #1861,  and, #1988 then why do they still show up in the connectors list?

**Comment by 27136773** [comment]
Users will complain when there is no manga list, users will complain when it takes hours to synchronize a manga list... This is status quo. For LINE it took like 2~3 hours on the old 1 GBit CDN to do a nightly sync, therefore it would take much longer for users.

Th websites are not removed, because copy & paste still allows bookmarking and downloading.

There was a suggestion that users may share their downloaded lists, but from similar experience i doubt this will work out, it will probably become an outdated collection of manga lists.

**Comment by Sheepux** [comment]
What was the main issue with the CDN scripts ?

**Comment by Robonau** [comment]
if the CDN is no longer a thing then why not give users some way to update sites currently like "line webtoon" as well as any future connectors that go the same way

**Comment by Robonau** [comment]
maybe something that could just run on a raspberry pi continuously, given the main bottle neck seems to be the limited requests/s from the sites

**Comment by Sheepux** [comment]
I can host such scripts within my kubernetes cluster (with node autoscaling), it would be transparent for me. That's why i'm asking what is the main issue with the CDN scripts (is it maintenance issue or something else?)

**Comment by 27136773** [comment]
Scripts are breaking, cannot solve captchas, needs to be updated frequently when website changes, ASN got blacklisted by some websites, ...

**Comment by 27136773** [comment]
If someone wanna check it, just clone https://github.com/manga-download/hakuneko-cdn and run `npm install` followed by e.g. `npm run linewebtoon-en`
It will update the manga list in the corresponding folder of the local repository

**Comment by Robonau** [comment]
i made an ahk script that does it (i don't know js, like at all) (linewebtoon-en)
[linewebtoon connector attempt.zip](https://github.com/manga-download/hakuneko/files/4893317/linewebtoon.connector.attempt.zip)
it takes a few hours to run, but it should output a functioning list (i have run it to completion)(there are some duplicates in the end,not that that causes any issues)
