### ISSUE TITLE
Impossibilité de télécharger des tomes/volumes sur Japscan

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#2000]
> **From:** HakuNeko User

**Version:** [6.1.7@508cba](https://github.com/manga-download/hakuneko/commits/508cba)

Impossibilité de télécharger des tomes/volumes sur Japscan, on ne peut uniquement télécharger que des chapitres. Par exemple pour Eyeshield 21, on peut télécharger les chapitres 242 à 333 car ils sont séparés des tomes mais impossible pour les volumes 1 à 27.

<details><summary>What has been done?</summary>

</details>

**Comment by Robonau** [comment]
support is provided in English.
but from google translate 
it seems japscan connector has a problem with getting full volumes (vol 28 onward works cause it is individual chapters not a full volume)

![](https://i.imgur.com/03Hs9vh.png)

when it gets to displaying whole volumes instead of chapters in volumes 
hakuneko cant grab the volume name for some reason

![](https://i.imgur.com/z2NeMgW.png)

(my chapter title format is "Chapter %CH% %t% %vol%")

**Comment by 27136773** [comment]
Volumes have a large amount of pages, read this:
https://github.com/manga-download/hakuneko/issues/1451#issuecomment-615505322

Chapter number cannot be extracted because there is no chapter number in the name, certain format rules will not work in this case.

![image](https://user-images.githubusercontent.com/27136773/87073472-c00ae100-c21d-11ea-8533-81acba8fc8c4.png)
