### ISSUE TITLE
some connectors don't grab chapter data properly

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#2006]
**Did you read [the troubleshooting guide](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)**
Yes

**Describe the bug**
some sites like koomanga it doesn't grab the chapter number so with "Chapter %CH%" as chapter title format you end up with 
![](https://i.imgur.com/YUz4rbt.png)
i think this is because they do "chap 123" and not "chapter 123"
adding %t% to the end of chapter title format gets you the chapter but you end up with 
![](https://i.imgur.com/ckseOKM.png)

**To Reproduce**
1. using the koomanga connector
2. look at any manga

**Expected behavior**
expected it to grab the chapter number

**Context (please complete the following information):**
 - OS: [Windows10]
 - HakuNeko Version [master from a couple days ago]

**Comment by 27136773** [comment]
This is within the expected behavior as the tooltip says this is experimental and may fail in some cases.

Reason:
A single extractor tries to get the parts through applying some generic regular expressions to avoid the effort of implementing a dedicated extraction for each website.

Rules may still be improved to work with KooManga
Related: https://github.com/manga-download/hakuneko/blob/036722c86f61d51b6e34bbba3088e227eab8909e/src/web/mjs/engine/Manga.mjs#L161

**Comment by Robonau** [comment]
i assume adding |chap| in to "reCh" (where the rest of the Synonyms for chapter) would fix it for koomanga, though i'm not sure it is used frequently enough (by enough connectors) to be worth

**Comment by Robonau** [comment]
also side point, why do you add the padded zeros even if chapter/volumes gets nothing

**Comment by 27136773** [comment]
Ensure sorting works even on software that does not support natural sorting
