### ISSUE TITLE
[Feature] Download all chapters into 1 folder, without subfolders

### ISSUE THREAD

**Issue by NeverSm1le** [manga-download/hakuneko#2014]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
add a checkbox that would allow all chapters to be downloaded into a single folder, next to the "download all chapters currently show..." button

**Describe alternatives you've considered**
There is no alternatives in the current version.

**Context (please complete the following information):**
 - 6.17

**Additional context**
In case I haven't explain it clearly to you guys above, what I mean is all pages get downloaded into a single folder, without "chapter 1", "chapter 2",... folders inside it. Chapter 1, for example, going from page 1-20, chapter 2 will continue from page 21-40, and so on. It will be incredibly helpful for people who wants to pack mangas into volumes rather than chapters.

**Comment by 27136773** [comment]
This can be simply achieved by using the `Post Command` setting or make a custom script to copy and rename the files.

The effort is way to high, to many adaptions and edge cases...
- How should files be named, when downloading chapter 37 HakuNeko does not know which number to start
- Reader support also needs to be implemented
- What should happen with already existing files, since HakuNeko does not know which images belongs to which chapter
- What should happen when the user is downloading in CBZ, PDF, EPUB
- ...
