### ISSUE TITLE
[Feature]being able to change the install directory

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#2057]
**Is your feature request related to a problem? Please describe.**
as it is right now you can't change where hakuneko installs, this could be a problem with limited c drive space (ssd boot and hdd for storage)

**Describe the solution you'd like**
an option in the installer to change the install directory 
right now its just :
. shortcuts?
. installing

**Describe alternatives you've considered**
if building it yourself it makes a setup folder containing the install
just moving the install files would probably work(haven tested)

**Context (please complete the following information):**
 - Your current HakuNeko Version [master]

**Additional context**

**Comment by newaccforhc** [comment]
Why not use portable version then?
https://github.com/manga-download/hakuneko/releases/download/nightly-20200705.1/hakuneko-desktop_8.3.4_windows-portable_amd64.zip

**Comment by 27136773** [comment]
Request is probably for Windows only since linux and macOS were not mentioned.
I think point and click users just want the installer to be as simple as possible, users that want more control are going for the portable version anyway.

However this is probably just a [one line change](https://jrsoftware.org/ishelp/index.php?topic=setup_disabledirpage) in the auto generated InnoSetup [script](https://github.com/manga-download/hakuneko/blob/c2b0e0f1347159c95559715713bab207b63052a4/build-app.js#L665) that builds the Windows installer...

**Comment by Robonau** [comment]
yes in my case it is for windows, i have little knowledge about mac and linux so didn't comment.

why would the users that want more control use portable? its functionally the same(other than setup putting some stuff in appdata rather than in the install dir) isn't it? 
being able to keep your settings and shit after changing versions would make more sense for someone that more frequently updates (someone that might want more control)

a 1 line change is good :)

**Comment by 27136773** [comment]
Need to confirm that a fresh install of HakuNeko did not provide the selection of installation directory as mentioned, since the installer is set to automatic and therefore it is expected to ask the user where to install.

Incremental installations should not ask for the directory, they should use the existing one...

**Comment by Robonau** [comment]
oh its me being dumb then (i was reinstalling over a current install)
il close this then
