### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by barhoomswi** [manga-download/hakuneko#215]
Can not download from teamx site

**Comment by 27136773** [comment]
Cannot be reproduced.
Which Manga/Chapter did not work?
Have you read and tried [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)?
Is there any error in the console output (F12)?

**Comment by barhoomswi** [comment]
Yes I have read but the latest chapters from the team x site can not be downloaded even though I can download the previous chapters

**Comment by 27136773** [comment]
Reproducable with "Why she gad to go to the Duke" chapter "86.2"
Website now seem to use Ad shortened links instead of chapter links.

![image](https://user-images.githubusercontent.com/27136773/60073945-0d570600-9722-11e9-9450-d9170136e123.png)

The link is flooded with adds, it is not even possible to reach the chapter for online reading on their website, so HakuNeko's behavior seems to be correct.

**Comment by 27136773** [comment]
The following steps where required to get to the chapter site:

1. Solve the captcha on the [ad-wall page](http://kora-2day1.com/VMOG7c)
2. Click the `Click here to continue` button and wait until the timer is done
3. Click the `Get Link` button to go to the [chapter page](https://team1x1.com/v8AJUS/)

**Comment by 27136773** [comment]
It is not worth the effort to break this ad-wall, as solution HakuNeko will hide any chapters that are hidden behind ad-pages.
