### ISSUE TITLE
[Novels of Tapas] Connector not working

### ISSUE THREAD

**Issue by snickerdooodle45** [manga-download/hakuneko#2198]
Did you read the troubleshooting guide
Yes

Is the website of the connector working properly / are you able to see the manga within your browser
Yes

Describe the bug
HakuNeko will be able to download the chapters from the novels, but will result in corrupt PDF and EPUB files that cannot be opened. The chapters as well cannot be accessed in the viewer of HakuNeko

To Reproduce

1. Tapas
2. Tapas - Beastly Beauty
3. All Chapters
4. The book is corrupt and cannot be opened

![1BD0E24B-C06D-4A7E-B6A4-5061252DC570](https://user-images.githubusercontent.com/69394376/90557934-dd907a80-e1cd-11ea-87fa-d16464f772db.png)

HakuNeko (please complete the following information):

Version 6.1.7

**Comment by 27136773** [comment]
It seems Tapas has now also [text based novels](https://tapas.io/novels) in their assets, but HakuNeko right now only supports [webtoons](https://tapas.io/comics).
PDF/EPUB output is not affected, they are just empty because no images are found in a text novel.

Similar to WorpressMadaraNovel, Tapas should be extended to detect the media type and properly convert text novels to an image.
