### ISSUE TITLE
[Mangago] Connector not working

### ISSUE THREAD

**Issue by sakuyakudou10** [manga-download/hakuneko#2207]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The connector cannot be accessed and missing from Hakuneko, and the bookmarked manga said it (mangago) is unavailable.

**To Reproduce**
1. Mangago to be able to be accessed with Hakuneko

**HakuNeko (please complete the following information):**
 - Version nightly-20200705.1

**Comment by Sheepux** [comment]
Unable to reproduce, the connector can be selected from the list of connectors.
The error message when trying to refresh this connector is clear: use the copy pasting functionnality as hakuneko does not provide list for this connector.

Tried copy paste with http://www.mangago.me/read-manga/curtain/
Worked fine.

Your bookmarks are probably not working because of change (need to rebookmark) but i also suggest to try using the manual website interraction to see if there is another trouble (click on the link on the connector within hakuneko).

Might close the ticket soon. Could you provide a screenshot on your issue ?

**Comment by sakuyakudou10** [comment]
It's working now, just as you said I used the copy-paste features and need to rebookmark the manga again. Thanks!

**Comment by Sheepux** [comment]
Note: the connector missing was indeed an issue: see #2209
