### ISSUE TITLE
ZeroScans (Can't download)

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#221]
> **From:** HakuNeko User

Zerescans (Manga: Star Martial God Technique), I can't download it :((

**Comment by 27136773** [comment]
Cannot be reproduced.
Which Manga/Chapter did not work? (You are not trying to download `Star Martial God Technique Video`, because it has no images)
Have you read and tried [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting)?
Is there any error in the console output (F12)?

**Comment by 27136773** [comment]
No further response => closed
