### ISSUE TITLE
Loading takes too looooooooooong

### ISSUE THREAD

**Issue by CarterSnich** [manga-download/hakuneko#2292]
Every loading takes too long;
- start up, checking updates
- loading a website (took more than half an hour)
- loading images (5 secs or more)
- downloading and frequent download failed errors
- loading a single image (a page of a chapter)

Please add a force retry download option on settings.

**Comment by 27136773** [comment]
The description is way to vague and would not allow any tester to verify a possible fix.
Use cases are missing details, no websites/mangas/chapters mentioned, no technical context such as system specs and internet connection, proxy or VPN usage, ...

Based on the given information i can only imply that the cause is a slow internet connection and therefore this is not something that can be fixed with HakuNeko.

**Comment by CarterSnich** [comment]
Okay. Sorry about my that, and thank you for responding.

The website I was browsing was Mangadex.

Can I request a feature instead? A force retry feature that will retry to download a chapter when it failed to download. I was able to download the chapters of the manga I was downloading when I post this issue, but I did a lot of download retries. Also, some sites works and loads fine, but some UI loading still not quite good like 3 to 5 sec but doesn't really bother me that much.

My laptop specs: (but instead it's a 12 GB RAM)
[https://www.cnet.com/products/dell-inspiron-5555-15-6-a10-8700p-8-gb-ram-1-tb-hdd-english/](url)
