### ISSUE TITLE
[Site Delete Request] mangabaz.com

### ISSUE THREAD

**Issue by DexiaSub** [manga-download/hakuneko#2314]
Than thx not need deleted

**Comment by 27136773** [comment]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

1. How much traffic is caused by HakuNeko?
2. How much is it compared to overall traffic (percentage)?
3. How did you measure those analytics (framework)?
4. How exactly did you distinguish traffic caused by HakuNeko from those caused by other scraper-bots?
5. Are you already using a proper configured CDN to reduce bandwdith and prevent scraper-bots (e.g. CloudFlare's free plan with IAUM)?
6. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by 27136773** [comment]
See also #1331, removal from HakuNeko will not prevent anyone else from downloading images, especially not when using a simple WordPress theme such as Madara...
