### ISSUE TITLE
[Line Webtoon (french)]  Connector not working 

### ISSUE THREAD

**Issue by Yunaxigf** [manga-download/hakuneko#2373]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The downloads are failing.

**To Reproduce**
1. Name of connector : Line Webtoon (french)
2. Name of manga : DEAD LIFE
3. Name of chapter : ALL THE CHAPTERS
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.
![Desktop-screenshot](https://user-images.githubusercontent.com/70101547/94232096-f3e8cf00-ff0d-11ea-9727-eb4737f71bf5.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.1.7@5365bd]

**Comment by newaccforhc** [comment]
Can be reproduced.. 

Looks like the images fail to load if Hakuneko makes simultaneous request for all images... I tested by adding throttle and configure the value so that next image will start loading only after previous one is done and it worked... But, I think throttle is a wrong thing to do here.. Server doesn't block for too many requests..

I think doing something (like Lazyloading) to make next request only after the previous image is completely downloaded may will solve the problem...
