### ISSUE TITLE
leviatanscans not connecting

### ISSUE THREAD

**Issue by hakuneko-user** [manga-download/hakuneko#241]
> **From:** HakuNeko User

Hello.

The site has been revamped. I think that's why it won't connect.

Thanks.

**Comment by 27136773** [comment]
The website was tagged as spanish, but looking into random chapters it seems to be english.
Can this be confirmed?

**Comment by giaez** [comment]
the website did provide both English and Spanish translation in some titles, while some others are English-only or Spanish-only. but after the site revamped only the English chapters remain.

**Comment by 27136773** [comment]
Keep tag as English => closed

**Comment by giaez** [comment]
why was this issue closed while Leviatanscans still hasn't connect yet. please fix, thanks in advance.

**Comment by 27136773** [comment]
It has been fixed and tested 2 days ago.
If you still have problems you need to open a new issue, because it is probably a different bug.
Make sure to provide more details what is not working, such as manga/chapter and the output from error console.

Furthermore try [Troubleshooting](https://github.com/manga-download/hakuneko/wiki/Troubleshooting) if not already done.
