### ISSUE TITLE
[Site Request] mangapill

### ISSUE THREAD

**Issue by someonewithakeyboard** [manga-download/hakuneko#2411]
**Name of the website**
mangapill

**Website urls (examples below)**
- Site: https://mangapill.com/
- Manga List: https://mangapill.com/manga/524/black-clover
- Manga example: https://mangapill.com/chapters/524-10001000/black-clover-chapter-1
- Chapter online viewer example: https://mangapill.com/chapters/524-10001000/black-clover-chapter-1

**Languages**
English, 

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by Robonau** [comment]
manga list:
https://mangapill.com/search?genre=1&genre=2&genre=3&genre=4&genre=5&genre=6&genre=8&genre=9&genre=10&genre=11&genre=35&genre=12&genre=13&genre=14&genre=43&genre=15&genre=16&genre=17&genre=18&genre=38&genre=19&genre=7&genre=20&genre=39&genre=40&genre=22&genre=21&genre=23&genre=24&genre=42&genre=25&genre=26&genre=27&genre=28&genre=36&genre=29&genre=30&genre=31&genre=37&genre=41&genre=32&genre=33&genre=34&page=1&status=0&title=&type=0

it uses an OR on genres rather than an AND idk why
