### ISSUE TITLE
[Nhentai] Connector not working

### ISSUE THREAD

**Issue by Ikhnaton-1** [manga-download/hakuneko#2437]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Trying to download any manga results in error: "TypeError: Cannot read property 'replace' of undefined"

**To Reproduce**
1. Name of connector **nhentai** (via pasting link)
2. Name of manga (if connector update is working) **any**
3. Name of chapter (if manga update is working) **any**
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![Capture](https://user-images.githubusercontent.com/73003422/96324776-2a6eb280-0fbf-11eb-8e35-227e51b1d1dc.PNG)

**HakuNeko (please complete the following information):**
 - 6.1.7 windows 64-bit portable

**Comment by Robonau** [comment]
unable to reproduce 
even that exact doujin works fine

**Comment by 27136773** [comment]
Can be reproduced on my end with 6.1.7 by pasting https://nhentai.net/g/333041/
HakuNeko parses html in `<noscript>` tags (this is by design as some websites uses `noscript` tags to prevent scraping).
In this case the `noscript` is not a protection, but a note for users who disabled JavaScript, as a result HakuNeko detects the images twice.

Suggestion:
Either change the CSS query for images to e.g. `div#thumbnail-container a.gallerythumb source.lazyload`
or apply an additional filter to remove these images, e.g. `let pageList = data.filter(element => element.dataset['src']).map(element => element.dataset['src'].replace('t.', 'i.').replace('t.', '.'))`

----

![image](https://user-images.githubusercontent.com/27136773/96472400-b8050900-1230-11eb-9278-21c0a7988c50.png)
*have you noted my awesome censoring skills in the above screenshot?

**Comment by newaccforhc** [comment]
Black brush censoring 😂😂

**Comment by Ace733** [comment]
I don't get it, but I want to read nhentai on hakuneko, can someone provide a video tutorial on how to do so?
