### ISSUE TITLE
[Bug] Download stuck forever only when queuing specific manga

### ISSUE THREAD

**Issue by kokizzu** [manga-download/hakuneko#2527]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
Download always hangs (stuck forever) only when downloading 4 Cut Hero from MangaHere, other manga works fine.

**To Reproduce**
1. Go to MangaHere
2. Click on 4 Cut Hero
3. Stuck forever
4. No error on terminal, but when visiting the manga page manually (not downloading) it shows something like this

```
Connector.mjs:600 ReferenceError: newImgs is not defined
    at <anonymous>:5:29
    at new Promise (<anonymous>)
    at <anonymous>:2:13
    at WebFrame.<computed> (/usr/lib/hakuneko-desktop/resources/electron.asar/renderer/api/web-frame.js:64)
    at WebFrame.executeJavaScript (/usr/lib/hakuneko-desktop/resources/electron.asar/common/api/deprecate.js:114)
    at /usr/lib/hakuneko-desktop/resources/electron.asar/renderer/web-frame-init.js:11
    at /usr/lib/hakuneko-desktop/resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7
    at new Promise (<anonymous>)
    at EventEmitter.<anonymous> (/usr/lib/hakuneko-desktop/resources/electron.asar/renderer/ipc-renderer-internal-utils.js:7)
    at EventEmitter.emit (events.js:200) EventTarget {manga: EventTarget, id: "/manga/4_cut_hero/c000/1.html", title: "Ch.000 - Prologue", file: {…}, language: "english", …}
```

**Expected behavior**
would not stuck, or at least give a timeout to continue download from next manga

**Context (please complete the following information):**
 - OS: Ubuntu 20.04 64-bit
 - HakuNeko Version 6.17@da8633

**Comment by Robonau** [comment]
the problem seems to be that chapter 156 still has 1 image (war.jpg) but it 404s
downloading doesn't seem to catch the 404 error, so just waits for the data forever
idk how to fix
note: lower number chapters have no pages (not even war.jpg) so you get the `newImgs is not defined` error

**Comment by 27136773** [comment]
Cannot be reproduced on my end with https://www.mangahere.cc/manga/4_cut_hero/c000/1.html
Download get not stuck, instead it fails correctly with an error, because there are no images.
The Website has removed the images due to copyright infringement.

If there is a chapter that gets stuck (progress bar does not move) please provide the exact chapter.

----

![image](https://user-images.githubusercontent.com/27136773/97427376-b6180580-1914-11eb-9189-c00b408e3fa7.png)

**Comment by 27136773** [comment]
For chapter 156 it's like @Robonau mentioned, a promise is neither resolved, nor rejected due to image loading failed.
Need to adjust [MangaFox `_getPagesDesktop`](https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/MangaFox.mjs#L106-L117), but it will still load all these weird `war` images which are not reachable...
```javascript
//Get Meta informations from last Image
let lastImage = await new Promise(resolve => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null);
    img.src = pages.slice(-1);
});
//Check if the last image seems to be the usual ad
if(lastImage && lastImage.naturalHeight === 563 && lastImage.naturalWidth === 1000) {
    pages.pop();
}
```
