### ISSUE TITLE
[QueensManga] Connector not working

### ISSUE THREAD

**Issue by amrsabry** [manga-download/hakuneko#2617]
Please note that QueensManga bug reported here: https://github.com/manga-download/hakuneko/pull/2579
is not fixed yet and the pull request was closed!!!

**Comment by 27136773** [comment]
Just because a pull request is completed doesn't mean that the website will keep working for all eternity.
If there is a new problem, you have to wait for a new fix...

NOTE: Such a demanding attitude (at least it is received by me this way) will not help in attracting contributors to fix this faster, its more the opposite way around.

**Comment by manh21** [comment]
What version are you using? for 6.1.7 it takes about 1-2 weeks for the update being distributed

**Comment by Robonau** [comment]
this isn't entirely relevant but shouldn't QueensManga be madaranovel? since it has novels as well as manga
note: everything seems to work on the nightly (not novelse obv)

**Comment by manh21** [comment]
> this isn't entirely relevant but shouldn't QueensManga be madaranovel? since it has novels as well as manga
> note: everything seems to work on the nightly (not novels obv)

Currently `WordPressMadaraNovel`  override `_getPages` function, therefore it should be separated from the current connector `QueensManga`.

**Comment by Sheepux** [comment]
If you're not using the nightly you don't have the fix that was merged.
6.1.7 stable will receive the fix later (previous patch was 9 days ago)

**Comment by 27136773** [comment]
It was stated that the fix was applied and correctly works
