### ISSUE TITLE
[AnimePahe] Connector not working

### ISSUE THREAD

**Issue by newaccforhc** [manga-download/hakuneko#2649]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Not able to download (tested by Ever4engel)

**To Reproduce**
1. Animepahe
2. All (if connector update is working)
3. All (if manga update is working)
4. Sorry but, I haven't tested it on HakuNeko (tested by Ever4Engel)

**Screenshots**
See above :/

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Extra Info**
AnimePahe changed their api recently. Now they are serving fake kwik links in their api response.
Now, you need to go through kwik adfly or kwik shst links to get real kwik links.
(It'll be good if someone finds a way to get real links without those adfly shst links tho)
~~Also, a good news: they removed captcha for download links.. So, HakuNeko can shift to download links rather than downloading through stream links (for faster and stable downloads)~~

Maybe these tools will help:
https://github.com/Sainan/Universal-Bypass

https://github.com/adsbypasser/adsbypasser

**Comment by Robonau** [comment]
can confirm not working
download links still captcha me tho

**Comment by newaccforhc** [comment]
Yeah.. they added captcha again I guess..

**Comment by Ever4engel** [comment]
even the preview don't work

Error in the console F12

**Comment by 27136773** [comment]
Preview is not expected to work, because the embedded video player does not support `referer` spoofing.
Downloads do not work, because they need to be throttled (same issue as downloading from 9anime).
HakuNeko has no support yet for throttling the download of video segments.

Downloading of short episodes such as [Miss Monochrome The Animation](https://animepahe.com/anime/5bd7aa98-35a5-f449-1027-403a2caa0ff4) works fine.

**Comment by newaccforhc** [comment]
Oh.. didn't know that.
