### ISSUE TITLE
[Site Request] Jumpbookstore

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#2652]
**Name of the website**
Jumpbookstore

**Website urls (examples below)**
- Site: https://jumpbookstore.com
- Manga List: https://jumpbookstore.com/    for top sells (mangas and magazines) 
https://jumpbookstore.com/ext/jc.html  (Jump mangas)
https://jumpbookstore.com/ext/yjc.html  (YoungJump mangas)
https://jumpbookstore.com/ext/novel.html  (Novel part of the website)
- Manga example: https://jumpbookstore.com/item_list.html?keyword=%E9%80%B1%E5%88%8A%E5%B0%91%E5%B9%B4%E3%82%B8%E3%83%A3%E3%83%B3%E3%83%97+2020
- Chapter online viewer example: https://jumpbookstore.com/client_info/SHUEISHA/html/player/viewer.html?tw=2&lin=1&cid=SHSA_JP01WJ2020046D01_57

**Languages**
Japanese

**Website relationship**
One of the personal websites of Shueisha

**Additional details**
This website uses the pubplus tamplate

**Comment by Ever4engel** [comment]
this tool seem to do it tho 
https://github.com/h-ishioka/jumpbookstore

**Comment by 27136773** [comment]
Looks to me like there are many mangas that only provides a preview or don't provide any content at all instead of the full number of pages, it is hard for me to distinguish between them from the manga list. Furthermore there are various filter options for the lists, but none of them seems to provide only mangas with full content...

- All https://jumpbookstore.com/item_list.html?request=max_row&sort_order=4&item_list_mode=1&SEARCH_MAX_ROW_LIST=100
- Top (New) https://jumpbookstore.com/item_list.html?request=max_row&ACCESS_FREE_ITEM12=New&sort_order=4&item_list_mode=1&SEARCH_MAX_ROW_LIST=100
- Top (Ranking) https://jumpbookstore.com/item_list.html?request=max_row&ACCESS_FREE_ITEM12=Ranking&sort_order=4&item_list_mode=1&SEARCH_MAX_ROW_LIST=100
- Boy https://jumpbookstore.com/item_list.html?request=max_row&acs_section=newb&sort_order=4&item_list_mode=1&SEARCH_MAX_ROW_LIST=100
- Seinen https://jumpbookstore.com/item_list.html?request=max_row&acs_section=newy&sort_order=4&item_list_mode=1&SEARCH_MAX_ROW_LIST=100
- Love/Adult https://jumpbookstore.com/item_list.html?request=change_order&acs_section=adultnew&sort_order=4&item_list_mode=1&SEARCH_MAX_ROW_LIST=100

**Comment by Ever4engel** [comment]
this website don't provide any free content. all mangas and magazines there are paid 
i could provide a paid content (premium account)

**Comment by 27136773** [comment]
I have it up and running accessing images without any account barrier so far
For [this random example](https://jumpbookstore.com/client_info/SHUEISHA/html/player/viewer.html?tw=2&lin=1&cid=SHSA_ST01O00048400101_57) there are `12 pages` accessible through the website, but HakuNeko shows `58 pages`, so i'm confused if this is the full number of pages or if there are still some missing...

![image](https://user-images.githubusercontent.com/27136773/99904107-283bfa00-2cc9-11eb-8d0b-cd4ee91a5e09.png)

**Comment by Ever4engel** [comment]
Thanks a lot for you hard work !
