### ISSUE TITLE
[Webtoons.com] Connector not working

### ISSUE THREAD

**Issue by blaxcky** [manga-download/hakuneko#2681]
Insert through clipboard doesn't work, list remains empty.
I have tested it with a few different webtoons.

**Comment by Robonau** [comment]
works fine for me, you do have to do [manual website interaction](https://hakuneko.download/docs/manual-website-interaction/) to get through the age verification tho.
![](https://i.imgur.com/5EeXpnC.png)

**Comment by 27136773** [comment]
You have to provide website / manga / chapter, maybe direct links
Otherwise it is not possible to reproduce

**Comment by Robonau** [comment]
i mean he said `[Webtoons.com]` in the title 
and that multiple webtoons were broken (i assumed all)
hence my suggestion of 'manual website interaction to get through the age verification' since its not something i remember having to do in the past

**Comment by 27136773** [comment]
It was stated multiple times that it is required to have at least one manga + chapter for reproduction to ensure the ticket creator and developer are talking about the exact same thing. Even if it is the same issue for all mangas/chapter, it is essential to provide a specific example.

Why?
1. User says all mangas/chapters for website XYZ are not working.
2. Developer picks manga AAA and chapter 001, discovers an age gate issue and fixes it.
3. User verifies the fix with manga BBB chapter 017 => surprise, the problem is not solved, because the age gate was a completely different issue than the one the user experienced.

Just provide a sample manga and chapter, its done in seconds but may save hours

----
Websites for `webtoons.com`

![image](https://user-images.githubusercontent.com/27136773/100515546-44361480-317d-11eb-9e3b-b7802d2e7d6e.png)

**Comment by Robonau** [comment]
fair enough

**Comment by 27136773** [comment]
No further response, seems the manual age verification trick worked... => closed
