### ISSUE TITLE
[SkyManga] removal request

### ISSUE THREAD

**Issue by saad430** [manga-download/hakuneko#2797]
i wanna my website be removed from hakuneko 
this is my website : https://skymanga.co/
hope we get respond asap thank you.

**Comment by 27136773** [comment]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

Why should this website be removed from HakuNeko?

#### In case of Traffic
1. How much traffic is caused by HakuNeko?
2. How much is it compared to overall traffic (percentage)?
3. How did you measure those analytics (framework)?
4. How exactly did you distinguish traffic caused by HakuNeko from those caused by other scraper-bots?
5. Are you already using a proper configured CDN to reduce bandwdith and prevent scraper-bots (e.g. CloudFlare's free plan with IAUM)?

#### In case of content protection
1. Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?
2. Have you also requested takedown on other tools such as Tachiyomi or FMD2?

#### In case of Monetization
1. Are you using Donations?
2. Are you using Advertisements?

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by saad430** [comment]
the website should be removed from hakuneko due the monetization your logiciel make me lose alot i spent everyday +30 dollars to post my contents and i don't get the half for it and my website has been removed from tachiyomi 03 days ago

**Comment by Sheepux** [comment]
Are you aware that your website is working fine with an adblock leading to the same result ?
HakuNeko is basically a stripped website browser with embeded ads removal. Tried without an adblock, it's an intrusive popup nightmare.
Also so far i'm not able to find the download button to read it offline.

**Comment by saad430** [comment]
bro if i don't put ads how i can get the money i lost for the raws i post(+30dollars per day ) i'm the only web who extract this raws and apps like hakuneko/tachiyomi and others make me lose alot and in the end close the website and for download chaps they have alot of free extensions in chrome or mozila who can do it so please bro accept my request and remove it thank you

**Comment by Sheepux** [comment]
Conditions I and II aren't fullfilled : non user respectfull ads + monetizing intent (if that wasn't the case a simple download buton would be no problem, isn't it ?).

Voting request rejection -for now-.

**Comment by saad430** [comment]
who can add the download button?? i'm not programmer you're putting impossible conditions

**Comment by 27136773** [comment]
The website does not qualify for removal, even if a download button is added, because it will not met the AMP standards of advertisement anyway.

Since there seems to be no intend to make the advertisements less intrusive, it is a status quo in which the requirements won't be fulfilled => rejected

Feel free to open a new removal request, in case the circumstances have changed.

**Comment by Robonau** [comment]
note: the site has also aggregated some of its content from other sites, making it completely ineligible for removal

**Comment by saad430** [comment]
fuck off we will see if they gonna be in your fucking app or not you didn't take my permission in the first place to add it or not and now my request rejected

**Comment by Sheepux** [comment]
welcome to the open internet. Did you also ask for the copyright holder for their permission ?

**Comment by 27136773** [comment]
Did `Google Chrome` or `Mozilla Firefox` ask for your permission to access your website?
Maybe you should request them to block your website as well, to ensure nobody will `steal` your hard work...

For someone who didn't even know how to add a download button, i'm curious about the upcoming protection against HakuNeko 😊

**Comment by 27136773** [comment]
**Fun Fact:**
There was not even a ticket for SkyManga, so probably no HakuNeko user is even downloading from this website.
Enjoy wasting your time to force zero users from HakuNeko to visit your intrusive ad minefield 🤣

References: #2224

**Comment by AriaMoradi** [comment]
Tachiyomi contributor here, skymanga had been removed due to the owner's request, but we added it back after a change of policy around removal requests.

**Quote:**
*We have changed our policies regarding removing extensions. Now we will only comply with source removal requests from scanlator sources. Previously removed extensions may or may not be back, nor is there any guarantee they work.*
