### ISSUE TITLE
[Wecomic] Connector not working

### ISSUE THREAD

**Issue by samanta-widjaja** [manga-download/hakuneko#2873]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Old chapter is fine and working such as chapter 1-73, but new chapter showing error unexpected end of json input 74-latest. This happen not only in one comic but actually couple of them such A's "Senior brother, please act according to script" and "Back in time: fox King's sole affection"

**To Reproduce**
1. Webcomic
2. Senior brother, please act according to script
3. Chapter 74 - 81
4. Syntax error: unexpected end of json input

**Screenshots**
If complex to describe, add screenshots to help
[
**HakuNeko (please complete the following information):**
 - Version  6.17

**Comment by Robonau** [comment]
these are premium chapters (require payment), the devs not having access to these chapters mean we are not likely to be able to fix it

**Comment by samanta-widjaja** [comment]
I already paid and login. It usually work. They change how they display it. Before the only show the image. In the new display they wrap it in a lot of div. But thats when i inspect it in browser.

**Comment by samanta-widjaja** [comment]
Nb. It happened to all, not just this title

**Comment by samanta-widjaja** [comment]
I upload the json for the chapter that error. Hope it can help. Thanks
[picture_list.zip](https://github.com/manga-download/hakuneko/files/5779316/picture_list.zip)

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
1. Purchased a chapter on the website
2. In HakuNeko logged in with my facebook account through manual website interaction
3. Copy & Pasted manga URL from browser
4. Clicked chapter preview of purchased chapter

The provided JSON file has an empty data field, which means the chapter is not accessible, probably because login was not successful for some reason

![image](https://user-images.githubusercontent.com/27136773/104033912-78671100-51d0-11eb-87ae-3fd7bfc8c99f.png)

**Comment by samanta-widjaja** [comment]
In mangatoon, this login error is also happening. I already login and unlock chapter, but it said in preview unlock

**Comment by 27136773** [comment]
Issue cannot be reproduced and there was no further response
=> Closed
