### ISSUE TITLE
[Furio Scans] Downloading Unexpected Format

### ISSUE THREAD

**Issue by Slowftw** [manga-download/hakuneko#2891]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
On the website it returns all pages in .jpeg/.jpg/.png
But when downloading/viewing from hakuneko, it returns in .webp

**Screenshots**
<a href="https://i2.wp.com/furioscans.com/wp-content/uploads/WP-manga/data/manga_5de68e4f25e01/8c9a163e660a0e594401339779a0202f/00.jpg?ssl=1"><img alt="request" src="https://user-images.githubusercontent.com/46169656/104106380-1243c200-5294-11eb-9f46-80bc68006ab8.png"></a>
![payload](https://user-images.githubusercontent.com/46169656/104106466-cfceb500-5294-11eb-804b-0e294d5ecda4.png)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by 27136773** [comment]
Check your first screenshot and look at the bottom to image type
It is mime type `image/webp`, because i2.wp.com is a proxy that optimizes the source image.
So HakuNeko did everything correct.

However, the i2.wp.com proxy should be bypassed and the uncompressed jpeg from furioscans.com should be downloaded directly instead.
