### ISSUE TITLE
[hiperdex] Connector not working

### ISSUE THREAD

**Issue by ExoAnime** [manga-download/hakuneko#2930]
Site; hiperdex.com
Manga Link; https://hiperdex.com/manga/bokutoku-nyuuin-seikatsu/
Manga; Bokutoku! Nyuuin Seikatsu

Problems; Fake file downloads.

I've attached a sample picture. The files he downloads are all like that.

![image](https://user-images.githubusercontent.com/30474170/104607553-ff652f00-5691-11eb-97e2-61c70944b7f9.png)

**Comment by Robonau** [comment]
same problem as #2929
imgur (this manga is hosted on imgur fsr) does not allow no JS

![](https://i.imgur.com/s6pe2Ot.png)

**Comment by 27136773** [comment]
This happens when the web server provides the wrong HTTP content type header (e.g. `application/octet-stream` instead of `image/jpeg`).
Maybe this becomes more common right now to do this intentionally to protect images...
HakuNeko already has a mechanism to detect images by their content signature instead of the (faked) mime type of the server, but it is only applied to website whioch do so.
Maybe we should always perform a signature based approach to detect file type and stop using the mime type from the server?

**Comment by 27136773** [comment]
The default [HTTP accept header was changed](https://github.com/manga-download/hakuneko/commit/2df11c8b6ea933b7ebfa121d8e82e524bf6bcf24#diff-88c2c925a0d5fa6b8d9b267fe6225ce1298cd58b416f70ca439203934bf6e630L38) to access MangaKu.
Unfortunately, imgur does not like the new header and redirects to a HTML file when accessing the image.

**Comment by 27136773** [comment]
Also affected by CloudFlare problem #2933 => #2989

**Comment by 27136773** [comment]
CloudFlare issue handled by #3042
