### ISSUE TITLE
[too many] Connector not working

### ISSUE THREAD

**Issue by tuxlife32** [manga-download/hakuneko#2982]
why there are too many connectors error? why it's taking too long, **you guys fckin stupid**, 
i want to use hakuneko, so fix all these errors.
remember: your user is a king, so you need to fix all these errors for me

**Comment by Robonau** [comment]
1. there are currently a lot of errors because or a cloudflare update causing issues with the version of electrum hakuneko uses 
2. hakuneko is never going to be error free
3. the notion of "the customer is always right": 
      1. does not apply here, you aren't a customer
      2. speak to anyone in customer service and they will tell you that the customer is almost always wrong
4. as it is January the two main devs are strapped for time and thus do not have much time to spend on hakuneko
it's an open source program the users are the devs, by all means fix the program yourself

**Comment by Robonau** [comment]
i would suggest you find a connector that works currently, the ones we suggest you use are all functioning

**Comment by Sheepux** [comment]
being rude will not get issues solved.
This program is open source, it's you're smarter than the contributors doing this on their free, then fix it by yourself.

**Comment by ronny1982** [comment]
@tuxlife32 Learn the difference between `user` of an open source software and `CUSTOMER` of a purchased product...

And if you still don't get it, why not hire a software company to make a manga downloader for you?
But be prepared to pay around 250000 USD, because this is the amount worth of time that the contributers put into HakuNeko in their free time up to now... oh and don't forget the extra bills everytime a fix needs to be added because a website changed

Have a nice day!
