### ISSUE TITLE
[Site Request] nyaa.si

### ISSUE THREAD

**Issue by Robonau** [manga-download/hakuneko#3049]
**Name of the website**
nyaa.si

**Website urls (examples below)**
- Site: https://nyaa.si/
- Manga List: special exception*
- Manga example: special exception*
- Chapter online viewer example: special exception*

**Languages**
allot (mostly jp and english tho)

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
*its an anime torrent site so it would have to be implemented a bit different from the regular sites
though pretty much all the info can be gotten from the rss feed https://nyaa.si/?page=rss
(rss feeds can be navigated like dom with queryselector etc)
custom rss filters would be something to add to the config for the connector https://nyaa.si/?page=rss&c=1_2&f=0 is english only (can be easily obtained from the site so can leave this up to the user)
or perhaps have multiple (csv or something) and display each as a manga and the results as a chapter
have to disable preview somehow (since it wont do anything)

**Comment by 27136773** [comment]
I vote for reject, as it is already very easy to download directly from nya and torrent software also support RSS subscriptions

**Comment by Maxwell12347842** [comment]
**my opinion:** it's not a good idea to add a torrent site to the project. i would also vote for reject if i could.

**why?**
**1)** it's already really easy to use this site without a software.. so there is not rly a need for it

**2)** torrent isn't really safe, so there is a chance a lot of users would use the connector without knowing what they do or what torrent is & get screwed by the law

**3)** it adds un-neccessary bloat to the code and software because you would need to implement the torrent protocol etc. into it.. just for one site

i also don't see how you would benefit from such a implementation. this site has already a good search function, and it's literaly 2-3 clicks that will open automatic your torrent software and you will be able to download. i don't really see why you would need such a implementation. it's way easier the way it is without any additional software.

**Comment by Robonau** [comment]
> **my opinion:** it's not a good idea to add a torrent site to the project. i would also vote for reject if i could.
> 
> **why?**
> **1)** it's already really easy to use this site without a software.. so there is not rly a need for it
> 
> **2)** torrent isn't really safe, so there is a chance a lot of users would use the connector without knowing what they do or what torrent is & get screwed by the law
> 
> **3)** it adds un-neccessary bloat to the code and software because you would need to implement the torrent protocol etc. into it.. just for one site
> 
> i also don't see how you would benefit from such a implementation. this site has already a good search function, and it's literaly 2-3 clicks that will open automatic your torrent software and you will be able to download. i don't really see why you would need such a implementation. it's way easier the way it is without any additional software.

1. fair
2. torrenting is just as safe as accessing sites hosting illegal copies 
3. my plan was to just make it open in a torrent client

4. i gave up on this like an hour after making this post, just forgot to close it
