### ISSUE TITLE
[MangaWOW] Removal

### ISSUE THREAD

**Issue by coderbromanga** [manga-download/hakuneko#3124]

**Comment by 27136773** [comment]
> **Site url : mangawow.net**
> 
> Why should this website be removed from HakuNeko?
> reply: 1. By using hakuneko, some sites are digging money thanks to their mangawow content to block them.
> reply: 2. to prevent unauthorized publishing of content
> reply: 3. I reached about 23TB/ bandwidth per month
> reply: 4.the problem is not site speed. copying their content to get along with us. They have hidden all site information and their identities. Even sites without discord servers focus only on stealing content.
> 
> In case of Traffic
> How much traffic is caused by HakuNeko?
> reply: I do not know the traffic of hakunekon on my site, if there is a method of dying, please show it.
> 
> How much is it compared to overall traffic (percentage)?
> reply: I think it has a 15% traffic share
> 
> How did you measure those analytics (framework)?
> reply: As I said, I do not know how to measure Hakuneko traffic, I said approximately (estimated)
> 
> How exactly did you distinguish traffic caused by HakuNeko from those caused by other scraper-bots?
> reply: I talked to other digging robots and asked them to remove it.
> 
> Are you already using a proper configured CDN to reduce bandwdith and prevent scraper-bots (e.g. CloudFlare's free plan with IAUM)?
> reply: I do not use the cdn system and I do not plan to use it, as my country does not have many manga readers, I do not need to pay attention to extra traffic, just hakuneko causes additional traffic
> 
> In case of content protection
> Are you aware that scraper-bots will still access the website even if the website is removed from HakuNeko?
> reply: Yes, I am aware, so I remove the printers that are accessed with my site one by one, The more I remove it, the better for me, the important thing is not the traffic, but the copying of the content for me, they delete the covers and publish them as if they did it themselves.
> 
> Have you also requested takedown on other tools such as Tachiyomi or FMD2?
> reply: I requested Tachiyomi removal and it was removed.
> reply: FMD2 also never happened but I'll check again.
> 
> In case of Monetization
> Are you using Donations?
> reply: yes I have a donation place but it doesn't help much.
> Are you using Advertisements?
> reply: yes

Website Link: https://mangawow.net
Related: #443

**Comment by 27136773** [comment]
**What i understand:**
Bandwidth caused by HakuNeko is not a concern for the website owner.
Monetization through bypassing the ads is not a concern for the website owner.

Downloading and re-publishing the images without the cover page is the main concern of the website owner.

----

**My opinion:**
Removing the website from HakuNeko will not change anything in regard to the main concern of the website owner. If content is scraped from this website and re-published, then it is very likely not done with HakuNeko since this would involve way to much manual work.

Also [some images](https://mangawow.net/manga/king-of-apocalypse/bolum-216/) have watermark from [other websites](https://mangagecesi.com), which contradicts the statement the translation was done by MangaWOW

**Comment by coderbromanga** [comment]
.

**Comment by 27136773** [comment]
> It would still lower my worries, even if there was a moment. If someone is to copy my content, at least try to download all episodes with 1 button, it will push them more. I'm trying to stop the download as much as I can. I ask you not to stay behind my eyes for hakuneko I would appreciate it if you could help thank you.
> 
> watermark previously allowed mangawow to broadcast episodes of manga on magnet night and they also allowed me to publish their own episodes, he becomes my friend.

Get a free tier of CoudFlare and enable `I'm Under Attack Mode`and Captcha, this will prevent most scrapers...
No need to remove MangaWOW from HakuNeko

**Comment by coderbromanga** [comment]
.

**Comment by coderbromanga** [comment]
.

**Comment by coderbromanga** [comment]
.

**Comment by 27136773** [comment]
Using intrusive popup ads and talking about CloudFlare will reduce usability is contradicting...

![image](https://user-images.githubusercontent.com/27136773/109283510-29784800-781f-11eb-89ef-3072e3b318df.png)

**Comment by coderbromanga** [comment]
.

**Comment by coderbromanga** [comment]
.

**Comment by Ever4engel** [comment]
> ![image](https://user-images.githubusercontent.com/79687576/109283991-6ef14100-7830-11eb-83e2-c0b134b2c43b.png)
> I set my ad setting to min impressions I need to turn it on I have an average daily earning of 1.3 $ for a while
> and I can't block ad-blocking programs ...
> Don't worry I'll remove that type of ad soon

> my priority is to prevent those who steal episodes with hakuneko .
> if that ad is the reason you didn't remove hakuneko, I'll remove it right away..

are you not the same person who came here months ago to request us to support it ?
i'm sure it where you. you scarped from other websites as you wish from other websites to build your wessite.
and 

`watermark previously allowed mangawow to broadcast episodes of manga on magnet night and they also allowed me to publish their own episodes, he becomes my friend.`

give us a proof, a screen, or a dm with that person approval (i know you will do a fake one)

15% of usage bandwidth is not really admissible from what you say it ? your intuition ? anyway.

i know for sure that you know what to do exactly to really request a removal from hakuneko.
do them all first. (especially about intrusive ads)

Ronny gave to you a good tip to stop most of the scrapers, for now just active your cloudflare protection.

**Comment by coderbromanga** [comment]
.

**Comment by coderbromanga** [comment]
.

**Comment by Sheepux** [comment]
> https://mangagecesi.com/hakuneko/
> https://hayalistic.com/hakuneko/
> https://mangawow.net/hakuneko/
> 
> @Ever4engel will these be enough

> the problem is not traffic here ... copying their content by others
> verification is not enough
> I added These articles
> if it's not enough discord contact me
> Ercan#9248

User requested via discord more than 30 connectors for his personal needs. (thank you discord history) 
Too much contradictions, seems  suspissions to me.
User also claimed that he is using hakuneko to get his raws. Contradiction with the purpose.

**Comment by 27136773** [comment]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions than a removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

QUESTIONS ALREADY ANSWERED, SEE ABOVE

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by 27136773** [comment]
Rules are quite clear:
- Remove ads to meet AMP standard.
- Provide download link for each chapter.

You can setup download links with scrape protection by using file hosting services with speed limit, captcha, ...

**Comment by Robonau** [comment]
imm just call this request out as ridiculous.
This man uses HN to get manga to *translate 
has requested turkish manga sites be added to HN in the past.
but doesnt want ppl to be able to download his *translations using the same tool he uses

as someone that recently had to redownload there entire manga library i know HN is not the ideal tool for scraping large amounts of manga from one source (bookmarks in my case) 

for another website to scrape off of this site using HN they would have to run another scraper (that they would have to write themselves) to grab the metadata (genres, description, cover etc), this is not ideal and would likely break at some point, ppl scraping from sites will be writing their own scrapers from scratch.

*(idk if the site is aggregating or translating, idk turkish so i can't confirm)

**Comment by coderbromanga** [comment]
.

**Comment by coderbromanga** [comment]
.

**Comment by Sheepux** [comment]
> > Kurallar oldukça açık:
> > 
> > * AMP standardını karşılamak için reklamları kaldırın.
> > * Her bölüm için indirme bağlantısı sağlayın.
> > 
> > Hız sınırı, captcha, ... ile dosya barındırma hizmetlerini kullanarak kazıma korumalı indirme bağlantılarını kurabilirsiniz ...
> 
> I won't add a download link I say they steal my content to turn off the download feature I want to remove hakunekodan you say add a download link
> for convenience to the person who plays my content, I will prepare a special download link to him.

> I say they steal my content with Hakuneko
> You say add download link, it will play easier :)
> please think carefully

Browsed to the page with chrome, "save page as". got the images in a folder in 3s.
Internet is "open" by default. Bascially: add a paywall if you want to prevent such situation.

**Comment by 27136773** [comment]
Just curious...

1. Which websites are stealing content?
2. Have you asked them to stop stealing or at least keep the cover page?
3. If you don't care about monetization, why do you even care about other websites hosting your content are making money? They even save you bandwidth for hosting the images.
4. Why not publishing directly on the websites that are "stealing" your content right now and shutting down your own website? This would be a win-win for all...

**Comment by coderbromanga** [comment]
.

**Comment by coderbromanga** [comment]
.

**Comment by coderbromanga** [comment]
.

**Comment by 27136773** [comment]
> > el ihtiyaçları için discord üzerinden 30'dan fazla bağlayıcı talep etti. (Teşekkürler uyuşmazlık geçmişi
> 
> Ever4engel said the same, I wrote the necessary explanation to him on discord. If you write to me, I will explain to you + with the evidence ...
> Can you open a fake account and have them made?
> I request the site to be removed they are stealing the contents ....
> 
> https://mangasehri.com/
> https://cizgiromanarsivi.com/
> https://www.mangazure.com/

> 1. https://mangasehri.com/  https://cizgiromanarsivi.com/ https://www.mangazure.com/ There was one more.
> 2. they do not chat in any way ... they do not accept.
>    3.They use google ads, how they do not earn, even the child understands.  bandwidth is not an issue for me.
>    4.hakuneko, why don't you do it on me so that your precious time doesn't run out ( the same thing you said to me )

> guys just play Turkish squads using hakunekoyu I say you say give to the man and take from them other squads steal from others.....

Other websites indeed scraping the content
e.g. Chapters on [mangagecesi](https://mangagecesi.com/manga/arcane-sniper/bolum-22/)
![image](https://user-images.githubusercontent.com/27136773/109308509-686bc500-7842-11eb-80c4-85b7025d46bb.png)
are uploaded to [mangazure](https://www.mangazure.com/2021/02/arcane-sniper-bolum-22.html)
![image](https://user-images.githubusercontent.com/27136773/109308583-80434900-7842-11eb-9cc3-a9d151c7405a.png)

However, i doubt that this is done with HakuNeko, because new chapters appears quite fast (~5 minutes) on the aggregator website. I don't thing they have a full-time 24/7 employee that is monitoring the mentioned websites and then uses HakuNeko to download, add all meta information and re-upload the chapters to the aggregator, this would be absolutely inefficient.

This is very likely done automatically with customized scripts.

Besides, just fulfill the requirements [posted above](https://github.com/manga-download/hakuneko/issues/3124#issuecomment-786601259) for your website and when its done chances for removal are much higher.

**Comment by coderbromanga** [comment]
.

**Comment by Slowftw** [comment]
I think it would be helpful to pin a separate Issue clarifying the removal rules

**Comment by 27136773** [comment]
Off Topic:
I proposed a ticket template for such requests right now #3129

**Comment by Robonau** [comment]
so this conversation finalised as.
he wants his site removed but is unwilling to conform to the rules about removals.
so will not be removed.
might as well close this issue.

**Comment by 27136773** [comment]
Rejected based on the discord discussion (not willing to comply with removal requirements).

**Comment by 27136773** [comment]
Images on the aggregator websites were not stolen with HakuNeko, the images have completely different file name scheme and image strips were split into chunks of equal height which is not something HakuNeko can do.
