### ISSUE TITLE
Download all missing button [Feature]

### ISSUE THREAD

**Issue by rickevans86** [manga-download/hakuneko#3145]
Is it possible to have a download all missing chapters from bookmarked series button on the program, and have a command that could be run to do this.

**Comment by 27136773** [comment]
Why not using the download all button?

**Comment by rickevans86** [comment]
Hi
The only download button I have seen is for individual series not all in your bookmark list from one button

**Comment by 27136773** [comment]
See [docs](https://hakuneko.download/docs/interface/#chapter-list), button number 2

**Comment by rickevans86** [comment]
With that button you have to go into each series and click download, I was suggesting a button that will download all chapters from all series without going into the series and clicking download. Eg I have 10 series in my bookmark list, I click download all and it downloads all the missing chapters from all 10 series from one button press

**Comment by Sheepux** [comment]
So the use case is:

As a daily offline reader, 
i want all my bookmarks to be automatically downloaded on a simple click
so that all missing chapters get retrieved.

Detected cases:
-  Someone would probably want to mark only certains bookmarks
- needs a log history so that you can find what was retrieved.
- would probably be covered with new chapter detection/notification (will not cover "missing" chapters) but this feature will never automatically download.

Somehow contradicts the HN phylosophy https://hakuneko.download/

> The philosophy is ad-hoc consumption, get it when you want to read/watch it. It is not meant to be a mass downloader to stock up thousands of chapters that are just collected and will probably never be read.
