### ISSUE TITLE
[Comico] Connector not working

### ISSUE THREAD

**Issue by perrinaz** [manga-download/hakuneko#3180]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
A comic is not appearing in the "Manga List"

**To Reproduce**
1. Name of Connector: Comico (not Comico Novels)
2. Name of Manga: Hな姉とニートなボクと
3. Name of chapter: N/A as the manga doesn't appear in the list of manga 
4. No error messages appear in F12. The manga *is* visible/readable when viewed in HakuNeko's manual browser window.

**HakuNeko (please complete the following information):**
 - Version: Nightly build

**Comment by 27136773** [comment]
Referenced comic seems not to be in any of the list that HakuNeko fetches.

Use copy & paste, but be aware that the comic is cross referenced to `plus.comico.jp`. HakuNeko does not explicitly support `plus.comico.jp`.
Therefore you need to get the original link from `www.comico.jp` which is https://www.comico.jp/articleList.nhn?titleNo=24478 instead of https://plus.comico.jp/manga/24478/

**Comment by perrinaz** [comment]
So this should be a changed to a  request to support plus.comico.jp or should I open a new ticket for that?

**Comment by 27136773** [comment]
Either changing this or make a new one doesn't really matter.

For development it is open to discuss if it makes sense to make a new one or improve implicit support for `plus.comico.jp` inside of `www.comico.jp`

**Comment by MikeZeDev** [comment]
there is no "plus" comico anymore?
