### ISSUE TITLE
Add a notification box for apdates

### ISSUE THREAD

**Issue by Ever4engel** [manga-download/hakuneko#324]
Add an ability to haku to see a notification box when he's apdated like haku 0.4.0

**Comment by 27136773** [comment]
I intentionally removed this popup because i thought this would be annoying for users.
Would be nice to get feedback from other users as well if an automatic update notification shall be shown, not shown or even add a setting for this (not sure if a setting should really be introduced for such trivial thing).

**Comment by Ever4engel** [comment]
ya i see it's just to see when Haku get updated ^^
maybe in the future you could add an option for that. if non ther is no problem ^^

**Comment by jrdp18** [comment]
I like having a notification. In a different program I use, they have a notice in a corner and when the user clicks it, it will show the update pop-up.

**Comment by 27136773** [comment]
This looks interesting:
https://electronjs.org/docs/tutorial/notifications

**Comment by 27136773** [comment]
Spend hours trying to get Notifications get to work on Windows 10 without success.
Giving up on system integrated notifications...

**Comment by 27136773** [comment]
A notification based approach seems to be the best approach to inform the user non-intrusive that an automatic update has been made.
Will re-evaluate possible solutions for this due to milestone 6.x

**Comment by Sheepux** [comment]
Today's discord discussion:
Notifications from electron only work if you have the app installed.
https://github.com/electron-userland/electron-builder/issues/4054
Currently not working for portable

**Comment by 27136773** [comment]
Since a native platform based approach seems to be very hard to achieve, a web-based solution might be used when introducing a new UI framework.

Some major frameworks such as [Element](https://element.eleme.io/) already have built-in support for [notifications](https://element.eleme.io/#/en-US/component/notification).

**Comment by Ever4engel** [comment]
@ronny1982 should delete this, no ?

**Comment by 27136773** [comment]
There are no plans to add a new UI framework with support for notifications in this version of HakuNeko
