### ISSUE TITLE
[SCANTRAD.NET] Connector not working

### ISSUE THREAD

**Issue by Ben93160** [manga-download/hakuneko#3394]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
AFter website update (22/04), connector doesn't work anymore, can't list or update manga and it seems #3380 that download doesn't work either 

**To Reproduce**
1. Scantrad
2. Sakamoto Days
3. 20
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - 6.17@845bf9

**Comment by 27136773** [comment]
Seems website got a complete new design

**Comment by Zarh** [comment]
As I said here : https://github.com/manga-download/hakuneko/issues/3380
On the nightly version, update manga/chapter list works, (it was fixed by this pull request : https://github.com/manga-download/hakuneko/pull/3382 ) but we can't download chapter, it return error 403. You just have to add an header (referer) to the request when it download the pictures, and it will be fixed.

referer = "https://scantrad.net/"

**Comment by dodieboy** [comment]
Look like they change the website agian, just update the connector to fix the bug
