### ISSUE TITLE
[Question]  How to configure Proxy in HakuNeko settings ?

### ISSUE THREAD

**Issue by wafergithub** [manga-download/hakuneko#3409]
Hi, a noob here.
i tried to open a few connectors. unfortunately, it blocked. 
in https://hakuneko.download/docs/troubleshoot/ , i found that we can configure proxy in HakuNeko settings. unfortunately, i have no idea how it is works.
could someone kindly teach me please ?
thank you

**Comment by dodieboy** [comment]
Step 1:
![image](https://user-images.githubusercontent.com/9015764/116773110-0a4ba000-aa86-11eb-8c80-b89eda55cb0c.png)

Step 2:
![image](https://user-images.githubusercontent.com/9015764/116773107-03249200-aa86-11eb-85ec-83569ae032cb.png)

**Comment by 27136773** [comment]
Check the tooltip of these options...

**Comment by malicious** [comment]
Adding the tooltip details for completeness, since I had a little trouble getting them to show up just now:

    Set the proxy servers that shall be used.  
    Leave blank to ignore.
    
    Examples:
    
        http=proxy.web:80
        http=127.0.0.1:8080;https=127.0.0.1:8080;socks=127.0.0.1:8081
    
    More info: https://git.io/hakuneko-proxy

And the Proxy Authentication field:

    Set the username and password for the proxy server(s).  
    Use "." as separator between both terms.  
    Only basic auth is supported!
    
    Examples:
    
        username:password

(The proxy configuration format is just however Electron does it, <https://git.io/hakuneko-proxy> redirects to <https://github.com/electron/electron/blob/main/docs/api/session.md#sessetproxyconfig>, which has the same information.)
