### ISSUE TITLE
Only the most recent chapters load on connector

### ISSUE THREAD

**Issue by Zehra** [manga-download/hakuneko#3424]
Only the most recent chapters appear on the connector for NaniScans.

![nani](https://user-images.githubusercontent.com/22282963/116945618-20a05a00-ac46-11eb-9451-89c05e455232.png)

**Comment by 27136773** [comment]
Which chapters are missing?
Looks identical to me...

**Comment by Zehra** [comment]
Chapters 1-5 are missing.
![nani1](https://user-images.githubusercontent.com/22282963/116946511-49295380-ac48-11eb-84ae-81ef332af9f6.png)

**Comment by 27136773** [comment]
Need to implement support for chapter pagination.
Instead of chapter link, the paginated lists shall be used (iterate until list is empty):
https://naniscans.com/titles/08d7de86-7877-45ff-824d-168e404d6e2d
=>
https://naniscans.com/titles/08d7de86-7877-45ff-824d-168e404d6e2d/1
https://naniscans.com/titles/08d7de86-7877-45ff-824d-168e404d6e2d/2
https://naniscans.com/titles/08d7de86-7877-45ff-824d-168e404d6e2d/3
