### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by LunerRaies** [manga-download/hakuneko#3430]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
the manga count gose form 25348/25348 to 23701/23701 and back again. It is not keeping up with the site. there are no new storys

**To Reproduce**
MangaKatana
connector update is not working
manga update is working
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by LunerRaies** [comment]
have been at 25348/25348 for a will

**Comment by 27136773** [comment]
Cannot be reproduced on my end.
No signs in source code that would lead to such behavior.

It is probably the website itself that generates inconsistent data.
Since HakuNeko makes 1291 page requests (20 manga / page) to get the manga list it is likely that sometimes the server generated page does not contain the correct amount of mangas, or mangas from the wrong page (duplicates).

It could also be an isolated network issue on the target system.

**Comment by 27136773** [comment]
Use `Copy & Paste` as workaround for mangas that are missing in the list

**Comment by LunerRaies** [comment]
Sawaranaide Kotesashi-kun
Dungeons & Artifactscan't find these with Copy & Paste on Manga Katana they are on the wibsite
---------- Original Message ----------

**Comment by 27136773** [comment]
Copy & Paste works fine for me, make sure to read the docs to understand how it works...

![image](https://user-images.githubusercontent.com/27136773/118654077-777e6580-b7e8-11eb-8aaa-4450ed8dfceb.png)
