### ISSUE TITLE
[mangapark] Connector not working

### ISSUE THREAD

**Issue by kinglessy** [manga-download/hakuneko#3506]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]     
so the connector works again but manga park has a two versions v2 and v3 it shows the mangas and translation on v3 , but when i copy the manga url from v2 and paste on the clipboard it doesnt show and the chapters wont appear in the manga in my favourites p.s: it was a manga from v2 can you make both versions appear or at least fix the url issue in v2 and the issue to make it appear in the favourites,
![Screenshot (28)](https://user-images.githubusercontent.com/84690859/119602898-7357d680-bdec-11eb-8b89-10f3c79bc0cf.png)

the chapters appearing in the files is from another source/connector if the v2 were still working it would show different versions of translations like version fox,duck,rock
![Screenshot (29)](https://user-images.githubusercontent.com/84690859/119603040-b87c0880-bdec-11eb-970c-0960bc08d702.png)

![Screenshot (30)](https://user-images.githubusercontent.com/84690859/119634627-32bf8380-be13-11eb-8ffc-5520d8b523f3.png)

**Comment by 27136773** [comment]
Related: #3246

MangaPark is constantly changing their website right now.

It would not be smart to adapt HakuNeko every time MangaPark changes something, this will lead to more confusion with every user having different bookmarks with different manga IDs, which may cease to work in some month because MangaPark changes something again.
In this case HakuNeko users have to remove and re-add all their bookmarks again...

Sticking around with the website layout which is most probably being the most future proof is the best bet right now to make sure bookmarks will still work within the next few month.

**Comment by kinglessy** [comment]
Thanks for the explanation totally agreed with you ,If mangapark ever
settled with this layout I hope you add a connector for V2 (old site) like
other apps do cause of the big library it have, hakuneko by far is the best
app I ever tried keep the good work all love.
