### ISSUE TITLE
I can't view any pictures in mangago. It says that "cannot read property 'src' of null"[Bug]

### ISSUE THREAD

**Issue by alexanderoe69** [manga-download/hakuneko#3632]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context (please complete the following information):**
 - OS: [e.g. Windows10]
 - HakuNeko Version [e.g. 6.17]

**Additional context**

**Comment by 27136773** [comment]
Create a new ticket and fill the [Website not Working](https://github.com/manga-download/hakuneko/issues/new?assignees=&labels=Website+Change&template=1-connector-website-not-working.md&title=%5BNameOfConnector%5D+Connector+not+working) form completely and correctly.
This is a possible duplicate of #3604 which has already been fixed in nightly release
