### ISSUE TITLE
[NameOfConnector] Connector not working

### ISSUE THREAD

**Issue by msam900** [manga-download/hakuneko#3644]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The sites dont work when using the paste button and software stays the same as when opened. 

**To Reproduce**
1. Name of sites: 
- mangaowl.com
- 1stkissmanga.love
- manhuascan.com
2- for all the mangas and chapters it doesn't work

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17] - Linux and windows

**Comment by Sheepux** [comment]
Create 1 issue per site, also use proper title

i'd be interested to know how mangaowl could be not working as it's not even implemented ... see #2335
1stkissmanga is working fine here, without proper details (name of manga/chapter) nothing we can investigate.
manhuascan is not working because of the cloudflare issue. #2933

Closing (will reopen if proper details are given)
