### ISSUE TITLE
Chapter Title Format gives chapters four digits instead of three? (and other suggestions)

### ISSUE THREAD

**Issue by Darkmaster006** [manga-download/hakuneko#3648]
**Is your feature request related to a problem? Please describe.**
I was trying out the 'Chapter Title Format' feature (using MangaDex as a connector), and went with "%M% v%VOL% c%CH% %T%", however, what I get is "Futari Escape v000 c0014 - Locked out escape (en) [knight heron]". The 'issues' I find are that chapter number has four digits instead of the usual three (any way to configure this?), that there's a hyphen that wasn't in the format, and that there's '(en) [scangroup]' at the end, which also wasn't in the format.

**Describe the solution you'd like**
I would like to be able to configure how much digits both volume and chapter number have, as well as whether the presence of a hyphen is necessary or not. I'd also like to be able to configure whether language and scan group appear at the end. I would also like to know if it is possible to 'ignore' %VOL% when it is '0'.
EDIT: I'd also like to know if it is possible to change the format and have the change take place after hitting the check, 'cause as of right now I'm opening and closing Hakuneko every time I change it.

**Describe alternatives you've considered**
I have no idea if this is possible (I know the numbers are extracted from the original, so), but I think it'd be a nice feature to have and wanted to let it be known. Thanks for all the work.

**Context (please complete the following information):**
2021, HakuNeko rev. 6.1.7@f5e130

**Additional context**
![image](https://user-images.githubusercontent.com/21136515/123976111-4622b900-d994-11eb-95a0-351653aa8b6f.png)
![image](https://user-images.githubusercontent.com/21136515/123975694-ea583000-d993-11eb-836f-c0a335d4dc13.png)
Kinda related, is there any way to enlarge the sections? For example, the chapter section there so I can see the name in full without having to over over it.

**Comment by Sheepux** [comment]
There is  currently no way to do a conditional formating
The post formating is actually just some replace and the additionals zeros (padding) are fixed in the code
https://github.com/manga-download/hakuneko/blob/a0be12e35c5693f609250f18e77e43f70716f108/src/web/mjs/engine/Manga.mjs#L161

Getting it dynamic with conditional formating would be quite hard. I have no idea how we should prompt the user such option.

Regarding the second question : 
it was proposed here https://github.com/manga-download/hakuneko/pull/3139
but the contributor didn't finish the job. Probably something we'll handle with the next version : haruneko (i'll create an issue on the haruneko git)

**Comment by 27136773** [comment]
The title format right now is a hack, the correct solution would be to implement an extract method for each website which is a lot of work...
The 4 digits for chapters are hardcoded, because there are mangas with more then 1000 chapters, therefore 3 digits are insufficient.

**Comment by Darkmaster006** [comment]
Thank you for the answers. I'll be on the lookout, then.
