### ISSUE TITLE
Option to set default manga language

### ISSUE THREAD

**Issue by pickx** [manga-download/hakuneko#366]
For sites that support multiple languages, I have to choose it to filter the chapter list whenever I search for a new manga. 

It would be nice to have a language name, so that it is automatically chosen if it is available.

Thanks.

**Comment by 27136773** [comment]
Rejected for the following reasons:

- Keeping the language filter across multiple websites is not possible because each website may use a different identifier for languages
- Keeping the language filter when switching between mangas within the same website was once implemented but removed, it was confusing when the chapter list was empty (in fact it was not empty but there were no chapters matching the selected language)

**Comment by 27136773** [comment]
As a workaround you an enter the language in the search filter, the search filter will not reset
