### ISSUE TITLE
[morenovel] Connector not working

### ISSUE THREAD

**Issue by andillk** [manga-download/hakuneko#3726]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Timeout Of 60 Second

**To Reproduce**
1. morenovel
2. all novel/list

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/81703465/126062432-801ab73b-2ce7-45c3-90e1-ac24acac5c8e.png)

**HakuNeko (please complete the following information):**
 - Version 6.17 and 8.3.4

**Comment by 27136773** [comment]
This seems to be a bug in a 3rd party library that is injected to extract the novel.
The method [html2canvas()](https://github.com/manga-download/hakuneko/blob/cd4b9670009d776de555cfb842dfcae0eed4397e/src/web/mjs/connectors/templates/WordPressMadaraNovel.mjs#L45) is not returning...

html2canvas [v1.1.2](https://github.com/niklasvh/html2canvas/releases/tag/v1.1.2) is still working, [v1.1.3](https://github.com/niklasvh/html2canvas/releases/tag/v1.1.3) breaks the functionality, probably caused by any of the [change](https://github.com/niklasvh/html2canvas/compare/v1.1.2...v1.1.3) ...

**Comment by 27136773** [comment]
`html2canvas` now awaits until all images finished loading, therefore HakuNeko shall not block images when loading novel website
