### ISSUE TITLE
trwebtoon Connector not working

### ISSUE THREAD

**Issue by canlost** [manga-download/hakuneko#3751]
trwebtoon.com   
They changed the site theme "something special is not working hakuneko needs updating.

**Comment by Sheepux** [comment]
works fine here.

Please fill the issue template as requested when opening an issue.

**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by 27136773** [comment]
See: #3729
Use `nightly` or wait for merge into `6.1.7`
