### ISSUE TITLE
[Reset] Connector not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#4115]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

Titles shows no chapters. Oddly, update works and title show, but no chapters. No CloudFlare issues.

**To Reproduce**
1. Name of connector - reset
2. Name of manga (if connector update is working) - All
3. Name of chapter (if manga update is working) - All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - None.

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

<img width="568" alt="Screen Shot 2021-11-02 at 11 40 57 AM" src="https://user-images.githubusercontent.com/70929406/139925410-f8a5f1d6-a79c-423f-b17f-667f6545971f.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Tested any manga, cover pictures dont load in Webview at all. No error messages in console.

In a regular browser chapter liinks redirect to to bilibili.com anyway.

**Comment by tsentered** [comment]
“Reset Scans" is the name of the connector and it’s all in the proper places. I answered every step for creating a new issue. Further, the site does not forward to bilibili.com <http://bilibili.com/>.
Thanks.

**Comment by tsentered** [comment]
The bilibili that you see is simply the advertisement.

**Comment by MikeZeDev** [comment]
Sorry i corrected my comment after seeing my error about mentioning the website name. I am sorry about that.

However, i dont think its as simple as saying its "an ad".

Take that screen
https://i.imgur.com/v7pXrQd.png

First link is https://reset-scans.com/manga/the-scholarly-reincarnation-00/
Second link is https://reset-scans.com/manga/my-wife-is-daji/

Both look identical. Except for the bili tag ofc.

Chapters for the first are on reset-scans.com, while chapters for the seconds are on bibilicomics.

https://reset-scans.com/manga/the-scholarly-reincarnation-00/chapter-183/
https://www.bilibilicomics.com/mc153/24012 (removed utm cause its tracking)

You can say they are ads, but they dont seem like ads to be honest. I am mentionning them because it may be up to HN to handle them.. or not.

Now that you talk about ads, there is the webview problem : previously it couldnt load the cover picture, now its even worse : https://i.imgur.com/Bno2dPa.png : Adblocker message.

**Comment by tsentered** [comment]
What do you mean? The site is clearly on reset scans with bilibili ads.

**Comment by tsentered** [comment]
Bilibili has blown up and some sites do end up being forwarded bilibili, but none of the titles which I am looking at. I already check for those things.

**Comment by tsentered** [comment]
Thanks!
