### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by Efreak** [manga-download/hakuneko#412]
Please add ability to minimize the application to the system tray. I believe this should be relatively simple with electron apps. Should probably be optional/setting for those who don't want such.

**Comment by 27136773** [comment]
Yes it can be done at less costs, but the desktop client currently has no settings manager so it would be either minimize to tray or minimize to task bar.

Further investigation is required for this proposal.

**Comment by 27136773** [comment]
**Current solution:**

HakuNeko will show an additional tray icon.
By clicking on the tray icon it is possible to minimize the application to tray or restore the application from tray.

The general minimize and restore behavior stays untouched.

**Comment by 27136773** [comment]
Tray icon will be removed for the following reasons:

- Very different behavior on different platforms
- Drag and drop of manga links is not supported as originally expected
- Does not integrate well in macOS
- HakuNeko crashes on the linux CI agent because of some dbus issues caused by libappindicator
