### ISSUE TITLE
[Site Request] Novema.jp

### ISSUE THREAD

**Issue by junksubsid** [manga-download/hakuneko#4354]
**Name of the website**
Novema!

**Website urls**
- Site: https://novema.jp/comic-grast/
- Manga List: https://novema.jp/comic-grast/serial
- Manga example: https://novema.jp/comic-grast/serial/n1
- Chapter online viewer example: https://novema.jp/comic-grast/serial/n1/n1/1

**Languages**
Japanese

**Website relationship**

**Additional details**
This website has a viewer similiar to magazine pocket i guess

**Comment by sisco0** [comment]
The requested site https://novema.jp/comic-grast/serial/n1/n1/8 has a layout very similar to these others:
**SpeedBinb** https://booklive.jp/bviewer/s/?cid=60040575_001&rurl=https%3A%2F%2Fbooklive.jp%2F
**SpeedBinb** https://static.ichijinsha.co.jp/online/u/book/zerosum/himegimiha/91f685adf2a88831175e53fd1f95c874/index.html
What do you think? Should **SpeedBinb** be the right connector, or we are just guiding ourselves because of the reader type?
