### ISSUE TITLE
Easier Migration between sites for bookmarks

### ISSUE THREAD

**Issue by ShadowEaglz** [manga-download/hakuneko#445]
With the impending closure of mangarock I, and many other users will be required to change sources for everything mangarock related which leads to a tedious one by one search, so was wondering if it was possible to implement something to simplify this a bit.

For example right click on a bookmark and have its title inputted into search automatically, or better yet, allow users to set a preferred list of sites and have it bookmark the first positive result.

This may also benefit from using a source such as MAL to get alternative title names so that if we search the English name, results for the Japanese name will also show up and vice versa.

**Comment by 27136773** [comment]
Such a workflow will not be implemented because it is

- not related to a core functionality
- a rare and unique use case
- very complex in implementation and in usage
- very easy to create an external script that exactly does what you want

----

Someone may write a script to achieve what you want by doing the following steps:

1. Read the `hakuneko.bookmarks` json file
2. Read a maga list json file that should be used for replacement (e.g. `hakuneko.mangas.mangadex`)
3. Go through all MangaRock bookmarks
4. Search the bookmark title in the provided manga list
5. Update the bookmark regarding the search result from the manga list
6. Save the updated bookmarks to `hakuneko.bookmarks`

**Comment by PeterBurner** [comment]
Hi guys

I played a little with the development console and created a script that will add for every MangaRock bookmark you have an additional MangaDex bookmark if the title matches exactly on both sides.

Instructions:
1. go to MangaDex connector to populate cache (you might want to hit the synchronize button)
2. open development console (F12 on Windows)
3. paste the following code and press Enter:
```
const deleteOldBookmarks = false;
const rock = HakuNeko.BookmarkManager.bookmarks.filter((bookmark) => bookmark.key.connector === 'mangarock');
const dex = HakuNeko.Connectors.find((connector) => connector instanceof MangaDex).mangaCache;

rock.forEach((oldBookmark) => {
    const newBookmark = dex.find((manga) => manga.title.toLowerCase() === oldBookmark.title.manga.toLowerCase());
    if (newBookmark) {
        HakuNeko.BookmarkManager.addBookmark(newBookmark);
        if (deleteOldBookmarks) {
            HakuNeko.BookmarkManager.deleteBookmark(oldBookmark);
        }
    }
});
```
As I said, this only works if the manga titles match exactly (not case-sensitive).
In additon it wont copy your chapter marks since MangaDex supports multiple uploads of the same manga.
If you are feeling lucky you can set `deleteOldBookmarks` to `true` which will delete old MangaRock bookmarks which where found.

Feel free to modify this code.
If you add new features like chapter mark migration please share it here so everyone can use it.

**Comment by 27136773** [comment]
Very nice, maybe add some console output to see what has been migrated and what failed...

A good example of the flexibility, you don't even need the UI, you can do everything by accessing the HakuNeko engine
