### ISSUE TITLE
[Kuaikanmanhua] Connector not working

### ISSUE THREAD

**Issue by Nari04** [manga-download/hakuneko#4471]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
For the longest time, it just says "just a moment", and when i tried logging into the connector via the app it wouldn't load and I wasn't able to see anything. 

**To Reproduce**
1. Name of connector : Kuaikanmanhua https://www.kuaikanmanhua.com/ 
2. Name of manga (if connector update is working) : 不宠之臣
3. Name of chapter (if manga update is working) : [第23话 韩峥他还是来了](https://www.kuaikanmanhua.com/web/comic/476070) 
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/101304788/157578191-07b1a7e3-b0b7-43f6-a98e-e97471b809da.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Sheepux** [comment]
Connector is working but the paid content is not showing ?
You used website interaction within hakuneko and it doesn't display the paid content ? 
Also that's not the correct URL to copy, use the chapter list URL: https://www.kuaikanmanhua.com/web/topic/12493/
let me know if it works and if not can you try though the refresh list instead of clipboard ?

**Comment by Nari04** [comment]
No, neither the connecter or the paid content were showing when I sent in the issue, but everything is fine now, thank you!
