### ISSUE TITLE
Several sites not opening

### ISSUE THREAD

**Issue by choclover3b** [manga-download/hakuneko#453]
e-Hentai
luscious
doujins
hentaifox
nhentai
![Untitled](https://user-images.githubusercontent.com/55901341/65808554-eed33180-e18c-11e9-9e65-abeaed700096.png)
all give the same message
there are more, making a list

**Comment by 27136773** [comment]
This error means that it is not implemented. There is no need to make a list for the following reasons:

- other users already made lists
- such a list can be simply auto generated by the developers
- a list will basically be ignored by the developers, because development time is focused on websites that are going to be used (which is not apparent from a list) 🡲 therefore a user has to create an issue for each website he wants to access, so the developer can see that a broken website is in need

See also: https://github.com/manga-download/hakuneko/issues/441#issuecomment-533571335
