### ISSUE TITLE
Preview should not set chapter marker

### ISSUE THREAD

**Issue by 27136773** [manga-download/hakuneko#469]
When clicking the preview button for a certain chapter to show its images, the chapter mark will be assigned to this chapter.
It would be expected that the chapter marker would only be assigned through the reader (open, close or change chapter up/down).

Occurs in development version 83882b8a

**Comment by hypoflex** [comment]
Correct, I've done this with intention.
Reason for doing it like this out of personal prefrence, since i read on multiple platforms (Windows, OSX, IOS (mangarock))

so getting back on a different platform i occasionally press preview to see if that's the correct chapter i left off on my other device.

Guess with bookmark file being able to locate somewhere else now this option can be scraped
and like you said yourself, it also put it once the viewer is closed
https://github.com/manga-download/hakuneko/commit/83882b8aaa5eccee99b1fab2118585840f89c7c7#diff-6dc48bd82fa99890cd7410d38f3f0ea6R439

https://github.com/manga-download/hakuneko/commit/83882b8aaa5eccee99b1fab2118585840f89c7c7#diff-f5eaf4cdf511723135b827d6c5326dd1R439
