### ISSUE TITLE
[Uzay Manga] Connector not working

### ISSUE THREAD

**Issue by MrsLucifer** [manga-download/hakuneko#4792]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
The manga list is not coming.

**Screenshots**
![image](https://user-images.githubusercontent.com/89423242/176372168-29751ade-e104-4dfb-b21c-bd114825f58f.png)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by Mehmet20032003** [comment]
Because of this is a closed issue, I opened a new issue. But it closed because there is already a issue. When I searched I only found this issue, so I think, I should write the problem here. [Uzay Manga] Connector not working. The list is not updating when I click the green arrows. Nightly build didn't fix the issue. I am using HakuNeko 8.3.4. I'm able to see the manga within my standard browser and also on the preview window of hakuneko. The URL is still the same. I tried with and without using VPN. When I entered the website today, Cloudflare screen didn't appear. So can you check it?

![Adsız](https://github.com/manga-download/hakuneko/assets/127633031/7d8f6f1a-8de3-4558-a235-ce69d655d4c9)
