### ISSUE TITLE
[Site Request] https://m.manganelo.com/wwww

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [manga-download/hakuneko#4955]
**Name of the website** Manganelo
[thewebsitename] (https://m.manganelo.com/wwww)

**Website urls (examples below)**
- Site: https://m.manganelo.com/wwww
- Manga List: ???
- Manga example: https://m.manganelo.com/manga-jp123783
- Chapter online viewer example: https://chapmanganelo.com/manga-jp123783/chapter-21

**Languages**
English, possibly more idk.

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

No idea if I'm doing this right or if this is already in the program, but the ones close i found didn't work.

**Comment by MikeZeDev** [comment]
Its just mangaleno/manganato. This website is already supported. Use manganato connector.

**Comment by GeneralUser-NonDev** [comment]
> Its just mangaleno/manganato. This website is already supported. Use manganato connector.

are you sure this site is supported and is the same as your thinking? or did I just find an odd-ball series/title? In my case I'm looking for "Kinsou no Vermeil" or "Vermeil in Gold" and when I type in the connector search "vermeil" I only get 2 connector results "Mangadex" and "Manganelos (by AnyACG)". Mangadex only shows up to chapter 15 of this title and the Manganelos connector shows up to 15.3 (part 3 of ch 15) but errors out when trying to DL them, However the full website mentioned in the submission has up to Ch 21 all of this is as of typing this reply.
![manganelos](https://user-images.githubusercontent.com/96662916/190061033-d42168d7-0918-409d-87e2-d41c5316aba0.JPG)

**Comment by MikeZeDev** [comment]
You made an "add website request" :). So i've just checked the url and its a domain already covered by a connector.

Now if there are bugs, you should have mentioned it. Maybe its worth to change the title? 

It turns out you already made one, but for a clone (or different, as its manganeloS) website (the one by Anyacg)
: https://github.com/manga-download/hakuneko/issues/4956 .

My two cents hypothesis : On manganelo/nato , there are some manga which points to the other website. And OFC the clone website does the same. I've definitely seen that on the clone .

I dont know what is the exact relation between nelo and nato. It could be like mangalife and mangasee.
