### ISSUE TITLE
[leitor] I can't download chapters anymore!!!!

### ISSUE THREAD

**Issue by iriscelio** [manga-download/hakuneko#5033]
When I will download a chapter it gets red with exclamation, adjust this problem please!!!!

Site Name: leitor.net

**Comment by MikeZeDev** [comment]
Please stop deleting the template and fill it properly.
And this issue is already known, there is no need to made duplicate issues :)

https://github.com/manga-download/hakuneko/issues/4526

(maybe this one too https://github.com/manga-download/hakuneko/issues/4391 )

Website seems to be geoblocked and may use more Cloudlfare stuff.
