### ISSUE TITLE
Library error

### ISSUE THREAD

**Issue by enriqueism** [manga-download/hakuneko#51]
hakuneko: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory. 
Ubuntu 19.04 now includes libcrypto.so.1.1

**Comment by 27136773** [comment]
It seems the version of NodeJS that is part of the bundled electron framework for HakuNeko was compiled against a libcrypto library that is not ABI compatible with the one from the latest Ubuntu repository and therefore cannot be run.

The next release of HakuNeko Desktop Client is planned for around august this year and comes with an electron update which shall solve this problem.

Related:
https://bugs.launchpad.net/ubuntu/+source/nodejs/+bug/1779863

**Comment by 27136773** [comment]
electron 5.0.0 was published just some hours ago, so i tried to build a package, but unfortunately there are to much breaking changes for a quick test release.

I deployed some builds based on electron 4.1.4, maybe they will work for you while waiting for the next milestone release...

https://sourceforge.net/projects/hakuneko/files/testing/

**Comment by enriqueism** [comment]
Ok, thanks a lot!

**Comment by enriqueism** [comment]
Same error "hakuneko: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory" I solved my problem running the source directly with npm.

**Comment by 27136773** [comment]
Performed manual pre-flight tests with an internal test candidate based on electron 5.0.6

- [x] Debian 9
- [x] Ubuntu 18.04
- [x] Ubuntu 19.04
- [x] Linux Mint 19.1
- [x] elementary 5.0
- [x] Fedora 30

**Findings:**

- Issue with permissions of `chrome-sandbox` is now fixed during packaging in the build chain
- HakuNeko get stuck on white screen on first launch when the update server cannot be reached (e.g. no network) => maybe inform user with popup?
- Ubuntu Software Center shows license as Proprietary
- Ubuntu Software Center shows package size instead of installation size

**Next Steps**

1. Review client code
2. Finish build script for MacOS
3. Build and release test candidates for all systems
4. Start canary deployment for volunteering/interested test users

**Comment by 27136773** [comment]
Finished all tasks and fixed some minor issues for Fedora 30 in the build tool-chain

**Comment by 27136773** [comment]
For public testing see #266
