### ISSUE TITLE
[Site Request] Bento Manga

### ISSUE THREAD

**Issue by Rad5101** [manga-download/hakuneko#5114]
**Name of the website**
Bento Manga

**Website urls (examples below)**
- Site: http://bentomanga.com/
- Manga List: http://bentomanga.com/manga_list
- Manga example: http://bentomanga.com/manga/the-games-strongest-troller
- Chapter online viewer example: http://bentomanga.com/manga/the-games-strongest-troller/chapter/2

**Languages**
French

**Website relationship**
none

**Additional details**
none

**Comment by Booblover22** [comment]
been waiting for this to be added too but not sure if the downloader even Updates anymore. Its been months since my Hakuneko desktop app even updated to reflect new websites and manga's added.

**Comment by onelots** [comment]
duplicate of #4513, and this website is an horror to scrape so I don't think it'll be done right now aha

**Comment by Rad5101** [comment]
> 

seems to still be updated :)

**Comment by Rad5101** [comment]
> duplicate of #4513, and this website is an horror to scrape so I don't think it'll be done right now aha

idk whats scraping means but if it's the process to take picture from the site so i understand :)

**Comment by Booblover22** [comment]
> > 
> 
> seems to still be updated :)

Idk what version you have but my Nightly version since I downloaded it earlier this year doesnt seem to update at all. I see request after request for new manga sites to be added here on Github but done ever do unless my Hakuneko desktop app just will not update automactically like it should. It always has the white sceen checking for updates when I initalizes it but doesnt show if any updates are found or added.

**Comment by Booblover22** [comment]
> > duplicate of #4513, and this website is an horror to scrape so I don't think it'll be done right now aha
> 
> idk whats scraping means but if it's the process to take picture from the site so i understand :)

Scraping is there way of telling us the requesters they Have NO plans to add that site for whatever reason they concluded.

**Comment by Rad5101** [comment]
> Idk what version you have but my Nightly version since I downloaded it earlier this year doesnt seem to update at all. I see request after request for new manga sites to be added but done ever do unless my Hakuneko desktop app just will not update automactically like it should. It always has the white sceen checking for updates when I initalizes it but doesnt show if any updates are found or added.

i have the same nightly version , same white screen 
idk what's happening [version HERE](https://prnt.sc/SLrICE5nU7uf)

**Comment by MikeZeDev** [comment]
> > > duplicate of #4513, and this website is an horror to scrape so I don't think it'll be done right now aha
> > 
> > 
> > idk whats scraping means but if it's the process to take picture from the site so i understand :)
> 
> Scraping is there way of telling us the requesters they Have NO plans to add that site for whatever reason they concluded.

They have Japscan. They have Japanread. HN support plenty of painful to scrap website (check the obfuscated connectors :D).
Its not that they have NO plan, its because its a pain to do, and time consuming. With limited workforce, and a tons of issues to check on Github, and HN successor development, adding such website is not a priority. Its not a will problem, its being realistic.

If there was NO plan to add it, this issue would have been closed already ^^

**Comment by Booblover22** [comment]
> > > > duplicate of #4513, and this website is an horror to scrape so I don't think it'll be done right now aha
> > > 
> > > 
> > > idk whats scraping means but if it's the process to take picture from the site so i understand :)
> > 
> > 
> > Scraping is there way of telling us the requesters they Have NO plans to add that site for whatever reason they concluded.
> 
> They have Japscan. They have Japanread. HN support plenty of painful to scrap website (check the obfuscated connectors :D). Its not that they have NO plan, its because its a pain to do, and time consuming. With limited workforce, and a tons of issues to check on Github, and HN successor development, adding such website is not a priority. Its not a will problem, its being realistic.
> 
> If there was NO plan to add it, this issue would have been closed already ^^

here is the short definition for Scrapping

To DISCARD or remove from serivce.

Hints they have NO PLANS to add this site because they DISCARDED the idea by rejection. You don't know if HN has a Successor in development unless you are part of the Devs who created the program so don't spout nonsence. It shouldn't matter what a Priority is this is just a Request and the request was rejected. 

Just because this request isnt closed yet doesnt mean it wouldn't be at some point because they discarded the request. aka Scapping the idea. 

HN hasn't been updated in months it COULD mean they are working on something bigger or it could mean there wouldn't be anymore updates. there are Hundreds of Request here on Github for the Team to add or Fix but 90% of them it overlooked because most are Time consuming like you said so the poeple who make the request forget about there request as time prolongs and the website isnt added or fixed after a period of time.

**Comment by MikeZeDev** [comment]
^ TLDR

Its a misunderstanding.
In this context scrapping refers to "scrap from a website". Its "getting data". https://www.geeksforgeeks.org/what-is-web-scraping-and-how-to-use-it/. By no means it means ditching.

> You don't know if HN has a Successor

FYI : https://github.com/manga-download/haruneko/

> HN hasn't been updated in months 

Its auto updating when you launch it. Latest modifications date from yesterday. I made the pull request myself.

You are totally making wrong assumptions.

**Comment by MikeZeDev** [comment]
It turns out they ditched all their stuff in favor of Cloudflare. I can get a manga list but chapters are behind cloudflare barrier :/
