### ISSUE TITLE
[Site Request] GlobalComix

### ISSUE THREAD

**Issue by tatsumasagc** [manga-download/hakuneko#5115]
**Name of the website**
thewebsitename

**Website urls (examples below)**
- Site: https://globalcomix.com/
- Manga List: https://globalcomix.com/browse/
- Manga example: https://globalcomix.com/c/werewoofs
- Chapter online viewer example: https://globalcomix.com/c/werewoofs/chapters/en/1/1

**Languages**
English, Spanish, Japanese, Norwegian

**Website relationship*
N/A

**Additional details**
some comics require premium subscription

**Comment by MikeZeDev** [comment]
Its done. Gotta wait for it to land in HN in a future pull request. Not sure it will works with paid comics.

**Comment by ChristopherGC** [comment]
@MikeZeDev As the creator of GlobalComix, I would politely request that you don't implement this feature at all. This is not behavior we support, and if needed, will go to lengths to prevent this from working.

**Comment by MikeZeDev** [comment]
@ChristopherGC  Thanks you for reaching me. I am just a contributor, so keep in mind i am just expression my own opinion which may or may not reflect HN main devs pov.

I don't see the problem, as HN wont obviously allow downloading paid stuff without it being paid. I don't see why people wouldn't be able to download the comics they paid for. What i can understand is bandwidth / server costs.

Anyway, no need for more debate, as per your request, file is now removed with the next commit. Its all i can do for now. I do not intend to play cat and mouse. Both of us will lose more time doing that.

Feel free to make little changes so it doesn't work anymore (so people wont use commit history), i wont press further. I mainly do that in my free time, for fun, and because someone asked. In fact you should do it already because people the repo is public after all.

Sorry for the inconvenience.

**Comment by ChristopherGC** [comment]
@MikeZeDev thank you :) I've done as you suggested! I appreciate the willingness to cooperate on this since we're working very hard to get readership up in the intended experience for the various indie creators to find a real following and engagement.

A 3rd party app that strips out that context is a losing situation for them :(

**Comment by 27136773** [comment]
> As the creator of GlobalComix, I would politely request that you don't implement this feature at all. This is not behavior we support, and if needed, will go to lengths to prevent this from working.

If you don't want a website to appear in HakuNeko, or want to add a donation link within HakuNeko the website have to met some strict requirements which can be found in the [Removal Request Template](https://github.com/manga-download/hakuneko/issues/new?assignees=&labels=Removal+Request&template=5-website-removal-request.md&title=Removal+Request+for+%5BWEBSITE%5D).

Without the approval of a `Website Removal Request`, the contributors are free to add the website and the maintainers are free to accept such contributions.

**Comment by Sheepux** [comment]
seing how fast he was to comment i'm also guessing he's a HakuNeko user himself :P

**Comment by ChristopherGC** [comment]
> seing how fast he was to comment i'm also guessing he's a HakuNeko user himself :P

Haha, or, you know, I could have Google alerts for mentions of GlobalComix showing up 😅 Also, "watch this/subscribe to updates"  on the thread now :-)
