### ISSUE TITLE
[iceKR ] Same image pops up sporadically 

### ISSUE THREAD

**Issue by siennk** [manga-download/hakuneko#5127]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
So, I don't know if it is a bug with HakuNeko or if it is a bug on individual sources, but for some Chinese sources, the same image pops up constantly replacing pages of the actual comic.

**To Reproduce**
iceKR is one source I've noticed this repeatedly on.

**Screenshots**
This is the image that repeatedly comes up.
<img width="927" alt="Screen Shot 2022-11-06 at 8 58 34 PM" src="https://user-images.githubusercontent.com/25418911/200212258-2c07035c-1224-481c-b381-82e2caa981dd.png">

<img width="1257" alt="Screen Shot 2022-11-06 at 9 10 30 PM" src="https://user-images.githubusercontent.com/25418911/200212390-ede406de-0a8b-4dba-a9a8-737882db46f2.png">

**Context (please complete the following information):**
 - OS: Mac
 - HakuNeko Version: 6.1.7

**Comment by Sheepux** [comment]
"some connectors" is a thing that cannot be analysed
Give the connector/title/chapter having an issue (we cannot recopy it from a screenshot)

**Comment by MikeZeDev** [comment]
Interesting (?) finds. On the website, its fine. Like, always fine. However, if i open a picture link in another tab, i got the bad picture instead. Why it is interesting? Because my Firefox has a particular referer policy. I do not have this problem on Firefox Nightly because i didnt tweak it for on purpose.

if i try curl <picture url> without a referer, i got a 301 code. With icekr.com as referer i got the picture fine.

I thing the referrer trick is worth a try.

**Comment by MikeZeDev** [comment]
Addin referer seems to fix the issue. :) Pr https://github.com/manga-download/hakuneko/pull/5138 .
