### ISSUE TITLE
[MangaWT] Connector not working

### ISSUE THREAD

**Issue by MrsLucifer** [manga-download/hakuneko#5147]
There is no member login on the site, but the sections ask for a member login requirement.
With normal electron, sections open without any problems.

site : mangawt.com

`import WordPressMangastream from './templates/WordPressMangastream.mjs';

export default class MangaWT extends WordPressMangastream {

    constructor() {
        super();
        super.id = 'MangaWT';
        super.label = 'MangaWT';
        this.tags = [ 'webtoon', 'turkish' ];
        this.url = 'https://MangaWT.com';
        this.path = '/manga/list-mode/';

        this.queryPages = 'div#readerarea img[loading]';
        this.requestOptions.headers.set('x-user-agent', 'Mozilla/5.0 (Linux; Android 9; Pixel) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4026.0 Mobile Safari/537.36');
    }

    async _getPages(chapter) {
        const excludes = [
            /panda_gif_large/i,
            /2021\/04\/page100-10\.jpg/i,
            /2021\/03\/20-ending-page-\.jpg/i
        ];
        const images = await super._getPages(chapter);
        return images.filter(link => !excludes.some(rgx => rgx.test(link)));
    }
}`

**Comment by MikeZeDev** [comment]
You see a login message because HN does not fetch any pictures from chapters, so it assume you have to login to get them :D

The reason is : your "queryPages" value is incorrect. The default one, from the WordPressMangastream template, works.

Does this code come from you? Because its not on HN repo, and not on your fork apparently..
Thanks for fixing this but : 

* I dont see why a custom user-agent is needed, it works without it.
* what pictures are you trying to exclude from results?  Can you give examples pls?
