### ISSUE TITLE
[GammaPlus] Connector not working

### ISSUE THREAD

**Issue by Zalugar** [manga-download/hakuneko#5164]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
It appears Gamma Plus has revamped its website. HakuNeko can load the manga series list, but will not load any chapters from any series.

**To Reproduce**
1. Name of connector - GammaPlus
2. Name of manga (if connector update is working) - All
3. Name of chapter (if manga update is working)  - All
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - The console gives no relative message when attempting to access manga.

**Screenshots**
![ScreenshotGammaPlus](https://user-images.githubusercontent.com/118584820/202833942-731349d4-e957-4c1b-beb1-3487c25e2f14.png)

**HakuNeko (please complete the following information):**
 - Version [6.1.7@a8da6a]

**Comment by tsenglol** [comment]
@MikeZeDev 

The meanwhile solution i found for this after seeing how StoriaDash was fixed and what was different since they use the same site now (since StoriaDash changed their site back in april), was edit the GammaPlus.mjs file in the cache\mjs\connectors folder and change './templates/TakeShobo.mjs' to './templates/TakeShoboNew.mjs'

https://i.imgur.com/66F8Yrz.png

None of the TakeShobo sites WebComicGamma, GammaPlus and StoriaDash use the old 'TakeShobo.mjs' template now, but the 'TakeShoboNew.mjs' instead, so when this get fixed, gotta remove the old template for good and just keep the new one, since these 3 sites use the new template now, i suppose

(tho i reported the solution in discord the day it happened, but they told me to do a pull request for it, but am too dumb for that)

**Comment by MikeZeDev** [comment]
Its nice you found the solution but please let the issue open. Issues are meant to be closed when the problem is fixed for everyone.
