### ISSUE TITLE
[Feature] Volumes download support

### ISSUE THREAD

**Issue by Kenny-Stilyan** [manga-download/hakuneko#5229]
**Is your feature request related to a problem? Please describe.**
When iam trying to download volumes some of them work the other one doesn't 

**Describe the solution you'd like**
Maybe expanding download size if that is possible 
Or when you can't download the file to be split into separate parts 

**Describe alternatives you've considered**
I know downloading the chapters are the better idea but honestly if there are Volumes available I prefer them because i have less files and its more easy to read than the chapters (opening, closing, opening the next one....)

Thanks for your hard work

**Comment by MikeZeDev** [comment]
* How are we supposed to know which chapters are part of a volume? 

Most website does not give the info. And when they do, each website doing that is kinda using their own format and its a pain in the butt do it properly. From what i understood, **we are not going to handle volume "separately", at least for the moment.** But i may be wrong.

* Volume should download like others if they are treated as chapters on the website. That is the default behavior. And it works for most websites. 

I know what is your problem : you are using a website where hakuneko needs to do some task to let you download. Because the website is protecting its stuff. Its works fine when its a just a chapter but when its volumes its ...pooping in the fan because of timeout. And sometimes it works.

We have to consider not making the experience worst when you download by chapters if we have to change something to circumvent this volume problem, that is tricky at least for me.
