### ISSUE TITLE
[MangaDex] Cant get manga list

### ISSUE THREAD

**Issue by TKCeegit** [manga-download/hakuneko#5258]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
Failed to update manga list for MangaDex

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/100026834/208782386-e9752fef-cec6-4310-aee5-f348a44e5cdc.jpg)

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by MikeZeDev** [comment]
Same. Its just Mangadex having hickups, because fetching mangas works for a while then boom http error.
Probably nothing to fix.

Try increasing throttling in options, wait a bit and retry or...use another website.

**Comment by TKCeegit** [comment]
@MikeZeDev Okay, I'll try doing that later on tonight. Thanks for the response.

**Comment by MikeZeDev** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/commit/9aa3d12afffe591a75398532601ae76179b8f0c0 Not sure what it implies

**Comment by TKCeegit** [comment]
@MikeZeDev I'm lost just from looking at that, does that mean MangaDex can't accessed by other readers?

**Comment by MikeZeDev** [comment]
I mentioned that change for other devs, Dont mind it. I dont know what it implies i never worked on Mangadex

**Comment by TKCeegit** [comment]
Alright. It sucks that Mangadex is so troublesome, I like the site because of its large library. Bato.to could've been a suitable alternative to try but just like Mangahasu the manga list loads but zero chapters.

**Comment by dgags** [comment]
It's been months since this worked. I've tried running the dev version locally, following the instructions, but I'm not a developer by trade. I tried looking for debug options for "npm start" in package.json but I could not find anything promising to help uncover the error given above.

"Failed to update manga list for MangaDex

Failed to receive content from "https://api.mangadex.org/manga?limit=100&offset=3300&order%5BcreatedAt%5D=asc&contentRating%5B%5D=safe&contentRating%5B%5D=suggestive&contentRating%5B%5D=erotica&contentRating%5B%5D=pornographic" (status: 400) - "

An error 400 (bad request) does not seem like website flakiness to me, although I do admit that Mangadex has had some troubles in the recent past. I'd be happy to dig into this, but I would need someone to pair up with.

**Comment by MikeZeDev** [comment]
1) The updating loop works until servers reject us and said rejection happens randomly so its hard to track.

2) I didnt design mangadex connector and i am not familiar with their api making it harder to fix. Not to mention they often change stuff.

3) Pasting solution still works, Bookmarks too (after pasting) so its not really a big deal. Although its frustrating to see such popular website partially not working and people asking for it :/

4) I tested this in [Haruneko ](https://github.com/manga-download/haruneko) and i got the list fine so there is hope :D

5) Time management. We are focusing on Haruneko. Fixes are still pushed to Hakuneko often but this one is hard for me to track and others devs are busy.  

You are welcome if you want to investigate the issue.

**Comment by dgags** [comment]
@MikeZeDev Thanks a lot for taking the time to reply. It might take me some time, but I'm going to try understanding how the connector works and maybe hop on the Mangadex discord to see if one of the site devs would be willing to work with me on this. I can't promise a quick turnaround, but i'm going to dig in a bit.

Is the pasting solution you mentioned documented somewhere?
