### ISSUE TITLE
Lezhin low res download

### ISSUE THREAD

**Issue by L3foow** [manga-download/hakuneko#527]
Hello,

there is a problem when downloading chapters from lezhin with 1080p resolution, hakuneko downgrades the resolution and download them as 720p res, why?

**Comment by 27136773** [comment]
HakuNeko uses the default quality instead of enforcing either w720 ([q=30](https://github.com/manga-download/hakuneko/blob/6ca1e5c8f5bba2ca497adf419965243a577939b0/src/web/mjs/connectors/templates/Lezhin.mjs#L216)) or w1080 ([q=40](https://github.com/manga-download/hakuneko/blob/6ca1e5c8f5bba2ca497adf419965243a577939b0/src/web/mjs/connectors/templates/Lezhin.mjs#L212)). I cannot remember if there was a reason to set it to auto...
