### ISSUE TITLE
Remove WuxiaWorld 

### ISSUE THREAD

**Issue by wuxiaworldsite** [manga-download/hakuneko#532]
Please remove Wuxiaworld site from hakuneko as it is causing a lot of server issues lately. @ronny1982 

Admin WuxiaWorld.Site

**Comment by 27136773** [comment]
For the removal process you need to answer the following questions and if they are legit and satisfying the additional removal conditions must be fulfilled. Feedback from the community might be requested as well if a clear decision is not possible. It is also possible to request a donation link within HakuNeko, which has more relaxed conditions then the removal request.

Since this is not the first removal request, be aware that HakuNeko has its own analytics support which was added in the past and can be added anytime again to verify analytics claims made by website owners, so i suggest to answer the following questions honest:

----

### QUESTIONAIRE

1. How much traffic is caused by HakuNeko?
2. How much is it compared to overall traffic (percentage)?
3. How did you measure those analytics (framework)?
4. How exactly did you distinguish traffic caused by HakuNeko from those caused by a web-browser?
5. Are you already using a proper configured CDN to reduce bandwith (e.g. CloudFlare's free plan)?
6. Are you aware that users will still access the website and cause the traffic anyway, even if the website is removed from HakuNeko?

----

### I - REMOVAL CONDITIONS

To remove a website from HakuNeko, the website must
- met the AMP standard regarding advertisements (only a single non-intrusive advertisement is allowed per page)
- must provide direct download links for all chapters

----

### II - DONATION CONDITIONS

To qualify for a donation link in HakuNeko:
- the website must comply with the "Acceptable Ads Standards" by the Acceptable Ads Committee (non-intrusive, non-content-blocking, ...)
- the website's intent must be focused on cultural contribution of content (e.g. scanlator group websites) and not on other things, e.g. monetizing (e.g. aggregation website)

**Comment by 27136773** [comment]
No further response => request rejected
