### ISSUE TITLE
Could not run Hakuneko on macOS catalina after the supplemental updates of version 10.15, application removed from the directory and disks and could not open after redownload. 

### ISSUE THREAD

**Issue by Macdada1** [manga-download/hakuneko#538]
Hakuneko works perfectly fine on all my PC, and Imac , but recently on the client Desktop app on macbook air with macOS Catalina's release of **supplemental updates** (version 10.15) on 15 october, after restarting mac the application disappear completely from the application directory, launch pad , and the main HD disk. Therefore i redownload the mac .dmg application again from github release pages,  now macOS came up with a warning  as following : 

<img width="1103" alt="Screen Shot 2019-10-18 at 20 36 47" src="https://user-images.githubusercontent.com/48245221/67099572-69b9c600-f1e8-11e9-9bb4-7c7b4f909b13.png">

the security and privacy section allows application downloaded from app store and idenfied developer ; firewall is off and all settings are the same as one previously running on macOS catalina before supplemental releases.

**Comment by 27136773** [comment]
Could you try to test if this problem also occurs with a newer version of HakuNeko, e.g. 5.0.8 or the last Nightly build.

**Comment by hypoflex** [comment]
First off, next time remove your serial number from the screenshot, for your own safety.

next, 10.15 should work without a problem, i've just downloaded and installed the latest 5.0.8 from github
(https://github.com/manga-download/hakuneko/releases/download/v5.0.8/hakuneko-desktop_5.0.8_macos_amd64.dmg)
![image](https://user-images.githubusercontent.com/36196198/67211868-bc2ef880-f41b-11e9-9c6d-a843878c5463.png)

**Comment by hypoflex** [comment]
Statement by AppleCare:
- Run /Applications/Utilities/Disk Utility.
- Click on &#8220;Macintosh HD&#8221; in the left column and then press the &#8220;Repair Disk Permissions&#8221; button.
- Delete the file called /System/Library/Extension.kextcache
- Delete the folder called /System/Library/Caches/com.apple.kernalcaches/
- Restart

Source:
https://macosx.com/threads/disk-image-failed-to-mount-device-not-configured.265270/post-1276862

Note:
I'm in no way responsible for issues possibly caused by this fix.
This issue seems to be OSX upgrade related and not related to HakuNeko itself.
