### ISSUE TITLE
[Nitro Scans] Connector not working

### ISSUE THREAD

**Issue by Prabathsl97** [manga-download/hakuneko#5385]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No

**Describe the bug**
Website has moved to a different address.
to - https://nitroscans.online/
**To Reproduce**
1. Nitro Scans
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Nitroscans.com redirect to Darkscans.com so it was changed recently https://github.com/manga-download/hakuneko/commit/bbe339357da44c1beff343bd0fbf584de5dad3e4 . And now we have another Nitroscans popping from nowhere, whats going on?

**Comment by Prabathsl97** [comment]
> 

It seems like they relocated to a new address.

**Comment by MikeZeDev** [comment]
Yeah but should i trust the redirection or someone who said another one is the new address? No offense btw

**Comment by Prabathsl97** [comment]
> Yeah but should i trust the redirection or someone who said another one is the new address? No offense btw

None taken. Just try googling 'nitro scans'.

**Comment by MikeZeDev** [comment]
Google search gives me https://nitroscans.club/index.php, with raw mangas, probably unrelated. and nitroscans.net a news websites about mangas anime but no scans or mangas inside.

Reddit says they rebranded : https://old.reddit.com/r/manhwa/comments/104brg6/what_happens_to_nitro_scans/.

Since google and reddit are not reliable, but the reddit info match the old url redirection i think we will stick with darkscans.
Unless you got other infos directly from said group ofc.

**Comment by MikeZeDev** [comment]
Tachiyomi use https://nitromanga.com/, gotta do the same
