### ISSUE TITLE
[Kuaikanmanhua] Connector not working

### ISSUE THREAD

**Issue by ErickShadow12** [manga-download/hakuneko#5511]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes/No
yes.

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes/No
yes.

**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

[**Screenshots**
If complex to describe, add screenshots to help explain your problem.](url)

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]
![Captura de pantalla 2023-02-28 025732](https://user-images.githubusercontent.com/126554747/221789676-2064f622-9764-4b17-9f42-29401278126f.jpg)
you do not go out the chapters of the manhua

**Comment by MikeZeDev** [comment]
By all means , use nightly. There have been a fix in december.

If it works close this issue. If it doesn't, write the manga name in your message, because having it on a screen wont help, i cant type chinese and i cant copy and paste from a picture.

If by "no sale" you are referring to bought chapters, make sure you had logged into the website through "Manual Interaction" before trying to view the chapters. Close haku, log in and retry to be sure cause chapters list is cached.

If you cant see bought chapters after logging like that, i may require your assistance on Hakuneko Discord as i wont buy myself to test.

**Comment by MikeZeDev** [comment]
Managed to copy the text with Google Lens. I got one chapter available 

![image](https://user-images.githubusercontent.com/10671518/221816956-4538e3fa-ab2a-4d3b-b51e-349d40649126.png)
