### ISSUE TITLE
[ReadM and Manhuafast] Connectors not working

### ISSUE THREAD

**Issue by tsentered** [manga-download/hakuneko#5548]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**

Error pops up when trying to view/ download chapters (both connectors, same error, started at the same time (which is why I doubled this up, it feels connected)

**To Reproduce**
1. Name of connector - Manhuafast and ReadM
2. Name of manga (if connector update is working) - NA
3. Name of chapter (if manga update is working) - NA
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12) - See screenshots

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

<img width="1383" alt="Screenshot 2023-03-09 at 8 20 46 AM" src="https://user-images.githubusercontent.com/70929406/224092902-6b86941e-1bc3-490e-a8f5-8251e8e315c6.png">
<img width="1257" alt="Screenshot 2023-03-08 at 6 37 09 AM" src="https://user-images.githubusercontent.com/70929406/224092938-a3fb3330-1d17-48d2-b1e9-9818b6e0c8c7.png">

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
Open 2 tickets for 2 differents websites pls. Those website have absolutely nothing to do with each other.

**Comment by MikeZeDev** [comment]
1) If you were to actually read what is written on ReadM you will see they put a captcha before chapters. Open website in hakuneko Manual Interaction, solve the captcha and it works

2) Manhuafast works

**Comment by tsentered** [comment]
Having a bad day, are we? I actually have read it and if you had actually looked at the screen shots you I provided, you would have seen that I did not have the captcha issue. You can see the sites in the background. But thank you for the warm response. I’ll send you two new pics, please be sure to look. Regardless, I appreciate you guys even with unwarranted snarky comments.



￼￼

**Comment by MikeZeDev** [comment]
ReadM frontpage : 

![image](https://user-images.githubusercontent.com/10671518/224158109-70250ebd-097f-45d5-bd51-95cf1efaffba.png)

The error you get when you want chapters is actually caused by the captcha (its a generic error which means nothing) 

![image](https://user-images.githubusercontent.com/10671518/224158443-4477b5b0-e6de-4442-97b5-4d2c969320d1.png)


Again, fill the captcha using Manual Interaction and it will work.

There is nothing hakuneko can do. 

And Manuhafast is working .

**Comment by tsentered** [comment]
As you saw, I have no issues with the captcha. You only need to go through it once (stated in the shot you just now sent).. Then it should work. It doesn’t. It’s not a big deal, either way.

**Comment by MikeZeDev** [comment]
> As you saw, I have no issues with the captcha

Forget what you see in real browser, lets focus on Hakuneko please. You are showing screens of your browser webpages, and generic Hakuneko messages that just means "cant find chapters". 

There are chances recaptcha just give the ok and you may not even see it in real browser. Because its a real browser. Its not he same for Hakuneko.

> You only need to go through it once (stated in the shot you just now sent).. Then it should work. It doesn’t. 
Thats weird because it works for me. I can confirm got myself captcha and stuff. In Firefox and Hakuneko webview. 

Now i can think about differences between you and me : 

* I use nightly build but that shouldnt make a difference. You may want to give it a try idk
* Can you precisely describe what you did In hakuneko after i warned you about the captcha? 

We need to go deeper :D

> It’s not a big deal, either way.

Thats cool. Issues needs to be fixed anyway, no biggie

**Comment by MikeZeDev** [comment]
Like i told you, it works for me 🤷 

![image](https://user-images.githubusercontent.com/10671518/224282543-c486141e-425d-456e-b62f-f5f58e190f64.png)

![image](https://user-images.githubusercontent.com/10671518/224282672-8618bfec-9695-4d32-b942-ff5db92e6c8f.png)

![image](https://user-images.githubusercontent.com/10671518/224282725-a54536af-e9d7-45e1-b727-9082f839286b.png)

Idk what to say :/

**Comment by MikeZeDev** [comment]
They removed captcha system for now
