### ISSUE TITLE
[9ANIME] Connector not working

### ISSUE THREAD

**Issue by Deon8339** [manga-download/hakuneko#5573]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

1. Connector name : 9ANIME
2. Its a website for watching anime, i think the url for the connector is invalid as i try to copy the url and paste it on google, Its invalid. It cant be access. But when i try to open the official website, im able to open it. Based on what i see, the officia link and the connector link are not the same. Official link is https://9animetv.to/home while the connector link is https://9anime.to. 

**HakuNeko (please complete the following information):**
 - Version [e.g. 6.17]

**Comment by MikeZeDev** [comment]
The link has been 9anime.to for a while and website answer. If you cant access to it change your DNS our use a VPN, We wont add a clone / copycat just because people cant access to the original. Imagine the mess if we do that.

![image](https://user-images.githubusercontent.com/10671518/224965766-431722cc-1cb2-4be2-9045-f28489bd3671.png)

**Comment by spectreninja** [comment]
I can access it via the website but it doesn't load in the application somehow
