### ISSUE TITLE
Folder Viewer ... Reader not working

### ISSUE THREAD

**Issue by ms308680** [manga-download/hakuneko#567]
I do not know if this was intentional or not, but no matter the version[5.0.8 or 6.0.12], the result is the same.

First off, the built-in viewer for manga is absolutely awesome.

This is mostly a non-issue if you never organize your downloads and leave them accessible through bookmarks and their originally downloaded folders/file names.

But for Clipboard downloads, I can only get back to the manga through the Folder Viewer

while it lists all the folders, it does not let me actually read any manga nor watch any videos downloaded either.

a note for the manga side is I am downloading them as epub files, and while they show fine in bookmarks if you try to look at them in Folder Viewer, you get the following message if you try to double click on the manga name to open the folder as you would in bookmarks:

Windows cannot find 'x:\mangas\[Folder Viewer]\Mangafox\.' Make sure you have typed the name correctly, and then try again.

It is failing since the path is incorrect, the program is adding \[Folder Viewer] when the actual location of the mangafox directory is actually at 'x:\mangas\Mangafox\.'

I also have subdirectories checked in settings so it sorts the files as such.

**Comment by 27136773** [comment]
Actually these are two separate issues:

- [ ] When the `Use Sub-Directory` checkbox is checked in settings, the double click on a chapter does not open the correct path to the manga containing the chapter with the `Folder View` plugin. The reason is because the `Folder View` plugin adds itself to the path as sub-directory. When disabling the checkbox in the settings, the double click for the `Folder View` plugin works as expected.
- [ ] The `Folder View` plugin does not show nested mangas. This behavior is currently expected. The `Folder View` plugin requires a strict structure: The root folder must contain manga directories and the manga directories must contain chapters. Nested sub-directories such as website names are not supported as there is no possibility to navigate into nested directories from within HakuNeko. This restriction should be added to the tooltip.

**Comment by 27136773** [comment]
Tooltip will be updated to explicitly state that only top-level mangas are supported (no nested folders).

Fixing the issue when opening the chapter with double click by using the correct path configured for the FolderViewer in the settings.
