### ISSUE TITLE
Line Webtoon (English) Connector not working

### ISSUE THREAD

**Issue by Proto-Pool** [manga-download/hakuneko#5748]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes

**Describe the bug**
So when I put in the Line Webtoon (English) and do the thing to synchronize it, it just says Failed to update manga list for Line Webtoon (English) and it tells me to directly put the link in and am not certain if I did it correctly or not but I put the link of the Webtoon I wanted to read and it is https://www.webtoons.com/en/drama/get-schooled/list?title_no=2684 in the MANGA section below the WEBSITE section and it is just bland.

**To Reproduce**
Dont know how to, just happened

**HakuNeko (please complete the following information):**
 - Version 6.1.6

**Comment by MikeZeDev** [comment]
Sure, website does not provide an accurate list, so you have to paste the link.

>i put the link of the Webtoon I wanted to read and it is https://www.webtoons.com/en/drama/get-schooled/list?title_no=2684 in the MANGA section below the WEBSITE section and it is just bland.

Because you didnt actually read the manual. Copy the link from browser, and use the paste button from Hakuneko interface. What you used is the manga FILTER and has nothing to do with pasting (and its useless with empty manga list)

![image](https://user-images.githubusercontent.com/10671518/235438444-b4025662-bac3-4ae5-be16-20516ee60bef.png)
