### ISSUE TITLE
[lilymanga] Connector not working

### ISSUE THREAD

**Issue by mrfoott** [manga-download/hakuneko#5758]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
Yes

**Is the website of the connector working properly / are you able to see the manga within your browser**
Yes
**Describe the bug**

**To Reproduce**
1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Screenshots**
If complex to describe, add screenshots to help explain your problem.

**HakuNeko (please complete the following information):**
 - Version [8.3.4]
 - Portable version [8.3.4]
![mangalist](https://user-images.githubusercontent.com/48422434/235856865-1cc4ffbb-ec85-4c16-8e4a-b92c846ecfe2.png)

**Comment by MikeZeDev** [comment]
Please check website before opening an issue and waste our time, because website is broken

![image](https://user-images.githubusercontent.com/10671518/235866364-19b69eac-36da-49fe-8367-626ce7ffc903.png)

Same for when you want to check a chapter

![image](https://user-images.githubusercontent.com/10671518/235866660-3a308e70-3685-4348-97ca-20d1cc50ea4c.png)

Remember Hakuneko is a browser, and browsers cant fix broken websites.
