### ISSUE TITLE
Madara (_getChapters): call _getChaptersAjaxOld only when _getChaptersAjax fails

### ISSUE THREAD

**Issue by TristanWasTaken** [manga-download/hakuneko#5865]
**Is your feature request related to a problem? Please describe.**
The madara connector currently uses promise.all() to call both `_getChaptersAjax()` and `_getChaptersAjaxOld()` ([link](https://github.com/manga-download/hakuneko/blob/697dd7c7a23b715832e833548a683add78849fa7/src/web/mjs/connectors/templates/WordPressMadara.mjs#L97-L100)). Most madara sites with sane site admins now use the newer versions that don't need the extra request of `_getChaptersAjaxOld()`, which means hakuneko spams invalid 400 requests for most madara sites. This strains the affected sites with unnecessary requests that could be avoided.

**Describe the solution you'd like**
Only call the `_getChaptersAjaxOld()` function when the `_getChaptersAjax()` request fails.

**Describe alternatives you've considered**
- some kind of per-site option to use the old method instead of the new one
- Removing the `_getChaptersAjaxOld()` function.

**Context (please complete the following information):**
 - Version: 6.1.7 (madara connector commit 697dd7c)

**Additional context**

**Comment by MikeZeDev** [comment]
* Its one single request by manga when getting chapters.
* Its only triggered when user click on a particular manga. So there at least will be a reasonable delay.
* And it wont be repeated while Hakuneko is not closed as chapters list is cached in memory.

Alternative 1 is fine but you need someone to check all those madara connectors.
Alternative 2 is not acceptable because some websites may still use it. Then its similar to alternative 1 where someone have to check every madara connectors anyway.

And needless to say, if someone make a PR it would have to be validated by a dev, so it means checking those websites again :D

I know the current situation is not ideal, but considering the workload and the little impact on servers, i am not sure this will be fixed. At least i can cay its already "fixed" in HaRUneko, as it works quite differently :)

**Comment by MikeZeDev** [comment]
Not planned
