### ISSUE TITLE
[Site Request] Olympus Scanlation

### ISSUE THREAD

**Issue by Frezian** [manga-download/hakuneko#5887]
**Name of the website**
Olympus Scanlation

**Website urls (examples below)**
- Site: https://olympusscans.com/
- Manga List: https://olympusscans.com/capitulos
- Manga example: https://olympusscans.com/series/comic-reencarne-como-el-heredero-loco
- Chapter online viewer example: https://olympusscans.com/capitulo/65816/comic-reencarne-como-el-heredero-loco

**Languages**
Spanish

**Website relationship*
If applicable describe the relation with any other website (eg : "alternative domain, copy of ...").

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
1) [Its already supported ](https://github.com/manga-download/hakuneko/blob/8eefa74914313837a6ae62124f886b32e7ccdb1d/src/web/mjs/connectors/OlympusScanlation.mjs#L4)
2) [An issue is already opened](https://github.com/manga-download/hakuneko/issues/5517)
3) [A fix is pending already because of mentioned issue](https://github.com/manga-download/hakuneko/pull/5521)

Please use search before posting.

Duplicate https://github.com/manga-download/hakuneko/issues/5517
