### ISSUE TITLE
[aquamanga.com] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#5982]
**Did you [try Nightly Build](https://github.com/manga-download/hakuneko/releases) ?**
No

**Is the website of the connector working properly / are you able to see the manga within your browser**
No

**Describe the bug**
unable to visit website
error message:
aquamanga.com
Warning 
Your browser is out of date!
Update your browser to view this website correctly. [More Information.](https://developers.cloudflare.com/fundamentals/get-started/concepts/cloudflare-challenges/#browser-support)

**To Reproduce**

**HakuNeko (please complete the following information):**
 - Version 6.1.7

**Comment by MikeZeDev** [comment]
I tested it works. Use nightly by all means, there is a reason why the question is in the template.

In your case, a workaround was pushed recently because of that old browser error. That fix is only available on nightly build.

![image](https://github.com/manga-download/hakuneko/assets/10671518/ad89d018-ea9b-4139-a424-d1a54797bbaf)
