### ISSUE TITLE
[MangaLivre] Another error just happened

### ISSUE THREAD

**Issue by Rodrigo-017** [manga-download/hakuneko#6281]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

After merging with Leitor.mjs, another error just happened when finding chapters "TypeError: Cannot read property '1' of null". 
Looking forward for who can fix this, thank you.

### To Reproduce

1.  Connector Name: MangaLivre
2. Name of manga: Any Manga
3. Name of chapter: Not showing chapter list
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
> "After merging with Leitor.mjs"

I dont know what you are trying to achieve by messing with files, but Mangalivre/Leitor is well known here for not working .

https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+MangaLivre&type=issues
https://github.com/search?q=repo%3Amanga-download%2Fhakuneko+Leitor&type=issues

2 reasons : 

1) website is geoblocked, meaning only BR or PT ip can access it, so our devs cant work on it. 
2) Even with such an IP, the system responsible for geoblocking, CloudFlare, is also preventing bots (and hakuneko) to work, and there is no easy solution. It has been for 2 years. 

Closing this, because its a duplicated issue, i wont bother linking one there are plenty
