### ISSUE TITLE
[Site Request] Young Animal

### ISSUE THREAD

**Issue by Redyn** [manga-download/hakuneko#6310]
**Name of the website**
Young Animal (ヤングアニマル)

**Website urls (examples below)**
- Site: https://younganimal.com/
- Manga List: https://younganimal.com/category/manga
- Manga example: https://younganimal.com/series/1e7265ecd37fc
- Chapter online viewer example: https://younganimal.com/episodes/3841af51f2d4a

**Languages**
Japanese

**Website relationship*
I'm told it uses the same viewer as Yanmaga (https://yanmaga.jp/), though I haven't confirmed it

**Comment by MikeZeDev** [comment]
Yup, Youngchampion && Yanmaga use the same

**Comment by Redyn** [comment]
Is there any reason this couldn't be implemented?

**Comment by MikeZeDev** [comment]
The reason is i stopped added websites to Hakuneko. The reason for that is we are working hard on [Haruneko](https://github.com/manga-download/haruneko) which will be Hakuneko next major version, from scratch.

I am only fixing stuff in Hakuneko now. User submitted websites (not requests, but code) are still welcomed, for now i guess? 

Requested websites will eventually land in Haruneko.

**Comment by MikeZeDev** [comment]
Duplicate https://github.com/manga-download/hakuneko/issues/5556
