### ISSUE TITLE
[<ManhuaScan>] Connector not working

### ISSUE THREAD

**Issue by Anniv123** [manga-download/hakuneko#6357]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Failed to updated manga list. 

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
> Chapter list isn't refreshing
> Failed to updated manga list.

Tried both Manhuascan. Both features. Everything works. Chapters are listed and pictures are displayed.
Can you give the manga link please? Are you trying from a bookmark?

**Comment by MikeZeDev** [comment]
It was fixed 2 months ago. https://github.com/manga-download/hakuneko/pull/6175

Fix is available in nightly. And you said your tried nightly but i doubt it. Did you just check the checkbox without trying because of lazyness ? 

![image](https://github.com/manga-download/hakuneko/assets/10671518/c6c9a347-e558-4b11-90c7-9d3c2eda2f20)
