### ISSUE TITLE
[Feature] Manga status

### ISSUE THREAD

**Issue by samanta-widjaja** [manga-download/hakuneko#6359]
Right now the status color only in library or not. Could we have status such as complete or hiatus. So when we add to library its default, but can be changed into complete, hiatus, etc. 

Thank you

**Context (please complete the following information):**
 - Your current HakuNeko Version 6.17

**Comment by MikeZeDev** [comment]
This information is rarely available on websites. Not sure it could be done reliably. Maybe in Haruneko, with manga tracking services?

**Comment by samanta-widjaja** [comment]
what i mean is we can change the status ourself. Is haruneko already officialy published? 

Thank you

**Comment by Sheepux** [comment]
I believe this use case is covered in https://github.com/manga-download/hakuneko/issues/1912
Completed would be a folder (you create whatever you want) and you can add a custom label "completed" to a title so that it get moved to the folder.
The issue #1912 is tracked within haruneko's experimental zone https://github.com/manga-download/haruneko/issues/40

Samanta, can we close your request (#NoDuplicates) or is it still another topic ?
