### ISSUE TITLE
[youngchampion.jp] Latest Chapter didn't show.

### ISSUE THREAD

**Issue by raeka21** [manga-download/hakuneko#6393]
**Describe the bug**
The latest chapter, Ch.6 part 1 and 2 didn't show

**To Reproduce**
1. Go to https://youngchampion.jp/series/9aaea584c31f6/pagingList?s=2&page=0&limit=50 to confirm the manga.
2. Now paste the series on hakuneko nightly build.
3. See error.

**Expected behavior**
I want to download ch 6 part 1 but unable due to how it didn't show ch 6. It did show chapters only up to ch. 5

**Context (please complete the following information):**
 - OS: [Windows10]
 - HakuNeko Version [nightly build rev. master@4a9c79]

**Additional context**
I'm using the nightly build.
Also I don't know if I had given the right Hakuneko version. CMIIW.

**Comment by MikeZeDev** [comment]
1) The link you pasted may not work at all because it has something after serie ID. Just paste the manga page link as it is on the website https://youngchampion.jp/series/9aaea584c31f6 and dont overcomplicate thing by looking for the whole chapter page by yourself ;). Hakuneko is doing the job itself, dont interfere :p

![image](https://github.com/manga-download/hakuneko/assets/10671518/d3285cc5-7400-4b07-818e-0a246b7ccc3f)


2) Make sure to use [nightly ](https://github.com/manga-download/hakuneko/releases)because a [fix ](https://youngchampion.jp/series/9aaea584c31f6/pagingList?s=2&page=0&limit=50)was issued last week for Youngchampion-like websites.

**Comment by raeka21** [comment]
i did everything you tell me. But it didn't work. Then I just told myself maybe there was something wrong with the app I'm using, I figure it wouldn't hurt, so I downloaded again the app then bam. It showed. 

Just a story from a few days ago, I'm using the portable one stored in my portable ssd. I opened the app, and the app opened, but it doesn't load and just stuck at the "Checking for updates". I tried to see if the app was properly checking for updates by maybe looking for it in the task manager and sorted by CPU or Network. But nothing is going on. So I thought to myself, "Yeah, this thing is not responding." So I just went close it by force. Maybe it was my fault after all, cause although the app functioned properly even after that, the updates maybe didn't got installed properly.
