### ISSUE TITLE
[<Portal Yaoi>] Connector not working

### ISSUE THREAD

**Issue by NobodyIsBody** [manga-download/hakuneko#6471]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

The website `Portal Yaoi` which uses the madara theme was not added to the list.

The request was made and responded to. But I think they forgot to add it to the list.

This was the only way I could find to warn you.

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
The last issue was closed because its was a duplicate, All you do is create more duplicate and make developers waste their time.
There is no need for multiple issues asking for the SAME website. It will be done when it will be done.

This one https://github.com/manga-download/hakuneko/issues/6187 is enough
