### ISSUE TITLE
[kuaikanmanhua.com] Image quality improvement

### ISSUE THREAD

**Issue by ErickShadow12** [manga-download/hakuneko#6653]
**Is your feature request related to a problem? Please describe.**
The image quality of the manhua is lower than what is downloaded with an external program.

**Describe the solution you'd like**
Well, the ideal would be for it to be downloaded in the highest quality.

**Describe alternatives you've considered**

**Context (please complete the following information):**
 - Your current HakuNeko Version [e.g. 8.3.4]

**Additional context**

evidence:
1:the first is hakuneko with a resolution of 750
2:The other one, which is external, is with a resolution of 1280
![hakuneko](https://github.com/manga-download/hakuneko/assets/126554747/bab25625-0a51-4522-ab62-e3a259a839c3)
![Otro programa](https://github.com/manga-download/hakuneko/assets/126554747/3f50e409-9a84-4362-9bb8-012737e372cf)

**Comment by MikeZeDev** [comment]
This is not really helpful.

1) External program ? Are we supposed to guess which one? :D
2) Also maybe provide the direct link to the manga and the chapter name since its a chinese website and i wont be able to find the good one otherwise.
3) Tested a random manga, its the same resolution than in browser, all 1280

**Comment by nourigns** [comment]
hhhhhhhhhhhhhhhhhhhhhhhhhh
