### ISSUE TITLE
[Site Request] Mangalek

### ISSUE THREAD

**Issue by MohaDC** [manga-download/hakuneko#6680]
**Name of the website**
Mangalek

**Website urls (examples below)**
- Site: https://manga-like.net/
- Manga List: https://manga-like.net/manga/
- Manga example: https://manga-like.net/manga/beginning-awakening-of-mythical-talents/
- Chapter online viewer example: https://manga-like.net/manga/beginning-awakening-of-mythical-talents/80/

**Languages**
Arabic

**Website relationship*
None

**Additional details**
Add any other context details that you may have found (like template to reuse)

**Comment by MikeZeDev** [comment]
Too much manga-like-lek org.net , meeeeeeh
https://github.com/manga-download/hakuneko/issues/6546

**Comment by MohaDC** [comment]
Agree honestly lol, but this one is the best so far you can cancel the
others trust me.
Gmanga, mangalek and manga on line have the biggest dictionary.
Thank you for your hard work

**Comment by MikeZeDev** [comment]
Ive heard the one you mentioned is a copycat

**Comment by MohaDC** [comment]
Strange, its one of the best though.
You wont be adding it?

**Comment by MikeZeDev** [comment]
I dont think so. Not by main contributors anyway. We accept user submitted code tho.

1) Those mangalek-like clones is a mess.
2) So its a mess in my head :)
2) I wont participate in this mess anymore. This will be settled in Haruneko, idk how. At this rate i 'd rather not touching those and have a clean start. Not that they are hard to add but its really confusing.

You underestimate the importance for us to know the truth between "its an unwanted clone" ', its a mirror", and "its a new url".
We want to do things properly. Worst : they all share the same logo and similar URL and names.  I dont speak that langage so its even more confusing

2) No team member have the will to add websites anymore in Hakuneko since we are busy on Haruneko.

**Comment by MohaDC** [comment]
No problem, thank you for your hard work as always

**Comment by 27136773** [comment]
Website probably no longer exist
