### ISSUE TITLE
mangadistrict

### ISSUE THREAD

**Issue by Rimatasa** [manga-download/hakuneko#6681]
https://mangadistrict.com/

Hi this website is great and doesn't have cloud flare anymore please add it

**Comment by MikeZeDev** [comment]
Dupe https://github.com/manga-download/hakuneko/issues/5515

**Comment by Rimatasa** [comment]
> Dupe #5515

Hi this site has manhwa that can't be find with such a high quality picture anywhere else please add it

**Comment by Rimatasa** [comment]
> Dupe #5515

Please This is really unique site

**Comment by MikeZeDev** [comment]
Spamming wont help.

**Comment by Rimatasa** [comment]
> Spamming wont help.

Bro I don't want to spam but manhwa from this site can't be find anywhere else that's all

**Comment by MikeZeDev** [comment]
> I don't want to spam 
But you keep doing it nonetheless.

We are unpaid, we refuse to take ANY FORM of donations. Its a hobby, and those issues are only websites "suggestions".
We also lack manpower/time so no more website will be added to Hakuneko by **main contributors** at this point.
Therefore spamming is quite rude. Wait, spamming is always rude.

* you waste time to write message and opening a duplicate issue
* I wasted time finding the duplicate issue when its something you should have done by yourself before opening a new issue.
* i waste time to answer properly because i dont want to be harsh, and its hard.

Websites will eventually end up in Haruneko so tickets are left opened. 
What you need to learn is patience.
