### ISSUE TITLE
[MangaOnlineFun] Connector chapter keep loading only

### ISSUE THREAD

**Issue by Xenos4th** [manga-download/hakuneko#6702]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

After installing nightly build 8.3.4, when selecting title, the chapter list just loading only, in network fetch keep pending.

### To Reproduce

1. MangaOnlineFun
2. All hail the sect leader
![image](https://github.com/manga-download/hakuneko/assets/113509256/c8d4a368-ddd4-4f63-a070-0fc72e886231)

and this is the SS from my browser (proof that i can access to the website)
![image](https://github.com/manga-download/hakuneko/assets/113509256/603ed3bf-d76c-4110-887c-7d8dadbbea77)

**Comment by Xenos4th** [comment]
When i reinstall 6.1.7 version. it work normal (other connector), but connector MangaOnlineFun still not connecting.

**Comment by Xenos4th** [comment]
![image](https://github.com/manga-download/hakuneko/assets/113509256/fda77990-adfe-464b-b641-5f7044b705fc)

**Comment by MikeZeDev** [comment]
I told you its on your end only, and opening more ticket wont change anything. 🤦 

It will obviously not work in stable as it based on Mangahub and Mangahub changed.
Mangahub and derivated are fixed on nightly only. And i cant reproduce this problem on nightly

The warnings you posted, as you can guess by reading them, have nothing to do with this website.

Not gonna close it because you will open another, ill just put "cant reproduce tag" as i cant reproduce the error.

![image](https://github.com/manga-download/hakuneko/assets/10671518/28b71ff4-9ee1-43f4-8138-b6ad974367a4)

**Comment by Xenos4th** [comment]
Problem solved.

Deleting all cached file, and clean install solved the problem
