### ISSUE TITLE
[Bug] Can log to Piccoma FR website through the inapp browser

### ISSUE THREAD

**Issue by Hachdog** [manga-download/hakuneko#6751]
When opening Piccoma Fr through the inapp Browser, the website doesn't fully load and clicking on the login button doesn't do anything.
Not such issue with Piccoma JP 
![image](https://github.com/manga-download/hakuneko/assets/72262131/b205d0b5-1cc5-4777-9c38-967112a2bf59)

 - OS: Windows7
 - HakuNeko Version 6.1.7]

Thank you for your help

**Comment by MikeZeDev** [comment]
You completely deleted the issue template, perhaps it would have been useful to read it? ;)

Because it clearly asks you to try Nightly version. In your case, it could have solved the problem eventually (i guess its an old browser version problem, nightly browser's version is less old). 

Anyway, you wont be able to do anything until https://github.com/manga-download/hakuneko/pull/6528 is merged. And guess what, it will be available first on nightly build.
