### ISSUE TITLE
[comic-porta.com] Connector not working

### ISSUE THREAD

**Issue by dw714364540** [manga-download/hakuneko#6759]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The connector matched with comic-porta has not been founded yet.
![image](https://github.com/manga-download/hakuneko/assets/22069314/2fb70b12-6218-4dad-bfe5-6387319ad78c)

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
huuu? website is not supported unless i am drunk . Why opening an issue "not working" for a website that Hakuneko devs  doesnt even know the existence until this issue ?

**Comment by dw714364540** [comment]
> huuu? website is not supported unless i am drunk . Why opening an issue "not working" for a website that Hakuneko devs doesnt even know the existence until this issue ?

If the fact that my browser can link to the website but HakuNeko doesnt even know its EXISTENCE should not be considered as a problem , I would be curious what kind of work you deal with every day .

**Comment by MikeZeDev** [comment]
>> If the fact that my browser can link to the website but HakuNeko doesnt even know its EXISTENCE should not be considered as a problem , I would be curious what kind of work you deal with every day .

This answer and the fact you opened this issue clearly means you dont know what you are talking about. Which is understandable, no problem 👍 

Let me explain. Code is not magic. Its impossible for Hakuneko to support a website unless support for it was added first. 
If a website has to be supported it has to be added. You see all those "Website suggestions" in issues?  ;) This is what i meant by "knowing the existence": website must be recognized, support must be coded, devs have to work. Not gonna be technical here.

Its just kinda a bruh moment, to see someone open an issue saying the "website doesnt work" when its not supported in the first place 😄. Its like you got a youtube downloader and you fill a report that it doesnt work on twitch. Common sense dictate that it shouldn't work so why reporting? 

I'd suggest you to open a "website suggestion" issue instead of a "website doesnt work" issue to request this website addition 👍 

I've checked the website, its using a template we know well, inclusion shouldn't be a problem. But it would be in [Haruneko ](https://github.com/manga-download/hakuneko/)( Hakuneko successor) as main devs stopped including new website in Haku to focus on Haru.

**Comment by dw714364540** [comment]
First of all, thanks a lot for your patient explanation and effective suggestions. 

Meanwhile, I got it very well that people who have vast problems to solve tend to get a little irritated when faced with obviously strange questions. However, there are very few people can bear an unfunny joke without hitting back. 

Lastly, I'm sorry about my lack of knowledge. At the same time I still think it would be better to give the advice directly. Code is not magic but word is. Do you agree with me?

**Comment by dw714364540** [comment]
> This answer and the fact you opened this issue clearly means you dont know what you are talking about. Which is understandable, no problem 👍
> 
> Let me explain. Code is not magic. Its impossible for Hakuneko to support a website unless support for it was added first. If a website has to be supported it has to be added. You see all those "Website suggestions" in issues? ;) This is what i meant by "knowing the existence": website must be recognized, support must be coded, devs have to work. Not gonna be technical here.
> 
> Its just kinda a bruh moment, to see someone open an issue saying the "website doesnt work" when its not supported in the first place 😄. Its like you got a youtube downloader and you fill a report that it doesnt work on twitch. Common sense dictate that it shouldn't work so why reporting?
> 
> I'd suggest you to open a "website suggestion" issue instead of a "website doesnt work" issue to request this website addition 👍
> 
> I've checked the website, its using a template we know well, inclusion shouldn't be a problem. But it would be in [Haruneko ](https://github.com/manga-download/hakuneko/)( Hakuneko successor) as main devs stopped including new website in Haku to focus on Haru.

First of all, thanks a lot for your patient explanation and effective suggestions.

Meanwhile, I got it very well that people who have vast problems to solve tend to get a little irritated when faced with obviously strange questions. However, there are very few people can bear an unfunny joke without hitting back.

Lastly, I'm sorry about my lack of knowledge. At the same time I still think it would be better to give the advice directly. Code is not magic but word is. Do you agree with me?
