### ISSUE TITLE
[Bug][Mangago]chapter eorror

### ISSUE THREAD

**Issue by rsgpwxfvc** [manga-download/hakuneko#6827]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
This chapter cannot be downloaded
(Link contains NSFW content)

[
  {
    "connectorID": "mangago",
    "mangaID": "/read-manga/warrior_s_adventure/",
    "chapterID": "/read-manga/warrior_s_adventure/uu/br_chapter-85207/pg-1/",
    "chapterTitle": "bounus.6.5  : Collection from 2020"
  }
]

This chapter can be viewed through the Preview Panel,but this chapter cannot be downloaded

**To Reproduce**

**Expected behavior**
this chapter can be downloaded

**Screenshots**

**Context (please complete the following information):**
Windows11
hakuneko-desktop_8.3.4_windows-portable_amd64

**Additional context**

**Comment by MikeZeDev** [comment]
If you look at the preview, there is a picture that is missing. Its a 404 error, meaning its probably missing on the websites too.

![image](https://github.com/manga-download/hakuneko/assets/10671518/316fac7b-7995-4cf4-8924-0bfcc47df88d)

Since you followed instructions and use nightly (<3) , checking the "ignore errors on downloads" in Settings temporarily may help.
You will miss some pictures anyway, its the website's fault. Find another websites perhaps?

**Comment by rsgpwxfvc** [comment]
@MikeZeDev 
Thank you for your reply.
I just turned on "ignore errors on downloads", but I still can't download any images for this chapter.

Is there anything else I need to do?

**Comment by MikeZeDev** [comment]
Use another website
