### ISSUE TITLE
[<Manganeloa (byAnyACG)>] Connector not working

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [manga-download/hakuneko#6855]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

Titles (tried a couple) are not loading from repos bookmark, only thing that loads is my bookmark on the current chapter in red (if I had a chapter bookmarked). I googled the site and the second link came up and links to who I believe is them. Hovering over the chapter "folder" in one of the titles says: 
```
This chapter has been marked as "recently read" but is no longer available. 
ID: https://mangapanda.in/tanbo...(series title)...-chapter-36


### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

1. Manganelos (by AnyACG)
2. Komi-San Wa Komyushou Desu (Current), Spy x Family (site says hasn't been updated in a while), Yuusha O Oida Sareta Kiyou Binbou (site says hasn't been updated in a while), Otome Game Sekai wa Mob ni Kibishi Sekai Desu (Current), "Tanbo De Hirotta Onna Kishi, Inaka De Ore No Yome Da To Omowareteiru" (site says hasn't been updated in a while)
3. All missing, I can go to "https://m.manganelo.com/wwww" and search each title and it shows up. If i try to go to that "Mangapanda" site norton web browser extension says it's not a "safesite" so I don't know if it works. I searched the connector and it shows up but NOTHING loads in any of the titles.
4. See field above for error message on chapter folder

**Comment by MikeZeDev** [comment]
> bookmark
> Manganelo

That is the problem. This website is always messing with chapters and mangas url. Suddenly a manga goes missing because it just changed url on the website, same for chapters.

Pretty sure if you update the manga list you its working. I am afraid you'll have to redo your bookmarks.

**Comment by MikeZeDev** [comment]
The url of "<Manganelo (byAnyACG)>" is `manganelo.today` and the website is dead, its a parking page. No wonder it doesnt work.

Manganelo**s** (By Anyacg) is `manganelos.com` and is dead too.

Moreover you mentioned a bookmark for "Mangapanda" 😔 

>This chapter has been marked as "recently read" but is no longer available. 
>ID: https://**mangapanda**.in/tanbo...(series title)...-chapter-36

I fail too see how this bookmark is related.

Manganel/Nelo/Nato is a mess, no wonder you got confused 🤷 

I got it. Manganelo.com (Manganel) was rebranded a long time a go to MangaNato with url manganato.com because  Manganelo.com was apparently dead for a while. 3 YEARS AGO. Now we have a manganato & manganelo alive and only Manganato is supported.

Now for your bookmark problem, i am afraid there is no ez way to find where they come from. 
Unless you open them manually.

Even then there is no wait edit bookmarks within hakuneko
