### ISSUE TITLE
[Mangadig]  download issue

### ISSUE THREAD

**Issue by Xeiv** [manga-download/hakuneko#6886]
**Did you read [the troubleshooting guide](https://hakuneko.download/docs/troubleshoot/)**
Yes

**Describe the bug**
When I download chapters sometimes I get 
`mjs/engine/Connector.mjs:618 Error: Failed to load "https://mangadig.com/manga-rg308526/1/11.html" within the given timeout of 30 seconds!
    at mjs/engine/Request.mjs:323 EventTarget
_getPageList @ mjs/engine/Connector.mjs:618`
or
`TypeError: Cannot read property 'isDevToolsOpened' of null
    at MangaDig.mjs:3
    at MangaDig._getPages (MangaDig.mjs:3)
    at MangaDig._getPageList (Connector.mjs:615)
    at Chapter.mjs:111 EventTarget`

**To Reproduce**
1. Go to Mangadig
2. Click on any series
3. Download Multiple chapters
4. first few downloads fine but then the errors start

**Expected behavior**
Chapters get downloaded

**Screenshots**
![image](https://github.com/manga-download/hakuneko/assets/25398298/b83e6e33-3742-4fc9-98bd-189f5bb30288)

**Context (please complete the following information):**
 - OS: Windows 11
 - HakuNeko Version 6.1.7

**Additional context**
The chapters work fine when I open it in my browser or new window in hakuneko

**Comment by MikeZeDev** [comment]
I tested a couple of them, it works. I am sorry, we cant test "any serie".  The point of having a manga and a chapter is to reproduce the bug more easily, just dont say "any serie", mention one pls.

Also.... Did you really try nightly (like you should because you checked the box). 

> HakuNeko Version 6.1.7

Cause its not nightly. 

Try nightly if it doesnt work give us a specific MANGA and CHAPTER. Were you binge downloading? Maybe you were blocked temporarily by the website?

**Comment by MikeZeDev** [comment]
Maybe related as Mangadig and Coco are the same https://github.com/manga-download/hakuneko/pull/6862

**Comment by Xeiv** [comment]
> I tested a couple of them, it works. I am sorry, we cant test "any serie".
> 
> If you were bulk downloading i'd maybe the website blocked you, idk.
> 
> Also.... Did you really try nightly?
> 
> > HakuNeko Version 6.1.7
> 
> Cause its not nightly.
> 
> Try nightly if it doesnt work give us a specific MANGA and CHAPTER. Were you binge downloading? Maybe you were blocked temporarily by the website?

Same issue with the nightly, the series is Divine Coffin Spirit, 
I was binge downloading so might have gotten temp blocked but the exact chapter does work on the website and the new window in hakuneko when I check right after it fails
It randomly happens when I don't binge download too

> Maybe related as Mangadig and Coco are the same #6862

Yeah I think so, this might help with the issue

Also I keep getting these warnings `Provided mime type "image/webp" does not match the file signature and Connector.mjs:717 was replaced by "image/jpeg"!` but I don't think it's related

**Comment by MikeZeDev** [comment]
> Also I keep getting these warnings Provided mime type "image/webp" does not match the file signature and Connector.mjs:717 was replaced by "image/jpeg"! but I don't think it's related

It just means server tell wrong image type so we correct it. Its unrelated. 
I mean the error you got is usually when there is something wrong while loading the page itself and hard to diagnose. 

Maybe, try replacing the content of your Mangadig.mjs by this? 
https://raw.githubusercontent.com/manga-download/hakuneko/cf8fb350f5e512d44bb86bb6252de0305405e28a/src/web/mjs/connectors/MangaDig.mjs

Because i use nightly but i may still have the file from the mentioned fix, so ofc it works for me 🤷

**Comment by Xeiv** [comment]
> It just means server tell wrong image type so we correct it. Its unrelated. I mean the error you got is usually when there is something wrong while loading the page itself and hard to diagnose.

Ah okay
 
> Maybe, try replacing the content of your Mangadig.mjs by this? https://raw.githubusercontent.com/manga-download/hakuneko/cf8fb350f5e512d44bb86bb6252de0305405e28a/src/web/mjs/connectors/MangaDig.mjs
> 
> Because i use nightly but i may still have the file from the mentioned fix, so ofc it works for me 🤷

I think this fixed it but not  sure, I haven't gotten any errors after replacing it though. Thank you 😁

**Comment by MikeZeDev** [comment]
Please keep in mind next time haku update the file could be replaced by the old one. Fix is temporary so youll have do it again until it is officially available to the people.
