### ISSUE TITLE
[Mangalek] Connector not working - Clones Wars strikes back

### ISSUE THREAD

**Issue by PD-ZIRO** [manga-download/hakuneko#6909]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

change domin website mangalek

new domin: https://lekmanga.net/

### To Reproduce

1. Name of connector manga lek
2. Name of manga (if connector update is working) all
3. Name of chapter (if manga update is working) all
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
You said its https://lekmanga.net/. Ok

This person says its https://manga-lek.org/ https://github.com/keiyoushi/extensions-source/issues/1999

Here its https://like-manga.net/ https://github.com/keiyoushi/extensions-source/issues/2032

How are we supposed to chose, especially when no main contributor speak this language? 🤷‍♂️

**Comment by PD-ZIRO** [comment]
> You said its https://lekmanga.net/. Ok
> 
> This person says its https://manga-lek.org/ [keiyoushi/extensions-source#1999](https://github.com/keiyoushi/extensions-source/issues/1999)
> 
> Here its https://like-manga.net/ [keiyoushi/extensions-source#2032](https://github.com/keiyoushi/extensions-source/issues/2032)
> 
> How are we supposed to chose, especially when no main contributor speak this language? 🤷‍♂️

bro, this page has many domains, and every time a new domain is opened or the domain is changed, you try to add one domain and keep the rest as backup.  I rely on the first link, the third is another domain for the site, and the second is a similar site 

-No problem, bro. I can help you in this language at any time ^^

**Comment by MikeZeDev** [comment]
Thats not how it works. Some could be better than the other, the content also may not be the same.

Do they have the same mangas, manga numbers and sames chapters? I doubt so .

See, if we choose a domain someone tomorrow will ask for the others, its endless.

They could be mirrors yes, but they also could be unauthorized clones. And we dont like sites like that.

What can be done is : url as a setting. Users will keep complaining because no one will know but you will use the one you want.
As long as they all use Madara it will work.

You can check how its done in other websites and rewrite your PR accordingly perhaps , or ask how its done on it :)
