### ISSUE TITLE
[Site Request] Topmanhua

### ISSUE THREAD

**Issue by Iann29** [manga-download/hakuneko#6959]
**Name of the website**
topmanhua

**Website urls (examples below)**
- Site: https://topmanhua.com
- Manga List: https://topmanhua.com/manga/?m_orderby=alphabet
- Manga example: https://topmanhua.com/manhua/pick-me-up/
- Chapter online viewer example: https://topmanhua.com/manhua/pick-me-up/chapter-1/

**Languages**
English

**Comment by MikeZeDev** [comment]
Did you open Hakuneko before requesting? This website has been supported for 5 years now.

https://github.com/manga-download/hakuneko/pull/534

If you want to report it as "non working" dont open a "website suggestion" issue.
And before you start doing that, dont, its pointless, because of cloudflare.
