### ISSUE TITLE
[<Lezhin Kor>] Connector not working

### ISSUE THREAD

**Issue by jomaister** [manga-download/hakuneko#6961]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Chapter list isn't refreshing

### Describe the bug

chapter lists aren't showing anything for recent ones i've purchased. chapters pop up for manga i've purchased months ago. i tried purchasing two different chapters from two different manga titles today and they aren't showing up at all. there is no error message given either. my hakuneko is up to date.

### To Reproduce

1. purchased comic on https://www.lezhin.com/ko today
2. put login into hakuneko
3. manga shows up on the manga list
4. it states there are 0/0 chapters when the website is working fine and says i purchased all the chapters

**Comment by MikeZeDev** [comment]
1) I am gonna state the obvious but are you logged in hakuneko? Sorry i need to ask that.

2)  > my hakuneko is up to date.

Yeah yeah yeah, as stated in the issue, you tried nightly right? No sure it helps and no offense but i must make sure, people check the box "i tried nightly" when they didnt at all.

3) We cant properly test for paid chapters unless we paid ourselves, you know what i mean.
Therefore its hard to diagnose.

4) Keep in mind that chapter list is cached once its fetched meaning if you fetched one BEFORE buying more chapter you will miss chapters only you restart hakuneko.

5) There is a pending fix for Lezhin websites . https://github.com/manga-download/hakuneko/pull/6834.  
I tested it again and i got chapter BUT obviously not paid one.

I am tented to mark this "Fixed by https://github.com/manga-download/hakuneko/pull/6834" but i dont know? Would you test it perhaps?  


Make sure you use nightly and launched it at least once, Find Lezhin.mjs on your computer open with Notepad and replace its content by this https://raw.githubusercontent.com/manga-download/hakuneko/5f7734f09136028a0cdb253d34c10f38740232cd/src/web/mjs/connectors/templates/Lezhin.mjs

**Comment by yimeji** [comment]
I would like to add that I similar issue. 
It works on the eng site fine but it doesn't on korean. 

The episode listed fine, free and paid however it got error when downloading.
