### ISSUE TITLE
[Feature] Combine chapters into the corresponding volume

### ISSUE THREAD

**Issue by Username9980** [manga-download/hakuneko#6962]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Combine every chapter into the corresponding volume of the specific manga if the information is available in the specific connector.

**Comment by Sheepux** [comment]
I don't know how many connectors have %VOL% available as it's based on the title. Do you have any connector in mind ?

**Comment by Username9980** [comment]
> I don't know how many connectors have %VOL% available as it's based on the title. Do you have any connector in mind ?

MangaDex

**Comment by MikeZeDev** [comment]
Too few websites gives the information for it to be worth. And wdym by combine exactly?  Same folder download? It would be a mess when it comes to recognize downloaded content. We do not cache chapters lists at all i am afraid.

I think something like a post command would be fine providing we expose the volume number.

**Comment by Username9980** [comment]
> Too few websites gives the information for it to be worth. And wdym by combine exactly? Same folder download? It would be a mess when it comes to recognize downloaded content. We do not cache chapters lists at all i am afraid.
> 
> I think something like a post command would be fine providing we expose the volume number.

By combine I mean, there should be an option similar to the [mangadex-dl's cbz-volume command](https://mangadex-dl.mansuf.link/en/stable/formats.html#cbz-volume), this should go to every site that has %VOL% available, not just MangaDex.

Sorry for the late reply.

**Comment by 27136773** [comment]
_Since this is requested quite often, i'll give a more detailed explanation which can be used as reference (e.g. Discord link)._

Combining multiple chapters into a single comic book archive is to complex to be achieved in a generic way for hundreds of websites due to various challenges:

## Missing Information
Many websites only provide a list of chapters. There is no additional information about volumes or books, which is necessary to compile multiple chapters into a single comic book archive

## Naming/Sorting
Since multiple chapters are combined, it is essential to ensure the images are named correctly to appear in the correct order. Shouldn't be a problem? Then you probably never saw `Chapter 7½`, `Ch. 12.5`, `Second Chapter`, ...

## Download Detection
Lets assume a website only provides chapters and somehow HakuNeko uses some magic to combine multiple chapters into volumes. HakuNeko detects downloaded chapters by comparing the downloaded files with the list from the website. It is quite difficult to detect the already downloaded chapters when they are hidden within a combined comic book archive.

## Incomplete Downloads
Lets assume a user downloaded Volume 4 which contains chapter 23-29 into a single combined comic book archive. Now chapter 30 is released which is also part of Volume 4. Quite a programming challenge to get this done correctly.

## Settings
There are already enough options to confuse the users. Adding a feature to combine multiple chapters into a single comic book archive comes with a set of additional options bloating the settings even more.

## Post Command
There is already a mechanism which allows each (experienced) user to combine multiple chapters into comic book archives by utilising the Post Command. Developing a script to do this is probably difficult, but still 100 times easier than implementing this feature in HakuNeko.
