### ISSUE TITLE
[Random Scans] Connector not working (Dead website)

### ISSUE THREAD

**Issue by Dougu77** [manga-download/hakuneko#7027]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

Since I'm not the owner, this type of issue seemd better.
https://randomscanlators.net/ is a dead website, the scan changed it's name and website to https://luratoon.com/
Here they say this information: https://mangadex.org/group/12131c70-9eed-4d18-926d-6837e4c01c46/lura-toon

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Read the issue template. Its said "tried nightly? ". You checked the box meaning you have tried nightly, but i bet you havent.

Because 

https://github.com/manga-download/hakuneko/blob/4011a9e3dca82339e2770a73cac7a8683ee11be9/src/web/mjs/connectors/RandomScan.mjs#L7

Its already luratoon in nightly. Please next time follow instructions and dont just randomly check boxes in forms, doing that is dangerous :D. We both lost our time.
