### ISSUE TITLE
[MangaDex] Connector not working

### ISSUE THREAD

**Issue by hygfvtt463** [manga-download/hakuneko#7030]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

[mangaDex](mangedex.org)
It's a good website. But it's not working on Hakuneko :( sad. Could you please fix this? 

Also I found most of the high-quality connectors are not working well, can anyone share some good available connectors ?
Currently I'm using MangaLife and MangaSee. They are overall ok.
Appreciate your time and Thank you so much !

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
Hello.

1) Its no use saying how you love mangadex. We need concrete stuff, like screenshot and error message.

2) Mangadex servers are known to be unstable, and mangalist cant be updated because after some time server says NO. When server says no there is nothing we can magically do. Their list is freaking huge. The solution would be on your end, go in settings and increase mangadex throttling to something like 5000.

3) You checked "Nightly didnt solve my problem". **You clearly didnt try nightly version because nightly use a cached mangadex list from our own server**. And it works i just checked myself. Please follow the instructions correctly. 

Dont check random boxes on forms. Dont sign contracts without reading and understanding them. Next time i'll introduce a "I agree to give my first born and all my organs to Hakuneko team" checkbox perhaps ? :D

4) If the manga is still missing from the cached list use copy paste : https://hakuneko.download/docs/FAQ/#copy-and-paste
