### ISSUE TITLE
[LectorManga] Connector not working (URL's were change)

### ISSUE THREAD

**Issue by Erev14** [manga-download/hakuneko#7092]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

The connector urls change (seem to change url every year)
new url: https://visortmo.com/
manga list: https://visortmo.com/library
manga example: https://visortmo.com/library/manhwa/217/solo-leveling
manga chapter name: Capítulo 200.00
manga chapter url: https://visortmo.com/viewer/bd703deb9beb2e3593d68b45e54b704f/cascade

### To Reproduce

The connector urls 
1. Name of connector LectorManga 
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)
![Captura desde 2024-05-19 17-46-31](https://github.com/manga-download/hakuneko/assets/15682064/fc29d2e8-899e-4005-8965-74eb156e6c3b)

**Comment by MikeZeDev** [comment]
1) We have LectorManga. Which is dead. Dont name the issue using a dead website name, use the good one : TuMangaOnline.
The address you point is indeed for TuMangaOnline

2) If you had properly followed the instructions in the issue template you wouldnt have completed this issue. Because it works following the instructions. Please read properly and stop wasting your time and our time.

Because this has been fixed like, 2 month ago https://github.com/manga-download/hakuneko/commit/4fb1b74db264be96cf1882505aa97d9e570ad2f3

![image](https://github.com/manga-download/hakuneko/assets/10671518/6691e328-df23-431f-9329-131b29258520)
