### ISSUE TITLE
[ KOMIKTAP, MANGASUSU, WESTMANGA, KOMIKCAST ] Change domain

### ISSUE THREAD

**Issue by wow2134** [manga-download/hakuneko#7245]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

website change domain

- komiktap.me -> komiktap.info
- m.mangasusu.co -> mangasusuku.xyz
- westmanga.org -> westmanga.fun
- komikcast.ch -> komikcast.cz

![image](https://github.com/manga-download/hakuneko/assets/35753907/3af3f515-7c2c-42f1-8050-d4f9472adfc5)
![image](https://github.com/manga-download/hakuneko/assets/35753907/87b92e3d-b047-4f13-879e-faf3a25c7240)

### To Reproduce

-

**Comment by MikeZeDev** [comment]
![image](https://github.com/manga-download/hakuneko/assets/10671518/28a37534-8673-40be-81f8-16d92f7a3011)

We already support mangasusuku, it WONT replace mangasusu.

**Comment by MikeZeDev** [comment]
Westmanga is already correct, Its fixed in nightly https://github.com/manga-download/hakuneko/blob/5a79824dd060552e0fd9721f3e9ee62d26ce345d/src/web/mjs/connectors/WestManga.mjs#L4

It means you just randomly checked boxes without reading and following instructions.
I am tempted to close this and not doing anything just because you cant simply READ simple instructions.

![image](https://github.com/manga-download/hakuneko/assets/10671518/f42c49f2-9d71-48d2-838f-a7fb72d0f942)
