### ISSUE TITLE
[Question] Comick Has 30000+ but in Hakuneko its 1400+ ?

### ISSUE THREAD

**Issue by La-michi** [manga-download/hakuneko#7268]
Hi, when i go in Comick (comick.io) website it has 30,000+ comics, 

![image](https://github.com/user-attachments/assets/0d355ce8-b543-44bb-955e-0dc2052a96f8)

but when in hakuneko its 1470.
no idea kindly tell me is it an issue or something?

![image](https://github.com/user-attachments/assets/c132fa4c-1716-40a0-8f35-38229d44c771)

**Comment by MikeZeDev** [comment]
Dont spam issues i told you its normal

If y u had used the search feature before opening an issue , like you should have you would never have opened an issue

https://github.com/manga-download/hakuneko/issues/6516

Test it yourself : open manga list on the website, in your own browser. Scroll down. Scroll Down again and again. Website stops you after a fixed number of "pages".

![image](https://github.com/user-attachments/assets/76893bbd-1a44-4cc4-9545-b9c95f2f225e)

There is the Clipboard feature (aka Copy paste feature) to get around such problematic websites with no or incomplete manga lists and access the desired manga.

**Comment by MikeZeDev** [comment]
Yeah, to be fair we have no definitive answer.

I'd like to give users at least a little list because copy pasting every single manga they want is kinda a hassle. There is definitely a way to get a list, albeit incomplete. On many websites with incomplete lists (hello japan's bookstores) we are still providing a list.
But even incomplete a list have its uses.  

I dont see why we shouldnt keep a list for Comick, **especially when the problem is so visible on the website itself even for the end user** (unlike those bookstore i talked about).

Users must be informed, thats for sure.  A message (when? ) and perhaps a tag on the website? 😔
