### ISSUE TITLE
[Site Request] mangahot

### ISSUE THREAD

**Issue by storyteller24** [manga-download/hakuneko#7290]
**Name of the website**
mangahot

**Website urls (examples below)**
- Site: https://web.mangahot.jp/
- Manga List: https://web.mangahot.jp/ranking/
- Manga example: https://web.mangahot.jp/works/detail.php?work_code=z_R0226
- Chapter online viewer example: https://web.mangahot.jp/works/view.php?story_id=31491&utm_source=

**Languages**
Japanese

**Website relationship*
Nope

**Additional details**
Look like they slice the images to encrypte them like Comic Gardo (when using F11 button) but much more complicated.

**Comment by MikeZeDev** [comment]
Search first. Dont open duplicates. 
![image](https://github.com/user-attachments/assets/d8448ded-d6b1-4116-af89-3b3fae63db0c)

**Comment by MikeZeDev** [comment]
I told you already dont open duplicate issues its useless and wont speed up the process . Why are you persisting? 

![image](https://github.com/user-attachments/assets/c2ee1768-b0df-46d6-9be5-eec6dba977c9)

**Comment by MikeZeDev** [comment]
Moreover, the tag on the not-closed issue tells us its done in [Haruneko](https://github.com/manga-download/haruneko).
Use Haruneko because it most likely wont be done  in Hakuneko 

Ho and another thing you should be aware : the website code is ugly, therefore we had to adapt so loading a chapter with many images can take long but it cant be helped.  At least it works ;)


![image](https://github.com/user-attachments/assets/1caff485-58a1-4e73-83a7-825b767a8c77)
