### ISSUE TITLE
[Batoto (by AnyACG)] Connector not working

### ISSUE THREAD

**Issue by ghost** [manga-download/hakuneko#7317]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Other

### Describe the bug

The link pasted via clipboard is not working.

### To Reproduce

1. Batoto (by AnyACG)
2. Paste any batoto link via clipboard.
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
> The link pasted via clipboard is not working.

People are able to chose which batoto mirror they want to use. If you pasted an url that does not match your current batoto mirror url it obviously wont be recognized. Check your batoto mirror url in settings ? 

Because it works
![image](https://github.com/user-attachments/assets/4ec75979-429f-4726-87d9-ae18a5742fa0)

**Comment by ghost** [comment]
My bad. It's working now. Thanks.
