### ISSUE TITLE
[Iris Scanlator] Domain change

### ISSUE THREAD

**Issue by jhonatanDS** [manga-download/hakuneko#7345]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Many Portuguese websites (almost all of them) are not working, many have changed their name/domain (url) or changed their WordPress template/theme, I wanted to know if there is a way for me to manually add the new websites?

Below are some examples of new websites:
https://oldi.sussytoons.com
https://imperiodabritannia.com
https://mangaeon.com
https://slimeread.com/

Below are some examples of websites that have changed their url or template:
Mode Scanlator = https://www.modescanlator.com
Cerise Scans = https://cerisetoon.com
Demon Scan = https://dsectcomics.org
Iris Scanlator = https://irisscanlator.com.br

The website below works but does not load all the titles in Hakuneko:
Sasikaiscan = https://saikaiscans.net

### To Reproduce

1. Name of connector
2. Mode Scanlator
3. https://site.modescanlator.net/comics

**Comment by MikeZeDev** [comment]
1) Pretty sure there are already issue opened for at least one of the "new website" you mentionned (slimeread i think, perhaps others)
In that case you have to search before in order not to create a duplicate. Its saving us precious time. Dont open duplicates

2) Cerisetoon is behind Cloudflare, no point making the change, it wont work. Moreover, i know for sure this website is totally broken, in Firefox AND in Chrome, because i tried adding it to Haruneko.

![image](https://github.com/user-attachments/assets/bc60ac95-bde7-451e-9067-c668bfea897a)

3) ModeScanlator need a total rewrite they changed everything, it most likely wont be done as we are focusing on Haruneko.
It is indeed planned in Haruneko, with Cerise. FYI they share the same template so i added both.

4) READ THE TICKET INSTRUCTIONS, POR FAVOR

![image](https://github.com/user-attachments/assets/81a6f89a-6f1d-4879-9a5f-93cd4e90b2a0)
![image](https://github.com/user-attachments/assets/dae106e9-0dba-44bf-9a98-8127905cf71c)

You checked without reading. You could have agreed to sell me your first born by checking without reading, you know ? :D

5) Thanks for reporting irisscanlator 👍 

6) Like most PT-BR website, saikai cant be accessed without pt-br ip. 
![image](https://github.com/user-attachments/assets/45ced05a-41a8-41dc-b933-5f8faffd20aa)

Moreover, if a website list doesnt got all manga, you can still paste manga link in Hakuneko.
We cant do anything if website liste is incomplete besides telling you to use clipboard so even if i check if refreshing list gives you incomplete results most likely its the website problem and youll have to use clipboard.

Clipboard method is described in user manual btw.

**Comment by MikeZeDev** [comment]
And please , ONE ISSUE PER TICKET next time :D

**Comment by MikeZeDev** [comment]
As for adding site yourself, you can contribute, yes :) First 2 are using Madara template it shouldnt be hard,
