### ISSUE TITLE
MangaNel chapters don't update.

### ISSUE THREAD

**Issue by gyegye** [manga-download/hakuneko#737]
Manga is not updating on Manganel

https://manganelo.com/

**Comment by hypoflex** [comment]
could you state more specific what's not working about it?
Because your statement could mean multiple things. 

1. the manga's itself are not being retrieved by hakuneko.
2. the manga chapters are not being retrieved by hakuneko.
3. the manga's chapter received a update but the update is not being retrieved by hakuneko 


i've gone through "quickly" checking the connector and it does seem to pull the manga list and manga chapters totally fine, with a but at the end.

the retrieving of the manga list takes pretty long. to be exact about 40.000 milliseconds.
![image](https://user-images.githubusercontent.com/36196198/70717117-ff0b9f00-1ced-11ea-822e-8d0ff1d51d70.png)
so this may give off it's not working correctly.

I advice you to retry to retrieve the manga list (expecting this is the issue you're having)
and pressing F12 to open the dev-tool. next navigate to the Network tab in the dev-tool to see the network activity and see if all manga's are being pulled.

as stated above this process may take some time, but since it's saved in hakuneko's cache it's something you only have to do once.

**Comment by gyegye** [comment]
I have just checked again and the problem is 2 the manga chapters are not being retrieved by hakuneko.
I checked on both previously downloaded manga and new manga and the network loads the manga but no chapters show up

**Comment by 27136773** [comment]
Possible duplicate of #731

**Comment by hypoflex** [comment]
@gyegye could you specify the manga  that's giving this issue, since the one's i tried are working.
then i can see if i can  reproduce the issue on my side with the same manga.

and maybe find out what the issue is.
thanks in advance

**Comment by gyegye** [comment]
Yes similar to #731 
i have tried looking for
- one piece
- solo leveling
- nanatsu no taizai
- boku no hero academia

looking up goblin slayer seemed to work

**Comment by 27136773** [comment]
> Yes similar to #731
> i have tried looking for
> 
> * one piece
> * solo leveling
> * nanatsu no taizai
> * boku no hero academia
> 
> looking up goblin slayer seemed to work

All of the listed mangas are working fine for me and showing the chapters.
Try with the latest nightly build.
Make sure your manga list is up to date as manga links may have changed.
