### ISSUE TITLE
can't update manga nor chapter list 

### ISSUE THREAD

**Issue by Nitro963** [manga-download/hakuneko#746]
Manga is not updating on
manga.ae
gmanga.me

and on-manga.me seems to be down

**Comment by MohammadNsearaty** [comment]
nigga

**Comment by hypoflex** [comment]
seems like gmanga.me is pulling the wrong content for the chapters
![image](https://user-images.githubusercontent.com/36196198/70715323-560f7500-1cea-11ea-9b7a-2a33dee4997f.png)

manga.ae seems to be down cause its failing to pull
going to the website itself will get you redirected to https://www.mangaae.com/, possibly only a source url change needed.

**Comment by Nitro963** [comment]
it's turns out that on-manga.me changed to onma.me

**Comment by 27136773** [comment]
https://www.mangaae.com is working for me
![image](https://user-images.githubusercontent.com/27136773/70930515-ab72bb80-2035-11ea-955e-952bbfa7de69.png)

----

https://gmanga.me is working for me, but it is very slow...
![image](https://user-images.githubusercontent.com/27136773/70930795-4d92a380-2036-11ea-82b1-0fa662149409.png)

----

https://on-manga.me is not working for me, probably because of new domain...
![image](https://user-images.githubusercontent.com/27136773/70931013-cc87dc00-2036-11ea-8e56-4b60cd5f0350.png)
