### ISSUE TITLE
[Site Request] vi.mangamew.com

### ISSUE THREAD

**Issue by enzief** [manga-download/hakuneko#7487]
**Name of the website**
mangamew

**Website urls (examples below)**
- Site: https://vi.mangamew.com/
- Manga List: https://vi.mangamew.com/tu-truyen/
- Manga example: https://vi.mangamew.com/truyen/vo-than-chung-cuc-2314/
- Chapter online viewer example: https://vi.mangamew.com/doc-truyen/vo-than-chung-cuc/chuong-1-126482/

**Languages**
Vietnamese

**Website relationship*
N/A

**Additional details**
It seems https://vi.mangamew.com and https://mangamew.com have different manga lists.

**Comment by MikeZeDev** [comment]
Website provide VT and ENG content. Gotta check how to handle that

**Comment by enzief** [comment]
One thing I notice is when the reading mode is selected as "vertical" the website loads all the chapter pages, otherwise only the first 3.

**Comment by MikeZeDev** [comment]
> One thing I notice is when the reading mode is selected as "vertical" the website loads all the chapter pages, otherwise only the first 3.

Should no be a problem. There are always solutions ^^

**Comment by MikeZeDev** [comment]
Wont be done. Most "recent update" was 4 years ago so any chapter i try to load got only 404 errors, or 403 errors.
If recent entries got the problem you can imagine its worst for 

Its because they just hotlink images from many others sites (already supported by Haruneko or long dead) and dont host anything themselves so it ends up like that.

Ive seen hotlinks to Mangakakalot, Mangadoom, and long dead viet websites. You'd better use those sites instead of just a lazy hotlinker.

Its so full of errors that people will endlessly complain that "pages doesnt load" :/
