### ISSUE TITLE
[<truyenqq>] Connector not working they change to truyenqqto(.)com

### ISSUE THREAD

**Issue by BookerSmoi** [manga-download/hakuneko#7543]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

they change their website to truyenqqto.com

### To Reproduce

1. Name of connector
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by MikeZeDev** [comment]
https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/TruyenQQ.mjs

Url is already truyenqqto.com.

You obviously didnt read the issues instructions despistes checking everything. You'd have use Nightly, where url is good.

Nonetheless The problem is CLOUDFLARE

![image](https://github.com/user-attachments/assets/51490f9b-6e8f-4c82-9dd3-fc9794bcf177)

Just  give up and use a less crappy website, CF cant be bypassed.
