### ISSUE TITLE
[Batoto (by AnyACG)] Connector not working, Bato.to is no longer available

### ISSUE THREAD

**Issue by Ren6422** [manga-download/hakuneko#7622]
### Is there an existing issue for this connector?

- [X] I have searched the existing issues

### Did you read the troubleshooting guide ?

- [X] I read it but nothing seems related

### Is the website of the connector working properly ?

- [X] Yes i'm able to see the manga within my standard browser

### Make sure to try Nightly Build

- [X] Yes nightly build didn't fix the issue

### What kind of issue are you encountering

Manga list isn't refreshing

### Describe the bug

Copy pasting Bato.to URLs no longer working.
Bato.to site redirecting to https://xbato.org/
Seems like they already not working.
![Screenshot 2024-12-22 114701](https://github.com/user-attachments/assets/c8a24c1e-dcbf-414a-a8fc-617258406036)
![Screenshot 2024-12-22 115001](https://github.com/user-attachments/assets/36a6cd8f-5e1a-4af6-a364-72ebdfc17fd3)

### To Reproduce

1. Name of connector Batoto (by AnyACG)
2. Name of manga (if connector update is working)
3. Name of chapter (if manga update is working)
4. Copy any relevant error message that appears in a popup or (advanced) within the console (press F12)

**Comment by imnotagamedev** [comment]
are you getting the 'cannot read property text of undefined' error? because i'm getting that whenever i try to use batoto too 😞

**Comment by MikeZeDev** [comment]
1) Juste use settings 
![image](https://github.com/user-attachments/assets/849d9614-f613-4a59-8057-d4dca082a99c)

2) Useless, as its Cloudflared, use another website. Or find a non Cloudflared mirror , good luck.
![image](https://github.com/user-attachments/assets/8df23bce-81e2-4c95-83a7-c535972e3e92)

**Comment by MikeZeDev** [comment]
Wont fix as there is a setting for domain, and cant do anything about cloudflare.

**Comment by Ren6422** [comment]
> are you getting the 'cannot read property text of undefined' error? because i'm getting that whenever i try to use batoto too 😞

Yes, I also get this error. Chapter list is no longer deployed.
I don't know what to do.

**Comment by imnotagamedev** [comment]
> Yes, I also get this error. Chapter list is no longer deployed. I don't know what to do.

i moved on to mangadex, i think its the closest alternative to bato.to

**Comment by goku90504** [comment]
while xbato.com seems to be the sites new default I was able to make it work by going to the manga I want on xbato.com then changing out the xbato.com part of the address to bato.to then using the paste link into HakuNeko specifically 
https://xbato.com/series/148096 doesn't work with HakuNeko
https://bato.to/series/148096 does work with HakuNeko at least for me 
If the programmer doesn't want to fix this then I at least leave this here for others who face the same issue to have a hopefully works for them as well work around

**Comment by MikeZeDev** [comment]
* Stop useless complains and use the damn setting already. 
All you had to do was to follow the instructions in this [post ](https://github.com/manga-download/hakuneko/issues/7622#issuecomment-2558410439). If "change domain in settings" isnt clear enough i dont know what to say.

![Image](https://github.com/user-attachments/assets/fcc2526f-911e-4dc5-accd-e3c43cce2652)

* We wont change the domain for a deprecated domain. Nope, never. This is why there is a custom domain option 🤦 .

* Tried "bato.to" and it works. 

![Image](https://github.com/user-attachments/assets/c6c8d03a-fcf3-4c18-a796-624f41322b8c)

Locking because people cant read properly and will keep bumping old issue.

Of course, if you encounter any problem with a **Non Cloudflared** Bato mirror, a new ticket for that will be welcomed <3
