### ISSUE TITLE
Cannot download chapter from CrunchyManga (premium)

### ISSUE THREAD

**Issue by annieonmymay** [manga-download/hakuneko#811]
Hello, I am trying to download the manga _Memoirs of Amorous Gentlemen_ off of CrunchyManga via the latest stable version of HakuNeko for mac (v5.0.8), and chapter 13 is not downloading. I do have a Crunchyroll premium account and I have inputted that information into HakuNeko so it has no issue downloading anything else from Crunchyroll, including the others chapters of this manga. It even loads all of the pages of chapter 13 in preview perfectly, so I know it can access them in some capacity. The error I have been getting just says "TypeError: Failed to fetch".

My macbook OS is Mojave, if that's info you need as well.

Fixes I have already tried which haven't worked:

- Uninstalling and reinstalling the latest stable version
- Installing and using the latest nightly updated version instead (v6.1.7)
- Tried on another macbook with the stable version and encountered the exact same issue (so this doesn't seem to have anything to do with my computer in particular)
- Deleting my crunchyroll info from HakuNeko and then signing in again.

If anyone can help me determine the source of this issue or come up with a fix it would be greatly appreciated :)

**Comment by Ever4engel** [comment]
Hakuneko 5.0.8 is in discontinued support you should use Hakuneko 6.

**Comment by annieonmymay** [comment]
Someone informed me that support for 5.0.8 has been discontinued (even though it's the newest stable version) but, as I said before, this issue still arises with the latest nightly release v6.1.7.

**Comment by Ever4engel** [comment]
yes, support for 5.0.8 has been discontinued (you should use the nightly build 6.1.7 instead of 5.0.8 (it's way stable for daily use)  
Right now ronny is on vacation, he should fix this later.

**Comment by ralvarador** [comment]
Well, At this moment, with Hakuneko 5.0.8, x64, Windows 10, no issues with Crunchyroll's manga.
But it is good read about 5.0.8 being discontinued, time to try the nightly...

**Comment by 27136773** [comment]
Page 19 in chapter 13 is broken.
See [FAQ](https://github.com/manga-download/hakuneko/wiki/FAQ) 6
I have no adobe flash player on my system, so i cannot tell if this is a problem in HakuNeko or a problem on CrunchyRoll's end.

Please try to read on CrunchyRoll (Browser) and check if the image that is missing in HakuNeko is also missing on CrunchyRoll, if so the problem is on CrunchyRoll's end. If the image is shown correctly it is a problem with HakuNeko.

<img width="1232" alt="Screen Shot 2020-01-01 at 1 07 44 PM" src="https://user-images.githubusercontent.com/27136773/71641194-b9f8de00-2c97-11ea-858b-a0608398464d.png">

**Comment by 27136773** [comment]
This is partially a problem on CrunchyRoll's server, sometimes a localized image is not found (e.g. 404 not found). In case of such a problem HakuNeko now tries to download the invariant image instead of the localized image.
