### ISSUE TITLE
mangago manga sync

### ISSUE THREAD

**Issue by BhenChod1221** [manga-download/hakuneko#866]
hello there i am facing an issue with hakuneko about new manga syncing of mangago whenever i want to sync new manga of mangago in hakuneko it doesn't load new manga and still fixed on **34409** total manga of mangago. Can you please fix the issue why i can't be load more new manga's of mangago.

Thanks in Advanced!

**Comment by ronny1982** [comment]
The [mangalist from MangaGo](https://github.com/manga-download/hakuneko-cdn/tree/master/mangago) comes from [HakuNeko's CDN sever](https://github.com/manga-download/hakuneko-cdn).
Due to lack of time the server hasn't been updated for quite a while now.

Use the copy/paste feature to download mangas from MangaGo.
see: [FAQ #5](https://github.com/manga-download/hakuneko/wiki/FAQ)
