### ISSUE TITLE
Shonen Magazine Pocket not working

### ISSUE THREAD

**Issue by 11thDoctr** [manga-download/hakuneko#963]
Can't download any chapters for any series. 

Gives "TypeError: Cannot read property "filter" of undefined"

**Comment by jintorau** [comment]
Similar error for ShonenJump+, though I get "TypeError: Cannot read property "Single" of null"

**Comment by 0xh3LL0** [comment]
want to create new issue about this site, but then i see someone already did,
fix please...
free manga only available for short amount of time, i want to download them before it become paid.

**Comment by 0xh3LL0** [comment]
looks like it still broken,
tried both latest stable (6.1.7) and latest nightly (from 9 hours ago, 2ed7318)
i install them by overwriting the old installation (portable 6.1.5)
the old one can detect them, but cant download,
the new one didnt detect new chapter at all,
just in case, i also tried to delete the cache folder, so that hakuneko can re-new them, but still didnt work,
try this one: https://pocket.shonenmagazine.com/episode/10834108156739667145

**Comment by 0xh3LL0** [comment]
@ronny1982

**Comment by 27136773** [comment]
It was discovered that there are invalid links on some chapter pages, e.g.
https://pocket.shonenmagazine.com/api/viewer/readable_products?current_readable_product_id=10834108156739667145&amp;number_since=0&amp;number_until=0&amp;read_more_num=250&amp;series_id=10834108156711623690&amp;type=episode
which leads to a 404 error.
The second link on the chapter page works just fine:
https://pocket.shonenmagazine.com/api/viewer/readable_products?current_readable_product_id=10834108156739667145&amp;number_since=8&amp;number_until=0&amp;read_more_num=250&amp;series_id=10834108156711623690&amp;type=episode

The only noticeable difference is the `number_since` parameter which is the same as the `number_until` in the non-working link (which makes no sense anyway).
It is still unknown how the website knows that this link is invalid.

**Comment by 0xh3LL0** [comment]
thank you very much!
